import { metricsFromCast } from "./metrics";
import type { CastMonthlyTrendPoint, TrendMonthlyInput } from "./types";

export const monthStatus = (month: string, to: string, now = new Date()): "COMPLETE" | "PARTIAL" => {
  const monthEnd = new Date(`${month}-01T00:00:00Z`); monthEnd.setUTCMonth(monthEnd.getUTCMonth() + 1); monthEnd.setUTCDate(0); monthEnd.setUTCHours(23, 59, 59, 999);
  const requestedEnd = new Date(`${to}T23:59:59.999Z`);
  return monthEnd < now && requestedEnd >= monthEnd ? "COMPLETE" : "PARTIAL";
};
export const calendarDays = (month: string) => { const start = new Date(`${month}-01T00:00:00Z`); return new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + 1, 0)).getUTCDate(); };
export const monthBounds = (month: string) => { const start = new Date(`${month}-01T00:00:00Z`); const end = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + 1, 0)); return { from: `${month}-01`, to: end.toISOString().slice(0, 10) }; };
export const normalizeMonthRange = (from: string, to: string) => { const first = `${from.slice(0, 7)}-01`; const endMonth = `${to.slice(0, 7)}-01`; const months: string[] = []; for (const cursor = new Date(`${first}T00:00:00Z`), end = new Date(`${endMonth}T00:00:00Z`); cursor <= end; cursor.setUTCMonth(cursor.getUTCMonth() + 1)) months.push(cursor.toISOString().slice(0, 7)); return { from: first, to: monthBounds(endMonth.slice(0, 7)).to, months }; };
export const activeCoverage = (month: string, activeFrom: string | null, activeTo: string | null) => { const bounds = monthBounds(month); const start = activeFrom && activeFrom > bounds.from ? activeFrom : bounds.from; const end = activeTo && activeTo < bounds.to ? activeTo : bounds.to; const activeDaysInMonth = !activeFrom || !activeTo || start <= end ? Math.max(0, Math.floor((Date.parse(`${end}T00:00:00Z`) - Date.parse(`${start}T00:00:00Z`)) / 86400000) + 1) : 0; return { periodFrom: bounds.from, periodTo: bounds.to, activeFrom, activeTo, activeDaysInMonth, calendarDaysInMonth: calendarDays(month), isPartialActiveMonth: activeDaysInMonth > 0 && activeDaysInMonth < calendarDays(month) }; };
export const buildTrendPointBase = (input: TrendMonthlyInput): CastMonthlyTrendPoint => ({ castId: input.cast?.fact.castId ?? "", month: input.month, label: input.month, status: input.status, coverage: { ...activeCoverage(input.month, input.activeFrom, input.activeTo), periodFrom: input.periodFrom, periodTo: input.periodTo }, metrics: metricsFromCast(input.cast), diagnosis: input.cast && input.diagnosisIncluded ? { primaryType: input.cast.diagnosis.primaryType, primaryLabel: input.cast.diagnosis.label, confidence: input.cast.confidence.overall.level, recalculatedWithCurrentRules: true, isPartialPeriod: input.status === "PARTIAL" } : null, action: null, warnings: input.status === "PARTIAL" ? [{ code: "PARTIAL_MONTH", label: "対象月は途中のため暫定値です" }] : [], previous: {} as CastMonthlyTrendPoint["previous"], rolling3: {} as CastMonthlyTrendPoint["rolling3"], rolling6: {} as CastMonthlyTrendPoint["rolling6"], direction: {} as CastMonthlyTrendPoint["direction"], extrema: {} as CastMonthlyTrendPoint["extrema"], records: {} as CastMonthlyTrendPoint["records"] });
