import { PageHeader } from "@/components/page-header";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { upsertMonthlyGoalAction } from "@/app/actions/goals";

const fields = [["salesTarget", "売上目標"], ["contractsTarget", "成約数目標"], ["averageActiveCastsTarget", "平均稼働キャスト目標"], ["nominationRateTarget", "本指名率目標（%）"], ["castPayoutTarget", "女子報酬目標"], ["averageUnitPriceTarget", "平均単価目標"], ["workingHoursTarget", "出勤時間目標"], ["townPvTarget", "Town PV目標"], ["townUuTarget", "Town UU目標"], ["townTelTarget", "Town TEL目標"], ["heavenPageAccessTarget", "Heavenアクセス目標"]] as const;

export default async function GoalsPage() {
  const user = await requireUser();
  const month = new Date(Date.UTC(new Date().getUTCFullYear(), new Date().getUTCMonth(), 1));
  const [stores, goals, histories] = await Promise.all([prisma.store.findMany({ where: { code: { in: ["KASUKABE", "KOSHIGAYA", "NODA"] } }, orderBy: { displayOrder: "asc" } }), prisma.monthlyGoal.findMany({ where: { targetMonth: month }, include: { store: true }, orderBy: { scopeKey: "asc" } }), prisma.monthlyGoalChangeHistory.findMany({ orderBy: { changedAt: "desc" }, take: 20, include: { changedBy: { select: { displayName: true } } } })]);
  const overall = goals.find((g) => g.scopeType === "OVERALL");
  return <><PageHeader eyebrow="GOAL MANAGEMENT" title="月次目標管理" description={`全体・店舗ごとの目標を設定し、ホームの達成率と着地予測に反映します。現在月：${month.toISOString().slice(0, 7)}`}/><div className="panel mb-6 p-5"><h2 className="font-semibold text-slate-900">現在月の設定状況</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-emerald-50 p-3 text-sm">全体：{overall ? "設定済み" : "未設定"}</div>{stores.map((s) => <div className="rounded-xl bg-slate-50 p-3 text-sm" key={s.id}>{s.shortName}：{goals.some((g) => g.storeId === s.id) ? "設定済み" : "未設定"}</div>)}</div></div>{user.role === "ADMIN" && <form action={upsertMonthlyGoalAction} className="panel grid gap-4 p-6 md:grid-cols-2"><h2 className="md:col-span-2 font-semibold text-slate-900">目標を保存</h2><label className="form-label">対象月<input className="form-input mt-1 w-full" name="targetMonth" type="month" defaultValue={month.toISOString().slice(0, 7)} required/></label><label className="form-label">対象<select className="form-input mt-1 w-full" name="scopeType" defaultValue="OVERALL"><option value="OVERALL">全体</option><option value="STORE">店舗</option></select></label><label className="form-label">店舗（店舗目標のみ）<select className="form-input mt-1 w-full" name="storeId"><option value="">全体</option>{stores.map((s) => <option value={s.id} key={s.id}>{s.shortName}</option>)}</select></label>{fields.map(([name, label]) => <label className="form-label" key={name}>{label}<input className="form-input mt-1 w-full" name={name} inputMode="decimal" placeholder="未設定"/></label>)}<label className="form-label md:col-span-2">変更理由<input className="form-input mt-1 w-full" name="reason" placeholder="例：月次会議で合意"/></label><label className="form-label md:col-span-2">メモ<textarea className="form-input mt-1 min-h-20 w-full" name="note"/></label><button className="primary-button md:col-span-2">目標を保存</button></form>}{user.role !== "ADMIN" && <p className="panel p-5 text-sm text-slate-500">目標の編集はADMINのみ可能です。</p>}<section className="panel mt-6 overflow-x-auto p-5"><h2 className="font-semibold text-slate-900">変更履歴</h2><table className="mt-3"><thead><tr><th>日時</th><th>管理者</th><th>理由</th></tr></thead><tbody>{histories.map((h) => <tr key={h.id}><td>{h.changedAt.toLocaleString("ja-JP")}</td><td>{h.changedBy.displayName}</td><td>{h.reason || "—"}</td></tr>)}{!histories.length && <tr><td colSpan={3}>履歴はありません。</td></tr>}</tbody></table></section></>;
}
