import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { CastMembershipSourceConfidence, CastMembershipStatus } from "@/generated/prisma/client";
import { requireUser } from "@/lib/auth";
import { formatDateOnly } from "@/lib/date";
import { prisma } from "@/lib/prisma";
import { loadMembershipReviewCasts, reviewClassificationLabel, reviewStatusLabel } from "@/lib/casts/membership-review-service";
import { closeMembershipAction, createMembershipAction, createReentryMembershipAction, resumeMembershipAction, setOnLeaveAction, updateMembershipAction } from "@/app/actions/memberships";

type Query = { castId?: string; q?: string; classification?: string; storeId?: string };

const dateText = (value: Date | null | undefined) => value ? formatDateOnly(value) : "";
const displayDate = (value: Date | null | undefined) => value ? formatDateOnly(value) : "—";

export default async function CastMembershipsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const user = await requireUser();
  const query = await searchParams;
  const [stores, casts] = await Promise.all([prisma.store.findMany({ where: { isActive: true }, orderBy: { displayOrder: "asc" }, select: { id: true, shortName: true } }), loadMembershipReviewCasts()]);
  const storeNames = new Map(stores.map((store) => [store.id, store.shortName]));
  const filtered = casts.filter((cast) => {
    const q = query.q?.trim().toLowerCase();
    return (!q || cast.displayName.toLowerCase().includes(q) || cast.id.includes(q))
      && (!query.classification || query.classification === "ALL" || cast.classification === query.classification)
      && (!query.storeId || cast.evidence.storeIds.includes(query.storeId));
  });
  const selected = casts.find((cast) => cast.id === query.castId) ?? null;
  const counts = { total: casts.length, configured: casts.filter((cast) => cast.memberships.length > 0).length, multi: casts.filter((cast) => cast.classification === "MULTI_STORE_EVIDENCE").length, storeUncertain: casts.filter((cast) => cast.classification === "STORE_UNCERTAIN").length, unreviewed: casts.filter((cast) => cast.memberships.length === 0).length };

  return <>
    <PageHeader title="Cast Membership Review" description="店舗別の在籍期間をFact・Alias・掲載根拠と照合し、人が確認して登録します。根拠の日付は自動でMembershipへ反映しません。" />
    <section className="panel mb-5 p-4"><div className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-5"><span>総Cast: <strong>{counts.total}</strong></span><span>Membership設定済み: <strong>{counts.configured}</strong></span><span>未対応: <strong>{counts.unreviewed}</strong></span><span>複数店舗根拠: <strong>{counts.multi}</strong></span><span>店舗要確認: <strong>{counts.storeUncertain}</strong></span></div></section>
    <form className="panel mb-5 grid gap-3 p-4 md:grid-cols-[1fr_190px_190px_auto] md:items-end">
      <label className="form-label">名前・ID<input className="form-input mt-1" name="q" defaultValue={query.q ?? ""} /></label>
      <label className="form-label">分類<select className="form-input mt-1" name="classification" defaultValue={query.classification ?? "ALL"}><option value="ALL">すべて</option>{["MULTI_STORE_EVIDENCE", "DATE_UNCERTAIN", "STORE_UNCERTAIN", "SAFE_AUTO", "SAFE_LEFT", "EXISTING_MEMBERSHIP"].map((value) => <option key={value} value={value}>{reviewClassificationLabel(value)}</option>)}</select></label>
      <label className="form-label">店舗<select className="form-input mt-1" name="storeId" defaultValue={query.storeId ?? ""}><option value="">すべて</option>{stores.map((store) => <option key={store.id} value={store.id}>{store.shortName}</option>)}</select></label>
      <button className="primary-button">絞り込む</button>
    </form>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(420px,0.9fr)]">
      <section className="panel overflow-hidden"><div className="table-wrap"><table><thead><tr><th>Cast</th><th>状態</th><th>主所属</th><th>Legacy期間</th><th>分類</th><th>根拠店舗</th><th>Membership</th></tr></thead><tbody>{filtered.map((cast) => <tr key={cast.id} className={cast.id === selected?.id ? "bg-emerald-50/50" : undefined}><td><Link className="font-semibold text-emerald-700 hover:underline" href={`/masters/casts/memberships?castId=${cast.id}`}>{cast.displayName}</Link><div className="font-mono text-[11px] text-slate-400">{cast.id.slice(0, 8)}…</div></td><td>{reviewStatusLabel(cast.status)}</td><td>{cast.primaryStoreId ? storeNames.get(cast.primaryStoreId) ?? "不明" : "未設定"}</td><td className="whitespace-nowrap text-xs">{displayDate(cast.startedOn)} ～ {displayDate(cast.endedOn)}</td><td><span className="status-badge bg-slate-100 text-slate-600">{reviewClassificationLabel(cast.classification)}</span></td><td className="text-xs">{cast.evidence.storeIds.map((id) => storeNames.get(id) ?? id.slice(0, 8)).join("・") || "—"}</td><td>{cast.memberships.length ? <span className="text-emerald-700">{cast.memberships.length}件</span> : <span className="text-slate-400">未設定</span>}</td></tr>)}</tbody></table></div>{filtered.length === 0 && <p className="empty-state">対象Castはありません。</p>}</section>
      <section className="panel p-5">{selected ? <ReviewDetail cast={selected} stores={stores} storeNames={storeNames} canEdit={user.role === "ADMIN"} /> : <p className="text-sm text-slate-500">左のCastを選択すると、店舗別EvidenceとMembershipを確認できます。</p>}</section>
    </div>
  </>;
}

function ReviewDetail({ cast, stores, storeNames, canEdit }: { cast: Awaited<ReturnType<typeof loadMembershipReviewCasts>>[number]; stores: Array<{ id: string; shortName: string }>; storeNames: Map<string, string>; canEdit: boolean }) {
  return <div>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{cast.displayName}</h2><p className="mt-1 text-xs text-slate-500">{reviewClassificationLabel(cast.classification)} / {cast.reason}</p></div><span className="status-badge bg-slate-100 text-slate-600">{reviewStatusLabel(cast.status)}</span></div>
    <dl className="mt-4 grid grid-cols-[110px_1fr] gap-2 text-sm"><dt className="text-slate-500">主所属</dt><dd>{cast.primaryStoreId ? storeNames.get(cast.primaryStoreId) ?? "不明" : "未設定"}</dd><dt className="text-slate-500">Legacy開始</dt><dd>{displayDate(cast.startedOn)}</dd><dt className="text-slate-500">Legacy終了</dt><dd>{displayDate(cast.endedOn)}</dd></dl>
    <h3 className="mt-6 font-semibold">店舗別Evidence</h3><p className="mt-1 text-xs text-slate-500">表示期間は確認根拠です。Membershipの日付には自動適用されません。</p>
    <div className="mt-3 space-y-3">{stores.map((store) => { const rows = cast.evidenceRows.filter((row) => row.storeId === store.id); return <div key={store.id} className="rounded-lg border border-slate-200 p-3"><div className="font-medium">{store.shortName}</div>{rows.length ? <div className="mt-2 space-y-1 text-xs">{rows.map((row, index) => <div key={`${row.sourceKind}-${index}`} className="flex flex-wrap justify-between gap-2"><span>{row.sourceKind}{row.mediaType ? ` / ${row.mediaType}` : ""}{row.isListed === undefined ? "" : row.isListed ? " / 掲載中" : " / 非掲載"}</span><span>{displayDate(row.from)} ～ {displayDate(row.to)} / {row.count}件</span></div>)}</div> : <p className="mt-1 text-xs text-slate-400">根拠なし</p>}</div>; })}</div>
    <h3 className="mt-6 font-semibold">Membership</h3>{cast.memberships.length ? <div className="mt-3 space-y-3">{cast.memberships.map((membership) => <MembershipCard key={membership.id} castId={cast.id} membership={membership} storeName={storeNames.get(membership.storeId) ?? "不明"} stores={stores} canEdit={canEdit} />)}</div> : <p className="mt-2 text-sm text-slate-500">未設定です。</p>}
    {canEdit && <CreateMembershipForm cast={cast} stores={stores} />}
    {!canEdit && <p className="mt-5 rounded-lg bg-slate-50 p-3 text-xs text-slate-500">Viewerは閲覧のみ可能です。Membershipの変更はAdminが行います。</p>}
  </div>;
}

function MembershipCard({ castId, membership, storeName, stores, canEdit }: { castId: string; membership: Awaited<ReturnType<typeof loadMembershipReviewCasts>>[number]["memberships"][number]; storeName: string; stores: Array<{ id: string; shortName: string }>; canEdit: boolean }) {
  return <div className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{storeName}</strong><span className="status-badge bg-slate-100 text-slate-600">{membership.status}</span></div><div className="mt-2 text-sm">{displayDate(membership.joinedAt)} ～ {displayDate(membership.leftAt)}</div><div className="mt-1 text-xs text-slate-500">source: {membership.source ?? "—"} / confidence: {membership.sourceConfidence ?? "—"} / 更新: {membership.updatedAt.toLocaleString("ja-JP")}</div>{canEdit && <><form action={updateMembershipAction} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="hidden" name="id" value={membership.id} /><input type="hidden" name="castId" value={castId} /><label className="form-label">入店日<input className="form-input mt-1" type="date" name="joinedAt" defaultValue={dateText(membership.joinedAt)} /></label><label className="form-label">退店日<input className="form-input mt-1" type="date" name="leftAt" defaultValue={dateText(membership.leftAt)} /></label><label className="form-label">状態<select className="form-input mt-1" name="status" defaultValue={membership.status}>{Object.values(CastMembershipStatus).map((value) => <option key={value}>{value}</option>)}</select></label><label className="form-label">店舗<select className="form-input mt-1" name="storeId" defaultValue={membership.storeId}>{stores.map((store) => <option key={store.id} value={store.id}>{store.shortName}</option>)}</select></label><label className="form-label">Source<input className="form-input mt-1" name="source" defaultValue={membership.source ?? ""} /></label><label className="form-label">信頼度<select className="form-input mt-1" name="sourceConfidence" defaultValue={membership.sourceConfidence ?? ""}><option value="">未設定</option>{Object.values(CastMembershipSourceConfidence).map((value) => <option key={value}>{value}</option>)}</select></label><label className="form-label sm:col-span-2">メモ<textarea className="form-input mt-1" name="note" defaultValue={membership.note ?? ""} rows={2} /></label><button className="primary-button sm:col-span-2">更新</button></form><div className="mt-2 flex flex-wrap gap-2">{membership.status === CastMembershipStatus.ACTIVE && <form action={setOnLeaveAction}><input type="hidden" name="id" value={membership.id} /><button className="secondary-button">休業にする</button></form>}{membership.status === CastMembershipStatus.ON_LEAVE && <form action={resumeMembershipAction}><input type="hidden" name="id" value={membership.id} /><button className="secondary-button">復帰する</button></form>}{membership.status !== CastMembershipStatus.LEFT && <form action={closeMembershipAction} className="flex gap-2"><input type="hidden" name="id" value={membership.id} /><input className="compact-input" type="date" name="leftAt" required /><button className="secondary-button">退店</button></form>}</div></>}</div>;
}

function CreateMembershipForm({ cast, stores }: { cast: Awaited<ReturnType<typeof loadMembershipReviewCasts>>[number]; stores: Array<{ id: string; shortName: string }> }) {
  return <div className="mt-6 rounded-lg bg-slate-50 p-4"><h3 className="font-semibold">Membershipを追加</h3><p className="mt-1 text-xs text-slate-500">Legacy日付は候補として表示しています。保存前に必ず確認・編集してください。</p><form action={createMembershipAction} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="hidden" name="castId" value={cast.id} /><label className="form-label">店舗<select className="form-input mt-1" name="storeId" required><option value="">選択</option>{stores.map((store) => <option key={store.id} value={store.id}>{store.shortName}</option>)}</select></label><label className="form-label">状態<select className="form-input mt-1" name="status" defaultValue={CastMembershipStatus.ACTIVE}>{Object.values(CastMembershipStatus).map((value) => <option key={value}>{value}</option>)}</select></label><label className="form-label">入店日候補（編集可）<input className="form-input mt-1" type="date" name="joinedAt" defaultValue={dateText(cast.startedOn)} /></label><label className="form-label">退店日<input className="form-input mt-1" type="date" name="leftAt" defaultValue="" /></label><label className="form-label">信頼度<select className="form-input mt-1" name="sourceConfidence"><option value="">未設定</option>{Object.values(CastMembershipSourceConfidence).map((value) => <option key={value}>{value}</option>)}</select></label><label className="form-label">Source<input className="form-input mt-1" name="source" defaultValue="MANUAL_REVIEW" /></label><label className="form-label sm:col-span-2">メモ<textarea className="form-input mt-1" name="note" rows={2} /></label><button className="primary-button sm:col-span-2">登録</button></form><form action={createReentryMembershipAction} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="hidden" name="castId" value={cast.id} /><input type="hidden" name="status" value={CastMembershipStatus.ACTIVE} /><label className="form-label">再入店店舗<select className="form-input mt-1" name="storeId" required><option value="">選択</option>{stores.map((store) => <option key={store.id} value={store.id}>{store.shortName}</option>)}</select></label><label className="form-label">再入店日<input className="form-input mt-1" type="date" name="joinedAt" required /></label><button className="secondary-button sm:col-span-2">再入店を追加</button></form></div>;
}
