import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { aggregateCti, resolveDateRange } from "@/lib/analytics/cti";
import { aggregateHeavenMetric, heavenMetricLabel } from "@/lib/analytics/heaven";
import { aggregateTown } from "@/lib/analytics/town";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const n = (value: number | null, digits = 0) => value === null ? "—" : value.toLocaleString("ja-JP", { maximumFractionDigits: digits });
const yen = (value: number | null) => value === null ? "—" : `¥${n(value)}`;
const pct = (value: number | null) => value === null ? "—" : `${n(value * 100, 2)}%`;
const HEAVEN_KEYS = ["page_access", "diary_posts", "my_girl", "mitene_sent", "okini_talk_sent", "attendance_notice", "diary_notice"];
const COLUMNS = ["basic", "cti", "town", "heaven", "derived"] as const;

type Query = { from?: string; to?: string; scope?: string; q?: string; listed?: string; sort?: string; columns?: string | string[] };
function selectedColumns(value: Query["columns"]) { const values = Array.isArray(value) ? value : value ? value.split(",") : []; return new Set(values.length ? values : COLUMNS); }

export default async function CastOverviewPage({ searchParams }: { searchParams: Promise<Query> }) {
  await requireUser(); const query = await searchParams; const range = resolveDateRange(query.from, query.to); const scope = query.scope === "KASUKABE" || query.scope === "KOSHIGAYA" || query.scope === "NODA" ? query.scope : "ALL"; const columns = selectedColumns(query.columns);
  const stores = await prisma.store.findMany({ where: { code: { in: ["KASUKABE", "KOSHIGAYA", "NODA"] } } }); const storeByCode = new Map(stores.map((s) => [s.code, s]));
  const allowedStores = scope === "ALL" ? stores : [storeByCode.get(scope)].filter(Boolean);
  const storeIds = allowedStores.map((s) => s!.id);
  const [cti, town, heaven] = await Promise.all([
    prisma.ctiCastDaily.findMany({ where: { businessDate: { gte: range.from, lte: range.to }, storeId: { in: storeIds }, cast: { mergedIntoCastId: null } }, include: { cast: { include: { primaryStore: true } }, store: true } }),
    scope === "NODA" ? Promise.resolve([]) : prisma.townCastDaily.findMany({ where: { date: { gte: range.from, lte: range.to }, storeId: { in: storeIds.filter((id) => id !== storeByCode.get("NODA")?.id) }, cast: { mergedIntoCastId: null } }, include: { cast: { include: { primaryStore: true } }, store: true } }),
    scope === "NODA" ? Promise.resolve([]) : prisma.heavenCastDaily.findMany({ where: { businessDate: { gte: range.from, lte: range.to }, storeId: { in: storeIds.filter((id) => id === storeByCode.get("KASUKABE")?.id) }, castId: { not: null }, cast: { mergedIntoCastId: null } }, include: { cast: { include: { primaryStore: true } }, store: true } }),
  ]);
  const castIds = new Set<string>(); for (const row of cti) castIds.add(row.castId); for (const row of town) castIds.add(row.castId); for (const row of heaven) if (row.castId) castIds.add(row.castId);
  const listings = await prisma.mediaListing.findMany({ where: { castId: { in: [...castIds] }, storeId: { in: storeIds }, mediaType: { in: ["TOWN", "HEAVEN"] } } });
  const q = (query.q ?? "").trim().toLowerCase();
  const rows = [...castIds].map((castId) => {
    const ctiRows = cti.filter((r) => r.castId === castId); const townRows = town.filter((r) => r.castId === castId); const heavenRows = heaven.filter((r) => r.castId === castId);
    const cast = ctiRows[0]?.cast ?? townRows[0]?.cast ?? heavenRows[0]?.cast; const c = ctiRows.length ? aggregateCti(ctiRows) : null; const t = townRows.length ? aggregateTown(townRows) : null; const h = new Map(HEAVEN_KEYS.map((key) => [key, heavenRows.some((r) => r.metricKey === key) ? aggregateHeavenMetric(heavenRows.filter((r) => r.metricKey === key)) : null]));
    const townByStore = new Map<string, ReturnType<typeof aggregateTown>>(); for (const store of allowedStores) { const records = townRows.filter((r) => r.storeId === store!.id); if (records.length) townByStore.set(store!.shortName, aggregateTown(records)); }
    const listed = listings.some((l) => l.castId === castId && l.isListed); return { cast, c, t, h, townByStore, listed, hasCti: ctiRows.length > 0, hasTown: townRows.length > 0, hasHeaven: heavenRows.length > 0 };
  }).filter((row) => row.cast && (!q || row.cast.displayName.toLowerCase().includes(q)) && (query.listed === "listed" ? row.listed : query.listed === "unlisted" ? !row.listed : true)).sort((a, b) => query.sort === "sales" ? (b.c?.salesAmount ?? -1) - (a.c?.salesAmount ?? -1) : a.cast!.displayName.localeCompare(b.cast!.displayName, "ja"));
  const input = (name: string, value: string, type = "text") => <input className="form-input mt-1" name={name} type={type} defaultValue={value} />;
  return <><PageHeader eyebrow="CROSS-MEDIA CAST" title="キャスト統合分析" description="CTI・Town・Heavenを同一期間で横断表示します。TownとHeavenのPVは顧客単位で対応しないため、参考合計として扱います。" />
    <form className="panel mb-6 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-6"><label className="form-label">開始日{input("from", range.fromText, "date")}</label><label className="form-label">終了日{input("to", range.toText, "date")}</label><label className="form-label">店舗<select className="form-input mt-1" name="scope" defaultValue={scope}><option value="ALL">全体</option><option value="KASUKABE">春日部</option><option value="KOSHIGAYA">越谷</option><option value="NODA">野田（CTI補助）</option></select></label><label className="form-label">キャスト検索{input("q", query.q ?? "")}</label><label className="form-label">掲載状態<select className="form-input mt-1" name="listed" defaultValue={query.listed ?? "all"}><option value="all">すべて</option><option value="listed">掲載中</option><option value="unlisted">未掲載</option></select></label><label className="form-label">並び順<select className="form-input mt-1" name="sort" defaultValue={query.sort ?? "name"}><option value="name">名前順</option><option value="sales">料金降順</option></select></label><div className="sm:col-span-2 xl:col-span-6"><p className="form-label">表示列</p><div className="mt-2 flex flex-wrap gap-4 text-sm">{COLUMNS.map((key) => <label key={key} className="flex items-center gap-2"><input type="checkbox" name="columns" value={key} defaultChecked={columns.has(key)} />{key === "basic" ? "基本情報" : key === "cti" ? "CTI" : key === "town" ? "Town" : key === "heaven" ? "Heaven" : "統合指標"}</label>)}</div></div><button className="primary-button sm:col-span-2 xl:col-span-6">表示</button></form>
    <p className="mb-3 text-sm text-slate-500">対象 {rows.length}名（CTIのみ {rows.filter((r) => r.hasCti && !r.hasTown && !r.hasHeaven).length} / Townのみ {rows.filter((r) => !r.hasCti && r.hasTown && !r.hasHeaven).length} / Heavenのみ {rows.filter((r) => !r.hasCti && !r.hasTown && r.hasHeaven).length} / 3媒体 {rows.filter((r) => r.hasCti && r.hasTown && r.hasHeaven).length}）</p>
    <section className="panel overflow-hidden"><div className="table-wrap"><table><thead><tr>{columns.has("basic") && <><th>キャスト</th><th>主所属</th><th>掲載</th><th>出勤日数</th><th>出勤時間</th></>}{columns.has("cti") && <><th>料金</th><th>女子報酬</th><th>成約</th><th>予約</th><th>本指名</th><th>本指名率</th><th>平均報酬</th><th>平均時給</th></>}{columns.has("town") && <><th>Town PV</th><th>Town UU</th><th>Town TEL</th><th>TEL率</th><th>店舗別</th></>}{columns.has("heaven") && HEAVEN_KEYS.map((key) => <th key={key}>{heavenMetricLabel(key)}</th>)}{columns.has("derived") && <><th>PV参考合計</th><th>成約/Town UU</th><th>成約/Heaven PV</th><th>報酬/出勤時間</th><th>集客に対する成約効率</th></>}{<th>詳細</th>}</tr></thead><tbody>{rows.map((row) => { const c = row.c; const t = row.t; const page = row.h.get("page_access")?.periodValue ?? null; const townPv = t?.pv ?? null; const traffic = townPv === null && page === null ? null : (townPv ?? 0) + (page ?? 0); return <tr key={row.cast!.id}>{columns.has("basic") && <><td className="font-medium text-slate-900">{row.cast!.displayName}</td><td>{row.cast!.primaryStore?.shortName ?? "—"}</td><td>{row.listed ? "掲載" : "未掲載"}</td><td>{c ? n(c.attendanceDays) : "—"}</td><td>{c ? `${n(c.attendanceMinutes / 60, 1)}h` : "—"}</td></>}{columns.has("cti") && <><td>{yen(c?.salesAmount ?? null)}</td><td>{yen(c?.castRewardAmount ?? null)}</td><td>{n(c?.contractCount ?? null)}</td><td>{n(c?.reservationCount ?? null)}</td><td>{n(c?.regularNominationCount ?? null)}</td><td>{pct(c ? c.regularNominationRate : null)}</td><td>{yen(c?.averageRewardPerDay ?? null)}</td><td>{yen(c?.averageRewardPerHour ?? null)}</td></>}{columns.has("town") && <><td>{n(t?.pv ?? null)}</td><td>{n(t?.uu ?? null)}</td><td>{n(t?.telTapUu ?? null)}</td><td>{pct(t?.conversionRate ?? null)}</td><td>{[...row.townByStore.entries()].map(([name, m]) => `${name}: ${n(m.pv)}/${n(m.uu)}/${n(m.telTapUu)}`).join(" / ") || "—"}</td></>}{columns.has("heaven") && HEAVEN_KEYS.map((key) => { const a = row.h.get(key); return <td key={key}>{a ? a.valueKind === "SNAPSHOT" ? <>{n(a.lastValue)}<span className="block text-xs text-slate-500">増減 {n(a.change)}</span></> : n(a.periodValue) : "—"}</td>; })}{columns.has("derived") && <><td>{traffic === null ? "—" : n(traffic)}</td><td>{pct(c && t ? (t.uu === 0 ? null : c.contractCount / t.uu) : null)}</td><td>{pct(c && page ? (page === 0 ? null : c.contractCount / page) : null)}</td><td>{c ? yen(c.averageRewardPerHour) : "—"}</td><td>{c && (t || page !== null) ? pct(c.contractCount / ((t?.uu ?? 0) + (page ?? 0))) : "—"}</td></>}{<td><Link className="text-emerald-700" href={`/analytics/heaven/casts/${row.cast!.id}?from=${range.fromText}&to=${range.toText}`}>詳細</Link></td>}</tr>; })}</tbody></table>{rows.length === 0 && <p className="empty-state">指定条件のキャスト実績はありません。</p>}</div></section></>;
}
