import { prisma } from "@/lib/prisma";

type Availability = "VALUE" | "ZERO" | "MISSING" | "PARTIAL" | "UNAVAILABLE" | "UNCOMPUTABLE";
export type Metric = { value: number | null; availability: Availability; validDayCount?: number; missingDayCount?: number };
type StoreCode = "ALL" | "KASUKABE" | "KOSHIGAYA" | "NODA";
const stores: Exclude<StoreCode, "ALL">[] = ["KASUKABE", "KOSHIGAYA", "NODA"];
const confirmed = { status: { in: ["COMPLETED", "COMPLETED_WITH_WARNINGS"] as ("COMPLETED" | "COMPLETED_WITH_WARNINGS")[] } };
const metric = (value: number | null, unavailable = false): Metric => unavailable ? { value: null, availability: "UNAVAILABLE" } : value === null ? { value: null, availability: "MISSING" } : { value, availability: value === 0 ? "ZERO" : "VALUE" };
const sum = (values: Array<number | null | undefined>) => { const valid = values.filter((value): value is number => value !== null && value !== undefined && Number.isFinite(value)); return valid.length ? valid.reduce((total, value) => total + value, 0) : null; };
const ratio = (numerator: number | null, denominator: number | null): Metric => numerator === null || denominator === null ? metric(null) : denominator === 0 ? { value: null, availability: "UNCOMPUTABLE" } : metric(numerator / denominator);
const dates = (from: string, to: string) => { const result: string[] = []; const cursor = new Date(`${from}T00:00:00Z`); const end = new Date(`${to}T00:00:00Z`); while (cursor <= end) { result.push(cursor.toISOString().slice(0, 10)); cursor.setUTCDate(cursor.getUTCDate() + 1); } return result; };
const monday = (value: string) => { const date = new Date(`${value}T00:00:00Z`); const day = date.getUTCDay(); date.setUTCDate(date.getUTCDate() - (day === 0 ? 6 : day - 1)); return date.toISOString().slice(0, 10); };
const addDays = (value: string, count: number) => { const date = new Date(`${value}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + count); return date.toISOString().slice(0, 10); };
export const weekRange = (value: string) => { const weekStart = monday(value); return { weekStart, weekEnd: addDays(weekStart, 6) }; };
const weekday = (value: string) => ["日", "月", "火", "水", "木", "金", "土"][new Date(`${value}T00:00:00Z`).getUTCDay()];

function aggregate(rows: Array<Record<string, number | null>>, key: string) { return metric(sum(rows.map((row) => row[key]))); }
function aggregateRows(rows: Array<Record<string, number | null>>) {
  const sales = aggregate(rows, "salesAmount"); const contracts = aggregate(rows, "contractCount"); const minutes = aggregate(rows, "attendanceMinutes");
  return { sales, contracts, castReward: aggregate(rows, "castRewardAmount"), profit: aggregate(rows, "ctiProfitAmount"), reservations: aggregate(rows, "reservationCount"), services: aggregate(rows, "serviceCount"), nominations: aggregate(rows, "regularNominationCount"), photoNominations: aggregate(rows, "photoNominationCount"), free: aggregate(rows, "freeCount"), newCount: aggregate(rows, "newCount"), repeat: aggregate(rows, "repeatCount"), cancellations: aggregate(rows, "cancellationCount"), paidOptions: aggregate(rows, "paidOptionCount"), attendancePeople: aggregate(rows, "attendanceCount"), attendanceMinutes: minutes, attendanceHours: minutes.value === null ? metric(null) : metric(minutes.value / 60), averageHourlyReward: ratio(aggregate(rows, "castRewardAmount").value, minutes.value === null ? null : minutes.value / 60), nominationRate: ratio(aggregate(rows, "regularNominationCount").value, contracts.value) };
}

function average(total: Metric, validDays: number) { return total.value === null || validDays === 0 ? metric(null) : metric(total.value / validDays); }

export function heavenDiaryMetric(rows: Array<{ businessDate: Date; rawValue: unknown; rawValueStatus: string }>) {
  const byDay = new Map<string, number | null>();
  for (const row of rows) {
    const date = row.businessDate.toISOString().slice(0, 10);
    const value = row.rawValueStatus === "VALUE" && row.rawValue !== null ? Number(row.rawValue) : null;
    if (!Number.isFinite(value ?? NaN)) {
      if (!byDay.has(date)) byDay.set(date, null);
      continue;
    }
    byDay.set(date, (byDay.get(date) ?? 0) + value!);
  }
  const values = [...byDay.values()];
  const valid = values.filter((value): value is number => value !== null);
  const missingDayCount = values.length - valid.length;
  const total = valid.length ? valid.reduce((sumValue, value) => sumValue + value, 0) : null;
  const availability: Availability = !values.length || !valid.length ? "MISSING" : missingDayCount ? "PARTIAL" : total === 0 ? "ZERO" : "VALUE";
  return { value: total, availability, validDayCount: valid.length, missingDayCount } satisfies Metric;
}

export async function getStoreWeekDetail(input: { week: string; storeCode: StoreCode }, includeComparisons = true) {
  const { weekStart, weekEnd } = weekRange(input.week); const calendarDates = dates(weekStart, weekEnd); const targetCodes = input.storeCode === "ALL" ? stores : [input.storeCode];
  const storeRows = await prisma.store.findMany({ where: { code: { in: stores }, isActive: true }, select: { id: true, code: true, shortName: true } });
  const selectedStores = storeRows.filter((store) => targetCodes.includes(store.code as Exclude<StoreCode, "ALL">)); const selectedIds = selectedStores.map((store) => store.id);
  const [cti, town, heaven] = await Promise.all([
    prisma.ctiCastDaily.findMany({ where: { businessDate: { gte: new Date(`${weekStart}T00:00:00Z`), lte: new Date(`${weekEnd}T23:59:59Z`) }, storeId: { in: selectedIds }, cast: { mergedIntoCastId: null }, importBatch: confirmed }, select: { businessDate: true, storeId: true, castId: true, attendanceCount: true, attendanceMinutes: true, reservationCount: true, cancellationCount: true, serviceCount: true, regularNominationCount: true, photoNominationCount: true, freeCount: true, contractCount: true, newCount: true, repeatCount: true, salesAmount: true, castRewardAmount: true, ctiProfitAmount: true, paidOptionCount: true, cast: { select: { displayName: true } } } }),
    prisma.townStoreDaily.findMany({ where: { date: { gte: new Date(`${weekStart}T00:00:00Z`), lte: new Date(`${weekEnd}T23:59:59Z`) }, storeId: { in: selectedIds }, importBatch: confirmed }, select: { date: true, storeId: true, pv: true, uu: true } }),
    prisma.heavenCastDaily.findMany({ where: { businessDate: { gte: new Date(`${weekStart}T00:00:00Z`), lte: new Date(`${weekEnd}T23:59:59Z`) }, storeId: { in: selectedIds }, metricKey: { in: ["page_access", "diary_posts"] }, importBatch: confirmed, cast: { mergedIntoCastId: null } }, select: { businessDate: true, storeId: true, castId: true, sourceCastName: true, metricKey: true, rawValue: true, rawValueStatus: true, cast: { select: { displayName: true } } } }),
  ]);
  const dayRows = calendarDates.map((date) => { const ctiRows = cti.filter((row) => row.businessDate.toISOString().slice(0, 10) === date); const townRows = town.filter((row) => row.date.toISOString().slice(0, 10) === date); const heavenRows = heaven.filter((row) => row.businessDate.toISOString().slice(0, 10) === date); const metrics = aggregateRows(ctiRows as unknown as Array<Record<string, number | null>>); const townPv = metric(sum(townRows.map((row) => row.pv))); const townUu = metric(sum(townRows.map((row) => row.uu))); const validAccessRows = heavenRows.filter((row) => row.metricKey === "page_access" && row.rawValueStatus === "VALUE" && row.rawValue !== null); const heavenAccess = metric(sum(validAccessRows.map((row) => Number(row.rawValue)))); return { date, weekday: weekday(date), rows: ctiRows, metrics, townPv, townUu, heavenAccess, ctiValid: ctiRows.length > 0, townValid: townRows.length > 0, heavenValid: validAccessRows.length > 0 }; });
  const selectedMetrics = aggregateRows(cti as unknown as Array<Record<string, number | null>>); const townPv = metric(sum(town.map((row) => row.pv))); const townUu = metric(sum(town.map((row) => row.uu))); const heavenAccess = metric(sum(heaven.filter((row) => row.metricKey === "page_access" && row.rawValueStatus === "VALUE" && row.rawValue !== null).map((row) => Number(row.rawValue))));
  const ctiValidDayCount = dayRows.filter((day) => day.ctiValid).length; const townValidDayCount = dayRows.filter((day) => day.townValid).length; const heavenValidDayCount = dayRows.filter((day) => day.heavenValid).length;
  const uniqueAttendance = new Set(cti.filter((row) => row.attendanceCount > 0).map((row) => `${row.castId}:${row.businessDate.toISOString().slice(0, 10)}`));
  const summary = { sales: selectedMetrics.sales, contracts: selectedMetrics.contracts, femaleReward: selectedMetrics.castReward, nominationCount: selectedMetrics.nominations, nominationRate: selectedMetrics.nominationRate, attendanceCount: selectedMetrics.attendancePeople, uniqueAttendanceCount: metric(new Set(cti.filter((row) => row.attendanceCount > 0).map((row) => row.castId)).size), workingHours: selectedMetrics.attendanceHours, townPv, townUu, heavenAccess };
  const contractBreakdown = { nominationCount: selectedMetrics.nominations, photoNominationCount: selectedMetrics.photoNominations, freeCount: selectedMetrics.free, newCount: selectedMetrics.newCount, repeatCount: selectedMetrics.repeat, cancelCount: selectedMetrics.cancellations };
  const breakdownValues = [contractBreakdown.nominationCount.value, contractBreakdown.photoNominationCount.value, contractBreakdown.freeCount.value]; const availableBreakdown = breakdownValues.filter((item): item is number => item !== null); const breakdownTotal = availableBreakdown.length === 3 ? availableBreakdown.reduce((a, b) => a + b, 0) : null; const breakdownAvailability: Availability = availableBreakdown.length === 0 ? "MISSING" : availableBreakdown.length < 3 ? "PARTIAL" : "VALUE";
  const heavenDiaryByCast = new Map<string, typeof heaven>(); for (const row of heaven) { if (row.metricKey === "diary_posts" && row.castId) { const values = heavenDiaryByCast.get(row.castId) ?? []; values.push(row); heavenDiaryByCast.set(row.castId, values); } }
  const castsMap = new Map<string, { name: string; stores: Set<string>; rows: Array<Record<string, number | null>>; days: Set<string> }>(); for (const row of cti) { const current = castsMap.get(row.castId) ?? { name: row.cast.displayName, stores: new Set<string>(), rows: [], days: new Set<string>() }; current.stores.add(selectedStores.find((store) => store.id === row.storeId)?.code ?? ""); current.rows.push(row as unknown as Record<string, number | null>); if (row.attendanceCount > 0) current.days.add(row.businessDate.toISOString().slice(0, 10)); castsMap.set(row.castId, current); }
  for (const [castId, rows] of heavenDiaryByCast) { const first = rows[0]; const current = castsMap.get(castId) ?? { name: first.cast?.displayName ?? first.sourceCastName, stores: new Set<string>(), rows: [], days: new Set<string>() }; current.stores.add(selectedStores.find((store) => store.id === first.storeId)?.code ?? "KASUKABE"); castsMap.set(castId, current); }
  const casts = [...castsMap.entries()].map(([castId, cast]) => { const m = aggregateRows(cast.rows); const photoDiaryCount = heavenDiaryMetric(heavenDiaryByCast.get(castId) ?? []); return { castId, name: cast.name, stores: [...cast.stores], reward: m.castReward, contracts: m.contracts, nominations: m.nominations, photoNominations: m.photoNominations, free: m.free, newCount: m.newCount, repeat: m.repeat, paidOptions: m.paidOptions, photoDiaryCount, diaryPosts: photoDiaryCount, cancellations: m.cancellations, attendanceDays: metric(cast.days.size), attendanceHours: m.attendanceHours, nominationRate: m.nominationRate, averageHourlyReward: m.averageHourlyReward, contractsPerDay: ratio(m.contracts.value, cast.days.size), contractsPerHour: ratio(m.contracts.value, m.attendanceHours.value) }; }).sort((a, b) => (b.reward.value ?? -1) - (a.reward.value ?? -1) || (b.contracts.value ?? -1) - (a.contracts.value ?? -1) || (b.nominations.value ?? -1) - (a.nominations.value ?? -1) || (b.attendanceDays.value ?? -1) - (a.attendanceDays.value ?? -1) || (b.attendanceHours.value ?? -1) - (a.attendanceHours.value ?? -1) || a.name.localeCompare(b.name, "ja"));
  const totalReward = summary.femaleReward.value ?? 0; const totalContracts = summary.contracts.value ?? 0; const storeBreakdown = selectedStores.map((store) => { const rows = cti.filter((row) => row.storeId === store.id); const m = aggregateRows(rows as unknown as Array<Record<string, number | null>>); const unique = new Set(rows.filter((row) => row.attendanceCount > 0).map((row) => `${row.castId}:${row.businessDate.toISOString().slice(0, 10)}`)); return { storeCode: store.code, storeName: store.shortName, sales: m.sales, contracts: m.contracts, femaleReward: m.castReward, nominations: m.nominations, attendanceCount: m.attendancePeople, uniqueAttendanceCount: metric(new Set(rows.filter((row) => row.attendanceCount > 0).map((row) => row.castId)).size), attendanceDays: metric(unique.size), attendanceHours: m.attendanceHours, salesShare: ratio(m.sales.value, summary.sales.value), contractsShare: ratio(m.contracts.value, summary.contracts.value) }; });
  const dailyBreakdown = dayRows.map((day) => ({ date: day.date, weekday: day.weekday, sales: day.metrics.sales, contracts: day.metrics.contracts, nominations: day.metrics.nominations, attendanceCount: day.metrics.attendancePeople, attendanceHours: day.metrics.attendanceHours, townPv: day.townPv, townUu: day.townUu, heavenAccess: day.heavenAccess, contractShare: ratio(day.metrics.contracts.value, summary.contracts.value), availability: { cti: day.ctiValid ? "VALUE" : "MISSING", town: day.townValid ? "VALUE" : "MISSING", heaven: day.heavenValid ? "VALUE" : "MISSING" } }));
  const today = new Date().toISOString().slice(0, 10); const isCompleteWeek = calendarDates.every((date) => date <= today) && ctiValidDayCount === 7;
  const castComposition = { activeCastCount: casts.length, attendanceCount: summary.attendanceCount, contractCastCount: casts.filter((cast) => (cast.contracts.value ?? 0) > 0).length, zeroContractCastCount: casts.filter((cast) => cast.contracts.value === 0).length, nominationCastCount: casts.filter((cast) => (cast.nominations.value ?? 0) > 0).length, threePlusContractCastCount: casts.filter((cast) => (cast.contracts.value ?? 0) >= 3).length, top3RewardShare: ratio(casts.slice(0, 3).reduce((total, cast) => total + (cast.reward.value ?? 0), 0), totalReward), top3ContractShare: ratio(casts.slice(0, 3).reduce((total, cast) => total + (cast.contracts.value ?? 0), 0), totalContracts), totalReward: summary.femaleReward, averageAttendanceDays: average(metric(casts.reduce((total, cast) => total + (cast.attendanceDays.value ?? 0), 0)), casts.length), averageAttendanceHours: average(metric(casts.reduce((total, cast) => total + (cast.attendanceHours.value ?? 0), 0)), casts.length) };
  const previousDetail = includeComparisons ? await getStoreWeekDetail({ week: addDays(weekStart, -7), storeCode: input.storeCode }, false) : null;
  const comparisonKeys: Array<[string, string, Metric, Metric]> = previousDetail ? [["sales", "売上", summary.sales, previousDetail.summary.sales], ["contracts", "成約", summary.contracts, previousDetail.summary.contracts], ["femaleReward", "女子報酬", summary.femaleReward, previousDetail.summary.femaleReward], ["workingHours", "出勤時間", summary.workingHours, previousDetail.summary.workingHours]] : [];
  const previousWeek = comparisonKeys.map(([metricKey, label, current, baseline]) => { const difference = current.value === null || baseline.value === null ? metric(null) : metric(current.value - baseline.value); return { metricKey, label, current, baseline, difference, differenceRate: ratio(difference.value, baseline.value), availability: difference.availability }; });
  return { weekStart, weekEnd, isCompleteWeek, scope: input.storeCode, validDayCounts: { calendar: 7, cti: ctiValidDayCount, townPv: townValidDayCount, townUu: townValidDayCount, heaven: heavenValidDayCount }, summary, averages: { salesPerValidDay: average(summary.sales, ctiValidDayCount), contractsPerValidDay: average(summary.contracts, ctiValidDayCount), rewardPerValidDay: average(summary.femaleReward, ctiValidDayCount), attendancePerValidDay: average(summary.attendanceCount, ctiValidDayCount), workingHoursPerValidDay: average(summary.workingHours, ctiValidDayCount), townPvPerValidDay: average(summary.townPv, townValidDayCount), townUuPerValidDay: average(summary.townUu, townValidDayCount), heavenPerValidDay: average(summary.heavenAccess, heavenValidDayCount) }, comparisons: { previousWeek, monthlyWeekAverage: [] }, dailyBreakdown, storeBreakdown, contractBreakdown: { ...contractBreakdown, availability: breakdownAvailability }, contractBreakdownConsistency: { isConsistent: breakdownTotal === null || summary.contracts.value === null ? null : breakdownTotal === summary.contracts.value, contracts: summary.contracts.value, breakdownTotal, difference: breakdownTotal === null || summary.contracts.value === null ? null : summary.contracts.value - breakdownTotal }, castComposition, casts, availability: { cti: ctiValidDayCount ? "VALUE" : "MISSING", town: townValidDayCount ? "VALUE" : "MISSING", heaven: heavenValidDayCount ? "VALUE" : "MISSING" }, _internal: { uniqueAttendance: uniqueAttendance.size } };
}
