import { describe, expect, it } from "vitest";
import { ImportDataType } from "@/generated/prisma/client";
import { parseAutoExecutionRoutes, resolveAutoPreviewDecision } from "./auto-execution-gate";

const mapping = (importDataType: ImportDataType, metricHint: string | null = null, overrides: Record<string, unknown> = {}) => ({ importDataType, metricHint, isActive: true, isFuture: false, ...overrides });

describe("I8 AUTO Preview gate", () => {
  it("keeps the global gate disabled by default", () => expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_STORE), false).reason).toBe("AUTO_EXECUTION_DISABLED"));
  it("allows only routes present in the per-route allowlist", () => { const shop = new Set(["HEAVEN_SHOP"] as const); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_STORE), true, shop).allowed).toBe(true); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_CAST, "PAGE_ACCESS"), true, shop).reason).toBe("AUTO_ROUTE_NOT_ENABLED"); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_CAST, "DIARY_POSTS"), true, shop).reason).toBe("AUTO_ROUTE_NOT_ENABLED"); });
  it("supports independent and multiple route enablement", () => { const access = new Set(["HEAVEN_GIRL_ACCESS"] as const); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_CAST, "PAGE_ACCESS"), true, access).allowed).toBe(true); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_STORE), true, access).allowed).toBe(false); const all = new Set(["HEAVEN_SHOP", "HEAVEN_GIRL_ACCESS", "HEAVEN_GIRL_DIARY"] as const); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_CAST, "DIARY_POSTS"), true, all).allowed).toBe(true); });
  it("blocks CTI/Town until target date can be resolved without operator input", () => { expect(resolveAutoPreviewDecision(mapping(ImportDataType.CTI_CAST_REPORT), true).reason).toBe("TARGET_DATE_REQUIRES_OPERATOR_INPUT"); expect(resolveAutoPreviewDecision(mapping(ImportDataType.TOWN_STORE), true).allowed).toBe(false); expect(resolveAutoPreviewDecision(mapping(ImportDataType.TOWN_CAST), true).allowed).toBe(false); });
  it("blocks inactive, future, unsupported and empty/unknown routes", () => { const empty = new Set<"HEAVEN_SHOP" | "HEAVEN_GIRL_ACCESS" | "HEAVEN_GIRL_DIARY">(); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_STORE, null, { isActive: false }), true, empty).allowed).toBe(false); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_STORE, null, { isFuture: true }), true, empty).allowed).toBe(false); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_CAST, "MY_GIRL"), true, empty).allowed).toBe(false); expect(resolveAutoPreviewDecision(mapping(ImportDataType.HEAVEN_STORE), true, empty).reason).toBe("AUTO_ROUTE_NOT_ENABLED"); expect(parseAutoExecutionRoutes("HEAVEN_SHOP,UNKNOWN").unknown).toEqual(["UNKNOWN"]); });
});
