import { AvailabilityBadge } from "./availability-badge";
import { ConfidenceBadge } from "./confidence-badge";
import { TrendIndicator } from "./trend-indicator";
import { formatMetric } from "@/lib/analytics/ui";
import type { ComparisonViewModel, MetricFormat, UiAvailability, UiConfidence, TrendDirection } from "@/lib/analytics/ui";

export function AnalyticsKpiCard({ label, value, format = "integer", unit, description, availability = "VALUE", confidence, sample, period, comparison, trend }: { label: string; value: unknown; format?: MetricFormat; unit?: string; description?: string; availability?: UiAvailability; confidence?: UiConfidence; sample?: string; period?: string; comparison?: ComparisonViewModel; trend?: { direction: TrendDirection; difference?: string | number | null; rate?: number | null; positiveIsBetter?: boolean } }) {
  return <article className="panel min-w-0 p-4" aria-label={label}><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="text-sm font-semibold text-slate-700">{label}</h3><AvailabilityBadge value={availability} hideValue /></div><p className="mt-2 break-words text-2xl font-bold tracking-tight text-slate-900">{formatMetric(value, format)}{unit && <span className="ml-1 text-sm font-medium text-slate-500">{unit}</span>}</p>{description && <p className="mt-1 text-xs text-slate-500">{description}</p>}{comparison && <div className="mt-3 border-t border-slate-100 pt-3"><TrendIndicator direction={trend?.direction ?? "UNAVAILABLE"} difference={comparison.difference} rate={comparison.rate} baselineLabel={comparison.label} comparisonPeriod={comparison.period} positiveIsBetter={trend?.positiveIsBetter} availability={comparison.availability} confidence={comparison.confidence} /></div>}<div className="mt-3 flex flex-wrap gap-2">{availability !== "VALUE" && <AvailabilityBadge value={availability} />}{confidence && <ConfidenceBadge value={confidence} />}{sample && <span className="text-xs text-slate-500">母数: {sample}</span>}{period && <span className="text-xs text-slate-500">期間: {period}</span>}</div></article>;
}
