"use client";
import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { AnalyticsPageLayout } from "@/components/analytics/shared";
type Metric = { value?: number | null; availability?: string; reason?: string };
type WeekdayRow = { weekday: number; label: string; sampleDays: number; confidence: string; primaryCause: string; causeCandidates?: Array<{ code: string; label: string; score: number; evidence: string[]; isPrimary?: boolean }>; recommendedActions?: Array<{ code: string; title: string; score: number; evidence: string[] }>; sales: Metric; townStoreUu: Metric; townDiaryPv: Metric; townCastPagePv: Metric; diaryPostActivityReference: Metric; reservations: Metric; workHours: Metric };
type DiaryResponse = { meta: { from: string; to: string }; availability: string; confidence: string; sample: { days: number }; summary: { efficiencies?: Record<string, Metric> }; postingActivity: Record<string, Metric>; exposure: Record<string, Metric>; conversion: { sales: Metric; compensation: Metric; reservations: Metric; contracts: Metric; efficiencies: Record<string, Metric> }; weekday: WeekdayRow[]; storeComparison: Array<Record<string, unknown>>; castComparison: Array<Record<string, unknown>>; dataNotes: string[]; };
const stores = [{ value: "ALL", label: "全体" }, { value: "KASUKABE", label: "春日部" }, { value: "KOSHIGAYA", label: "越谷" }, { value: "NODA", label: "野田（CTI補助）" }];
const value = (metric: Metric | undefined, suffix = "") => metric?.value === null || metric?.value === undefined ? "—" : `${Math.round(metric.value * 100) / 100}${suffix}`;
const availability = (metric: Metric | undefined) => metric?.availability ?? "MISSING";
const card = (label: string, metric: Metric | undefined, suffix = "") => <article className="panel p-4" key={label}><p className="text-sm font-semibold text-slate-700">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value(metric, suffix)}</p><p className="mt-1 text-xs text-slate-500">データ状態: {availability(metric)}</p></article>;

export function DiaryAnalyticsPage({ initialFrom, initialTo, initialStore }: { initialFrom: string; initialTo: string; initialStore: string }) {
  const [from, setFrom] = useState(initialFrom); const [to, setTo] = useState(initialTo); const [store, setStore] = useState(initialStore || "ALL"); const [data, setData] = useState<DiaryResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const selectedWeekday = params.get("weekday");
  const selectWeekday = (weekday?: number) => { const next = new URLSearchParams(params.toString()); if (weekday === undefined) next.delete("weekday"); else next.set("weekday", String(weekday)); router.replace(`${pathname}?${next.toString()}`); };
  const url = useMemo(() => `/api/analytics/diary?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&store=${encodeURIComponent(store)}&groupBy=weekday`, [from, to, store]);
  useEffect(() => { let active = true; fetch(url).then(async (response) => { if (!response.ok) throw new Error(await response.text()); return response.json() as Promise<DiaryResponse>; }).then((json) => { if (active) setData(json); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "読み込みに失敗しました"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [url]);
  const summary = data?.summary;
  return <AnalyticsPageLayout layoutOnly loading={loading}><div className="mx-auto max-w-[1500px] space-y-6"><header><p className="text-xs font-bold tracking-[0.18em] text-emerald-700">DIARY ANALYTICS</p><h1 className="mt-2 text-3xl font-bold text-slate-950">写メ日記分析</h1><p className="mt-2 text-sm text-slate-600">投稿活動、Town写メ日記閲覧、キャストページ閲覧、予約・売上を分けて確認します。相関指標は因果を示しません。</p></header>
    <form className="panel flex flex-wrap items-end gap-3 p-4" onSubmit={(event) => { event.preventDefault(); }}><label className="text-sm">開始日<input className="input mt-1 block" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-sm">終了日<input className="input mt-1 block" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><label className="text-sm">店舗<select className="input mt-1 block" value={store} onChange={(event) => setStore(event.target.value)}>{stores.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><span className="text-xs text-slate-500">{from}〜{to}</span></form>
    {loading && !data ? <div className="panel p-8 text-center text-slate-600">データを集計しています… CTI・Town・Heavenを統合しています</div> : error ? <div className="panel p-8 text-red-700">読み込みに失敗しました: {error}</div> : !data ? <div className="panel p-8">データがありません</div> : <>
      <section className="panel p-4"><div className="flex flex-wrap gap-5 text-sm"><span>対象日数: {data.sample.days}日</span><span>データ状態: {data.availability}</span><span>信頼度: {data.confidence}</span></div></section>
      <section><h2 className="mb-3 text-xl font-bold">投稿活動</h2><div className="grid gap-4 sm:grid-cols-3">{card("CTI写メ日記投稿数", data.postingActivity.ctiDiaryPostCount)}{card("Heaven写メ日記投稿数", data.postingActivity.heavenDiaryPostCount)}{card("写メ日記投稿活動参考値", data.postingActivity.diaryPostActivityReference)}</div><p className="mt-2 text-xs text-slate-500">CTIとHeavenの投稿数を参考的に合算した値です。正式な総投稿数ではありません。</p></section>
      <section><h2 className="mb-3 text-xl font-bold">写メ日記閲覧</h2><div className="grid gap-4 sm:grid-cols-3">{card("Town写メ日記PV", data.exposure.townDiaryPv)}{card("Town写メ日記UU", data.exposure.townDiaryUu)}{card("Town写メ日記TEL", data.exposure.townDiaryTel)}{card("PV／投稿活動", summary?.efficiencies?.townDiaryPvPerPost)}{card("UU／投稿活動", summary?.efficiencies?.townDiaryUuPerPost)}{card("Heaven写メ日記PV", data.exposure.heavenDiaryPv)}</div></section>
      <section><h2 className="mb-3 text-xl font-bold">キャストページ閲覧・成果</h2><div className="grid gap-4 sm:grid-cols-3">{card("TownキャストページPV", data.exposure.townCastPagePv)}{card("TownキャストページUU", data.exposure.townCastPageUu)}{card("予約", data.conversion.reservations)}{card("成約", data.conversion.contracts)}{card("売上", data.conversion.sales, "円")}{card("女子報酬", data.conversion.compensation, "円")}{card("売上／Town写メ日記PV", data.conversion.efficiencies.salesPerDiaryPv, "円")}{card("売上／Town UU", data.conversion.efficiencies.salesPerTownUu, "円")}</div></section>
      <section><h2 className="mb-3 text-xl font-bold">曜日別クロス分析</h2><p className="mb-2 text-xs text-slate-500">行を選択すると曜日詳細を開きます。優先度は因果効果ではなく確認優先度です。</p><div className="table-wrap"><table className="min-w-[1400px]"><thead><tr><th>曜日</th><th>対象日数</th><th>売上</th><th>Town店舗UU</th><th>Town写メ日記PV</th><th>TownキャストページPV</th><th>投稿活動参考値</th><th>予約</th><th>出勤時間</th><th>主要原因候補</th><th>優先度</th><th>信頼度</th><th>データ状態</th></tr></thead><tbody>{data.weekday.map((row) => <tr key={row.weekday} onClick={() => selectWeekday(row.weekday)} className="cursor-pointer hover:bg-slate-50"><td>{row.label}</td><td>{row.sampleDays}</td><td>{value(row.sales, "円")}</td><td>{value(row.townStoreUu)}</td><td>{value(row.townDiaryPv)}</td><td>{value(row.townCastPagePv)}</td><td>{value(row.diaryPostActivityReference)}</td><td>{value(row.reservations)}</td><td>{value(row.workHours, "時間")}</td><td>{row.causeCandidates?.map((candidate) => candidate.label).join(" / ") || row.primaryCause}</td><td>{row.causeCandidates?.[0]?.score ?? "—"}</td><td>{row.confidence}</td><td>{availability(row.sales)}</td></tr>)}</tbody></table></div>{selectedWeekday && (() => { const row = data.weekday.find((item) => String(item.weekday) === selectedWeekday); return row ? <div className="panel mt-4 p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">{row.label}の詳細</h3><button type="button" className="secondary-button" onClick={() => selectWeekday()}>閉じる</button></div><p className="mt-2 text-sm">原因候補：{row.causeCandidates?.map((candidate) => `${candidate.label}（${candidate.score}）`).join(" / ") || "安定"}</p><ul className="mt-2 list-disc pl-5 text-sm">{row.recommendedActions?.map((action) => <li key={action.code}>{action.title}：{action.evidence.join("、")}</li>)}</ul></div> : null; })()}</section>
      <section><h2 className="mb-3 text-xl font-bold">原因・推奨アクション</h2><div className="panel p-4"><p className="text-sm text-slate-600">原因候補 → 根拠 → 改善候補の順に確認してください。媒体指標と売上の関係は相関・比較であり、因果を断定しません。</p>{data.weekday.filter((row) => row.primaryCause !== "STABLE").slice(0, 5).map((row) => <div key={row.weekday} className="mt-2 text-sm"><strong>{row.label}：</strong>{row.causeCandidates?.map((candidate) => `${candidate.label}（${candidate.evidence.join("、")}）`).join(" / ")}<br /><span className="text-slate-600">アクション候補：{row.recommendedActions?.map((action) => action.title).join(" / ") || "—"}</span></div>)}</div></section>
      <section><h2 className="mb-3 text-xl font-bold">データについて</h2><ul className="list-disc space-y-1 pl-5 text-sm text-slate-600">{data.dataNotes.map((note) => <li key={note}>{note}</li>)}</ul></section>
    </>}</div></AnalyticsPageLayout>;
}
