"use client";
import { usePathname, useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AnalyticsEmptyState, AnalyticsErrorState, AnalyticsKpiCard, AnalyticsSection, AnalyticsSkeleton, AnalyticsUnavailableState, AvailabilityBadge, ConfidenceBadge, GrowthPotentialCard, NextBestActionCard } from ".";
import { formatMetric } from "@/lib/analytics/ui";
import { toPerformanceViewModel, type PerformanceResponseDto } from "@/lib/analytics/ui/performance-view-model";

type Props = { initialFrom: string; initialTo: string; initialStore: string };
const stores = [{ value: "ALL", label: "全体" }, { value: "KASUKABE", label: "春日部" }, { value: "KOSHIGAYA", label: "越谷" }];
const confidenceOrder = ["High", "Medium", "Low", "Insufficient"] as const;

export function PerformanceFunnelPage({ initialFrom, initialTo, initialStore }: Props) {
  const router = useRouter(); const pathname = usePathname(); const abortRef = useRef<AbortController | null>(null); const requestId = useRef(0);
  const [from, setFrom] = useState(initialFrom); const [to, setTo] = useState(initialTo); const [store, setStore] = useState(initialStore || "ALL"); const [search, setSearch] = useState(""); const [growth, setGrowth] = useState("ALL"); const [confidence, setConfidence] = useState("ALL"); const [sort, setSort] = useState("reward"); const [data, setData] = useState<PerformanceResponseDto | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [status, setStatus] = useState("");
  const load = useCallback(async (next?: { from?: string; to?: string; store?: string }) => { const currentFrom = next?.from ?? from; const currentTo = next?.to ?? to; const currentStore = next?.store ?? store; if (!currentFrom || !currentTo || currentFrom > currentTo) { setError("開始日は終了日以前にしてください。"); setLoading(false); return; } const days = (Date.parse(currentTo) - Date.parse(currentFrom)) / 86400000 + 1; if (!Number.isFinite(days) || days > 366) { setError("期間は366日以内で指定してください。"); setLoading(false); return; } abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; const id = ++requestId.current; setLoading(true); setError(null); setStatus("分析データを取得中"); try { const params = new URLSearchParams({ from: currentFrom, to: currentTo }); if (currentStore !== "ALL") params.set("store", currentStore); const response = await fetch(`/api/analytics/performance?${params}`, { signal: controller.signal, cache: "no-store" }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error ?? `HTTP ${response.status}`); } const json = await response.json() as PerformanceResponseDto; if (id !== requestId.current) return; setData(json); setStatus(`${json.casts.length}名の分析結果を表示中`); } catch (cause) { if (cause instanceof DOMException && cause.name === "AbortError") return; if (id === requestId.current) { setError(cause instanceof Error ? cause.message : "分析データを取得できませんでした。"); setStatus(""); } } finally { if (id === requestId.current) setLoading(false); } } , [from, store, to]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => { window.clearTimeout(timer); abortRef.current?.abort(); }; }, [load]);
  const apply = (event: React.FormEvent) => { event.preventDefault(); const params = new URLSearchParams({ from, to, period: "custom" }); if (store !== "ALL") params.set("store", store); router.replace(`${pathname}?${params}`); void load(); };
  const view = useMemo(() => data ? toPerformanceViewModel(data) : null, [data]);
  const filtered = useMemo(() => { if (!view) return []; return view.casts.filter((row) => (!search || row.name.toLowerCase().includes(search.toLowerCase())) && (growth === "ALL" || row.growthLabel === growth) && (confidence === "ALL" || row.confidence === confidence)).sort((a, b) => { const value = (row: typeof a) => row.summary.volume.metrics[sort === "sales" ? "sales" : sort === "reward" ? "castReward" : "attendanceMinutes"] ?? null; const av = value(a); const bv = value(b); if (typeof av === "number" && typeof bv === "number") return bv - av; return a.name.localeCompare(b.name, "ja"); }); }, [view, search, growth, confidence, sort]);
  const summary = view?.overall?.summary;
  const sample = summary?.sample;
  return <div className="mx-auto max-w-[1500px]" aria-busy={loading}><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-bold tracking-[0.18em] text-emerald-700">PERFORMANCE FUNNEL</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900">Performance Funnel</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Sample → Efficiency → Volume → Growth Potentialの順に確認します。媒体露出と予約は経路を特定できないため、因果関係ではなく参考指標として表示します。</p></div><button type="button" className="secondary-button" onClick={() => void load()} disabled={loading}>{loading ? "再取得中…" : "再取得"}</button></header>
    <form className="panel mb-6 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-6" onSubmit={apply}><label className="form-label">開始日<input className="form-input mt-1" type="date" value={from} onChange={(e) => setFrom(e.target.value)} required /></label><label className="form-label">終了日<input className="form-input mt-1" type="date" value={to} onChange={(e) => setTo(e.target.value)} required /></label><label className="form-label">店舗<select className="form-input mt-1" value={store} onChange={(e) => setStore(e.target.value)}>{stores.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="form-label">Cast検索<input className="form-input mt-1" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="名前で検索" /></label><label className="form-label">Growth<select className="form-input mt-1" value={growth} onChange={(e) => setGrowth(e.target.value)}><option value="ALL">すべて</option>{["Data不足", "Capacity上限", "Schedule制約", "Exposure不足", "Activity不足", "Efficiency改善余地", "安定維持"].map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="form-label">Confidence<select className="form-input mt-1" value={confidence} onChange={(e) => setConfidence(e.target.value)}><option value="ALL">すべて</option>{confidenceOrder.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="form-label">並び順<select className="form-input mt-1" value={sort} onChange={(e) => setSort(e.target.value)}><option value="reward">女子報酬</option><option value="sales">売上</option><option value="attendanceMinutes">出勤時間</option></select></label><button className="primary-button sm:col-span-2 xl:col-span-6">表示</button></form>
    <p className="sr-only" role="status">{status}</p>{error && <AnalyticsErrorState message={error} />}{loading && !view && <AnalyticsSkeleton count={4} />}{!loading && !error && view && view.casts.length === 0 && <AnalyticsEmptyState title="対象キャストがありません" description="指定期間・店舗に分析可能なキャスト実績がありません。" />}
    {!loading && !error && view && view.casts.length > 0 && <><AnalyticsSection title="Sample / Data Health" description="最初に母数とデータ取得状態を確認してください。" period={`${view.period.from}〜${view.period.to}`}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><AnalyticsKpiCard label="対象日数" value={sample?.targetDays ?? null} format="count" availability={sample ? sample.targetDays === 0 ? "ZERO" : "VALUE" : "MISSING"} sample={`${sample?.uniqueCastCount ?? 0}名`} /><AnalyticsKpiCard label="出勤回数" value={sample?.attendanceCount ?? null} format="count" availability={sample ? sample.attendanceCount === 0 ? "ZERO" : "VALUE" : "MISSING"} /><AnalyticsKpiCard label="総出勤時間" value={sample?.totalAttendanceHours ?? null} format="hours" availability={sample ? sample.totalAttendanceHours === 0 ? "ZERO" : "VALUE" : "MISSING"} /><article className="panel p-4"><h3 className="text-sm font-semibold text-slate-700">Confidence</h3><div className="mt-3"><ConfidenceBadge value={sample?.confidence ?? "Insufficient"} /></div><p className="mt-3 text-xs text-slate-500">ユニークCast数: {sample?.uniqueCastCount ?? "—"}<br />媒体未取得は0ではなく欠測として扱います。</p></article></div></AnalyticsSection>
      <AnalyticsSection title="Efficiency" description="日別の単純平均ではなく、Engineが期間合計から算出した効率値です。"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(view.overall?.efficiency ?? []).map((metric) => <AnalyticsKpiCard key={metric.key} label={metric.label} value={metric.value} format={metric.format} availability={metric.availability} description={metric.description} />)}</div></AnalyticsSection>
      <AnalyticsSection title="Volume" description="予約と媒体露出は別の指標群です。Town／Heavenから予約経路を推定しません。"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(view.overall?.volume ?? []).map((metric) => <AnalyticsKpiCard key={metric.key} label={metric.label} value={metric.value} format={metric.format} availability={metric.availability} description={metric.description} />)}</div></AnalyticsSection>
      <AnalyticsSection title="Growth Potential / Next Best Action" description="全体GrowthがAPI DTOにない場合は、判定を推測せず未接続として表示します。"><div className="grid gap-4 lg:grid-cols-2">{summary?.growth ? <GrowthPotentialCard classification={summary.growth.classification} reason={summary.growth.reason} evidence={summary.growth.evidence} availability={summary.growth.availability} score={summary.growth.score} /> : <AnalyticsUnavailableState title="全体Growthは未接続" description="Performance APIは現在Cast単位のGrowth判定を返します。全体判定は推測しません。" />}{summary?.nextBestAction ? <NextBestActionCard result={summary.nextBestAction} /> : <AnalyticsUnavailableState title="全体のNext Best Actionは未接続" description="対象単位の判定が返されていません。" />}</div></AnalyticsSection>
      <AnalyticsSection title="Cast一覧" description={`表示 ${filtered.length}名 / 対象 ${view.casts.length}名。並び順: ${sort === "reward" ? "女子報酬" : sort === "sales" ? "売上" : "出勤時間"}降順`}><div className="mb-3 flex flex-wrap gap-2 text-xs text-slate-500"><span>検索結果: {filtered.length}名</span><span>色だけで状態を判断せず、AvailabilityとConfidenceを確認してください。</span></div><div className="grid gap-4 md:hidden">{filtered.map((row) => <article key={row.castId} className="panel min-w-0 p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-900">{row.name}</h3><p className="text-xs text-slate-500">Cast ID: {row.castId}</p></div><AvailabilityBadge value={row.availability} /></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm">{row.metrics.slice(0, 6).map((metric) => <div key={metric.key} className="min-w-0"><p className="text-xs text-slate-500">{metric.label}</p><p className="truncate font-medium">{formatMetric(metric.value, metric.format)}</p></div>)}</div><div className="mt-3 flex flex-wrap gap-2"><ConfidenceBadge value={row.confidence} /><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{row.growthLabel}</span><span className="text-xs text-slate-500">Action: {row.actionLevel}</span></div></article>)}</div><div className="table-wrap hidden md:block"><table><caption className="sr-only">Performance Funnel Cast一覧</caption><thead><tr><th>Cast</th><th>Confidence</th><th>Growth</th><th>Availability</th><th aria-sort={sort === "reward" ? "descending" : "none"}>女子報酬</th><th aria-sort={sort === "sales" ? "descending" : "none"}>売上</th><th>売上／時間</th><th>女子報酬／時間</th><th>予約</th><th>出勤時間</th><th>Action</th></tr></thead><tbody>{filtered.map((row) => { const metric = (key: string) => row.metrics.find((item) => item.key === key); return <tr key={row.castId}><td className="font-medium text-slate-900">{row.name}</td><td><ConfidenceBadge value={row.confidence} /></td><td>{row.growthLabel}</td><td><AvailabilityBadge value={row.availability} /></td><td>{formatMetric(metric("castReward")?.value, "currency")}</td><td>{formatMetric(metric("sales")?.value, "currency")}</td><td>{formatMetric(metric("salesPerHour")?.value, "hourly")}</td><td>{formatMetric(metric("rewardPerHour")?.value, "hourly")}</td><td>{formatMetric(metric("reservations")?.value, "count")}</td><td>{formatMetric(metric("attendanceMinutes")?.value, "hours")}</td><td>{row.summary.nextBestAction?.actionLevel ?? "NONE"}</td></tr>; })}</tbody></table></div></AnalyticsSection></>}</div>;
}
