"use client";
import { useMemo } from "react";
import { AnalyticsPageLayout, AnalyticsHeader, AnalyticsFilterBar, AnalyticsPeriodPicker, AnalyticsStoreSelector, AnalyticsSection, AnalyticsMetricGroup, AnalyticsTable, AnalyticsLoadingState, AnalyticsErrorMessage, AnalyticsUnavailableMessage } from "@/components/analytics/shared";
import { useAnalyticsFilters, useAnalyticsQuery } from "@/hooks/analytics";
import { formatMetric } from "@/lib/analytics/ui";
import { storeMetric, storeMetricAvailability, STORE_METRICS, type StoreSummaryDto, type StoreResponseDto } from "@/lib/analytics/ui/store-view-model";

const stores = [{ value: "ALL", label: "全体" }, { value: "KASUKABE", label: "春日部" }, { value: "KOSHIGAYA", label: "越谷" }, { value: "NODA", label: "野田" }];
const storeUrl = (from: string, to: string, store: string) => `/api/analytics/store?${new URLSearchParams({ from, to, ...(store !== "ALL" ? { store } : {}) })}`;
const availability = (summary: StoreSummaryDto["summary"] | undefined, key: string) => String(storeMetricAvailability(summary, key));

export function StoreAnalyticsPage({ initialFrom, initialTo, initialStore }: { initialFrom: string; initialTo: string; initialStore: string }) {
  const defaults = useMemo(() => ({ from: initialFrom, to: initialTo, store: initialStore || "ALL" }), [initialFrom, initialTo, initialStore]);
  const { filters, updateFilters } = useAnalyticsFilters(defaults);
  const query = useAnalyticsQuery<StoreResponseDto>(storeUrl(filters.from, filters.to, filters.store));
  const selected = filters.store === "ALL" ? query.data?.overall : query.data?.storeSummaries?.find((item) => item.store.code === filters.store)?.summary;
  const selectedName = stores.find((item) => item.value === filters.store)?.label ?? "全体";
  const selectedStore = query.data?.stores.find((item) => item.code === filters.store);
  const comparisonRows = selected?.comparison ?? [];
  return <AnalyticsPageLayout layoutOnly loading={query.loading}>
    <div className="mx-auto max-w-[1500px] space-y-6" aria-busy={query.loading}>
      <AnalyticsHeader title="Store Analytics" eyebrow="STORE ANALYTICS" description="店舗のCause・Evidence・Actionを、Sample → Efficiency → Volumeの順で確認します。" storeLabel={selectedName} period={`${filters.from}〜${filters.to}`} loading={query.loading} onRefresh={query.retry} />
      <AnalyticsFilterBar><AnalyticsPeriodPicker from={filters.from} to={filters.to} onChange={updateFilters} /><AnalyticsStoreSelector value={filters.store} stores={stores} onChange={(store) => updateFilters({ store })} /></AnalyticsFilterBar>
      {query.error ? <AnalyticsErrorMessage message={query.error} onRetry={query.retry} /> : null}
      {query.loading && !query.data ? <AnalyticsLoadingState /> : !query.data ? <AnalyticsUnavailableMessage message="店舗分析データを取得できません。" /> : selected ? <>
        <AnalyticsSection title="Cause"><article className="panel p-5"><h2 className="text-lg font-semibold">{selectedName}の現在地</h2><p className="mt-2 text-sm text-slate-600">Growth: {selected.growth?.classification ?? "—"} / {selected.growth?.reason ?? "根拠データを確認してください。"}</p><p className="mt-1 text-xs text-slate-500">Confidence: {selected.sample.confidence} / Availability: {selected.growth?.availability ?? "MISSING"}</p></article></AnalyticsSection>
        <AnalyticsSection title="Evidence" description={`${selectedStore?.shortName ?? selectedName} / ${filters.from}〜${filters.to}`}>
          <AnalyticsSection title="Store Summary"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{STORE_METRICS.slice(0, 8).map(([key, label, format]) => <article className="panel p-4" key={key}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold">{formatMetric(storeMetric(selected, key), format)}</p><p className="mt-1 text-xs text-slate-500">{availability(selected, key)} / {selected.sample.confidence}</p></article>)}</div></AnalyticsSection>
          <AnalyticsSection title="Performance"><AnalyticsMetricGroup title="Volume" metrics={STORE_METRICS.filter((item) => ["sales", "castReward", "attendancePeople", "reservations", "services", "regularNominations", "diaryPosts"].includes(item[0])).map(([key, label, format]) => ({ key, label, value: storeMetric(selected, key), format, hint: availability(selected, key) }))} /><AnalyticsMetricGroup title="Efficiency" metrics={STORE_METRICS.filter((item) => ["salesPerHour", "rewardPerHour"].includes(item[0])).map(([key, label, format]) => ({ key, label, value: storeMetric(selected, key), format, hint: availability(selected, key) }))} /></AnalyticsSection>
          <AnalyticsSection title="Trend" description="UIでは差分を再計算せず、Performance APIのComparison DTOを表示します."><AnalyticsTable caption="店舗期間比較" columns={[{ key: "baseline", label: "比較" }, { key: "current", label: "現在" }, { key: "difference", label: "差分" }, { key: "rate", label: "差異率" }, { key: "availability", label: "状態" }]} rows={comparisonRows} renderCell={(row, column) => { const item = row as NonNullable<typeof selected.comparison>[number]; if (column.key === "baseline") return item.baselineKind; if (column.key === "current") return formatMetric(item.current, "currency"); if (column.key === "difference") return formatMetric(item.difference, "currency"); if (column.key === "rate") return item.differenceRate == null ? "—" : `${(item.differenceRate * 100).toFixed(1)}%`; return item.availability; }} /></AnalyticsSection>
          <AnalyticsSection title="Time"><AnalyticsTable caption="曜日別店舗分析" columns={[{ key: "label", label: "曜日" }, { key: "sales", label: "売上" }, { key: "efficiency", label: "売上／時間" }, { key: "sample", label: "Sample" }, { key: "confidence", label: "Confidence" }]} rows={query.data.weekdays ?? []} rowKey={(row) => String((row as { weekday: number }).weekday)} renderCell={(row, column) => { const item = row as NonNullable<StoreResponseDto["weekdays"]>[number]; if (column.key === "label") return item.label; if (column.key === "sales") return formatMetric(item.volume.metrics.sales, "currency"); if (column.key === "efficiency") return formatMetric(item.efficiency.salesPerHour, "currency"); if (column.key === "sample") return `${String(item.sample.targetDays ?? "—")}日`; return String(item.sample.confidence ?? "Insufficient"); }} /></AnalyticsSection>
          <AnalyticsSection title="Exposure"><AnalyticsMetricGroup title="媒体露出" metrics={STORE_METRICS.filter((item) => ["townPv", "townUu", "heavenAccess"].includes(item[0])).map(([key, label, format]) => ({ key, label, value: storeMetric(selected, key), format, hint: `${availability(selected, key)}。予約経路とは結び付きません。` }))} /></AnalyticsSection>
          <AnalyticsSection title="Cast Composition"><AnalyticsUnavailableMessage message="在籍人数・上位下位・平均値を返すStore専用DTOは未提供です。UIで平均や順位を生成していません。" /></AnalyticsSection>
          <AnalyticsSection title="Store Comparison"><div className="grid gap-4 md:grid-cols-2">{(query.data.storeSummaries ?? []).map((item) => <article className="panel p-4" key={item.store.id}><h3 className="font-semibold">{item.store.shortName}</h3><p className="mt-2">売上: {formatMetric(storeMetric(item.summary, "sales"), "currency")}</p><p>売上／時間: {formatMetric(storeMetric(item.summary, "salesPerHour"), "currency")}</p><p className="mt-2 text-xs text-slate-500">{availability(item.summary, "sales")} / {item.summary.sample.confidence}</p><p className="text-xs text-slate-500">Growth: {item.summary.growth?.classification ?? "—"}</p></article>)}</div></AnalyticsSection>
        </AnalyticsSection>
        <AnalyticsSection title="Action"><article className="panel p-5"><h2 className="text-lg font-semibold">Growth</h2><p className="mt-2">{selected.growth?.classification ?? "—"}</p><p className="mt-2 text-sm text-slate-600">{selected.growth?.evidence?.join(" / ") || selected.growth?.reason || "根拠データがありません。"}</p><h2 className="mt-5 text-lg font-semibold">Next Best Action</h2><p className="mt-2">{selected.nextBestAction?.action ?? "提案なし"}</p><p className="mt-2 text-xs text-slate-500">原因: {selected.nextBestAction?.cause ?? "—"} / Confidence: {selected.nextBestAction?.confidence ?? "Insufficient"}</p></article></AnalyticsSection>
        <AnalyticsSection title="Data Notes"><p className="text-sm text-slate-600">Volumeだけで判断せず、Efficiency・Sample・Availabilityを併せて確認してください。Trendは因果関係を示しません。ZEROとMISSINGを区別し、未提供指標は推測していません。</p></AnalyticsSection>
      </> : <AnalyticsUnavailableMessage message="選択店舗の分析データがありません。" />}
    </div>
  </AnalyticsPageLayout>;
}
