"use client";
import { usePathname, useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AnalyticsEmptyState, AnalyticsErrorState, AnalyticsKpiCard, AnalyticsSection, AnalyticsSkeleton, AnalyticsUnavailableState, AvailabilityBadge, GrowthPotentialBadge, TrendIndicator } from ".";
import { formatMetric } from "@/lib/analytics/ui";
import { comparisonLabels, toTrendViewModel, type ComparisonKey, type TrendResponseDto } from "@/lib/analytics/ui/trend-view-model";

type Props = { initialFrom: string; initialTo: string; initialStore: string; initialComparison: ComparisonKey };
const storeOptions = [{ value: "ALL", label: "全体" }, { value: "KASUKABE", label: "春日部" }, { value: "KOSHIGAYA", label: "越谷" }];
function direction(value?: string) { return value === "increase" ? "INCREASE" : value === "decrease" ? "DECREASE" : value === "flat" ? "FLAT" : "UNAVAILABLE"; }

export function TrendAnalyticsPage({ initialFrom, initialTo, initialStore, initialComparison }: Props) {
  const router = useRouter(); const pathname = usePathname(); const abortRef = useRef<AbortController | null>(null); const requestId = useRef(0);
  const [from, setFrom] = useState(initialFrom); const [to, setTo] = useState(initialTo); const [store, setStore] = useState(initialStore || "ALL"); const [comparison, setComparison] = useState<ComparisonKey>(initialComparison); const [metricGroup, setMetricGroup] = useState<"efficiency" | "volume">("efficiency"); const [castSearch, setCastSearch] = useState(""); const [data, setData] = useState<TrendResponseDto | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [status, setStatus] = useState("");
  const load = useCallback(async () => { if (!from || !to || from > to) { setError("開始日は終了日以前にしてください。"); setLoading(false); return; } const days = (Date.parse(to) - Date.parse(from)) / 86400000 + 1; if (!Number.isFinite(days) || days > 366) { setError("期間は366日以内で指定してください。"); setLoading(false); return; } abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; const id = ++requestId.current; setLoading(true); setError(null); setStatus("Trend分析を取得中"); try { const params = new URLSearchParams({ from, to, comparison }); if (store !== "ALL") params.set("store", store); const response = await fetch(`/api/analytics/trend?${params}`, { signal: controller.signal, cache: "no-store" }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error ?? `HTTP ${response.status}`); } const json = await response.json() as TrendResponseDto; if (id !== requestId.current) return; setData(json); setStatus("Trend分析を表示中"); } catch (cause) { if (cause instanceof DOMException && cause.name === "AbortError") return; if (id === requestId.current) { setError(cause instanceof Error ? cause.message : "Trend分析を取得できませんでした。"); setStatus(""); } } finally { if (id === requestId.current) setLoading(false); } }, [comparison, from, store, to]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => { window.clearTimeout(timer); abortRef.current?.abort(); }; }, [load]);
  const apply = (event: React.FormEvent) => { event.preventDefault(); const params = new URLSearchParams({ period: "custom", from, to, comparison }); if (store !== "ALL") params.set("store", store); router.replace(`${pathname}?${params}`); void load(); };
  const view = useMemo(() => data ? toTrendViewModel(data, comparison) : null, [data, comparison]);
  const castRows = useMemo(() => [], []);
  const comparisonLabel = view?.selectedComparison ? comparisonLabels[view.selectedComparison.baselineKind as ComparisonKey] ?? view.selectedComparison.baselineKind : comparisonLabels[comparison];
  return <div className="mx-auto max-w-[1500px]" aria-busy={loading}><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-bold tracking-[0.18em] text-emerald-700">TREND ANALYTICS</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900">Trend Analytics</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">増減率だけで判断せず、Sample → Efficiency → Volume → Comparison Evidenceの順に確認します。</p></div><button className="secondary-button" type="button" onClick={() => void load()} disabled={loading}>{loading ? "再取得中…" : "再取得"}</button></header>
    <form className="panel mb-6 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-6" onSubmit={apply}><label className="form-label">開始日<input className="form-input mt-1" type="date" value={from} onChange={(e) => setFrom(e.target.value)} required /></label><label className="form-label">終了日<input className="form-input mt-1" type="date" value={to} onChange={(e) => setTo(e.target.value)} required /></label><label className="form-label">店舗<select className="form-input mt-1" value={store} onChange={(e) => setStore(e.target.value)}>{storeOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="form-label">比較軸<select className="form-input mt-1" value={comparison} onChange={(e) => setComparison(e.target.value as ComparisonKey)}>{(Object.keys(comparisonLabels) as ComparisonKey[]).map((key) => <option key={key} value={key}>{comparisonLabels[key]}</option>)}</select></label><label className="form-label">指標群<select className="form-input mt-1" value={metricGroup} onChange={(e) => setMetricGroup(e.target.value as "efficiency" | "volume")}><option value="efficiency">Efficiency</option><option value="volume">Volume</option></select></label><label className="form-label">Cast検索<input className="form-input mt-1" value={castSearch} onChange={(e) => setCastSearch(e.target.value)} placeholder="名前で検索" /></label><button className="primary-button sm:col-span-2 xl:col-span-6">表示</button></form>
    <p className="sr-only" role="status">{status}</p>{error && <AnalyticsErrorState message={error} />}{loading && !view && <AnalyticsSkeleton count={4} />}{!loading && !error && view && !view.selectedComparison && <AnalyticsUnavailableState title="比較データがありません" description="比較期間の実績がないため、増減を算出できません。" />}{!loading && !error && view && <><AnalyticsSection title="Sample / Data Health" description="比較結果を見る前に、現在期間と比較期間の母数を確認してください。" period={`${view.period.from}〜${view.period.to}`}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><AnalyticsKpiCard label="現在期間 対象日数" value={view.sample?.targetDays ?? null} format="count" availability={view.sample ? view.sample.targetDays === 0 ? "ZERO" : "VALUE" : "MISSING"} /><AnalyticsKpiCard label="出勤回数" value={view.sample?.attendanceCount ?? null} format="count" availability={view.sample ? view.sample.attendanceCount === 0 ? "ZERO" : "VALUE" : "MISSING"} /><AnalyticsKpiCard label="総出勤時間" value={view.sample?.totalAttendanceHours ?? null} format="hours" availability={view.sample ? view.sample.totalAttendanceHours === 0 ? "ZERO" : "VALUE" : "MISSING"} /><article className="panel p-4"><h2 className="text-sm font-semibold text-slate-700">比較基準</h2><p className="mt-2 text-lg font-semibold">{comparisonLabel}</p><p className="mt-2 text-xs text-slate-500">現在Confidence: {view.sample?.confidence ?? "Insufficient"}<br />比較期間はAPIのComparison DTOを表示しています。</p>{view.selectedComparison && <AvailabilityBadge value={view.selectedComparison.availability} />}</article></div></AnalyticsSection>
      <AnalyticsSection title="Efficiency Trend" description="期間合計から算出された効率値と、選択した比較軸の差分です。"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{view.efficiency.map((metric) => <AnalyticsKpiCard key={metric.key} label={metric.label} value={metric.value} format={metric.format} availability={metric.availability} confidence={metric.confidence} description={metric.description} comparison={view.selectedComparison ? { current: metric.value, baseline: view.selectedComparison.baseline, difference: view.selectedComparison.difference, rate: view.selectedComparison.differenceRate, label: comparisonLabel, period: `${view.selectedComparison.period.from}〜${view.selectedComparison.period.to}`, availability: view.selectedComparison.availability, confidence: view.selectedComparison.confidence } : undefined} trend={view.selectedComparison ? { direction: direction(view.selectedComparison.direction), rate: view.selectedComparison.differenceRate, positiveIsBetter: metric.positiveIsBetter ?? undefined } : undefined} />)}</div></AnalyticsSection>
      <AnalyticsSection title="Volume Trend" description="売上・接客・活動量・媒体露出を分けて確認します。媒体露出と予約の因果関係は推測しません。"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(metricGroup === "volume" ? view.volume : view.volume.slice(0, 4)).map((metric) => <AnalyticsKpiCard key={metric.key} label={metric.label} value={metric.value} format={metric.format} availability={metric.availability} confidence={metric.confidence} description={metric.description} comparison={view.selectedComparison ? { current: metric.value, baseline: view.selectedComparison.baseline, difference: view.selectedComparison.difference, rate: view.selectedComparison.differenceRate, label: comparisonLabel, period: `${view.selectedComparison.period.from}〜${view.selectedComparison.period.to}`, availability: view.selectedComparison.availability, confidence: view.selectedComparison.confidence } : undefined} trend={view.selectedComparison ? { direction: direction(view.selectedComparison.direction), rate: view.selectedComparison.differenceRate, positiveIsBetter: metric.positiveIsBetter ?? undefined } : undefined} />)}</div></AnalyticsSection>
      <AnalyticsSection title="Store比較" description={`選択中の比較軸: ${comparisonLabel}`}><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{view.storeSummaries.map((item) => { const comparisonItem = item.summary.comparison?.find((candidate) => candidate.baselineKind === comparison); const sales = item.summary.volume.metrics.sales; return <article key={item.store.id} className="panel min-w-0 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold text-slate-900">{item.store.shortName}</h3>{comparisonItem && <AvailabilityBadge value={comparisonItem.availability} />}</div><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-500">売上</p><p className="font-semibold">{formatMetric(sales, "currency")}</p></div><div><p className="text-xs text-slate-500">売上／時間</p><p className="font-semibold">{formatMetric(item.summary.efficiency.salesPerHour, "hourly")}</p></div></div>{comparisonItem && <div className="mt-3"><TrendIndicator direction={direction(comparisonItem.direction)} difference={comparisonItem.difference} rate={comparisonItem.differenceRate} baselineLabel={comparisonLabel} comparisonPeriod={`${comparisonItem.period.from}〜${comparisonItem.period.to}`} positiveIsBetter /><p className="mt-2 text-xs text-slate-500">Confidence: {comparisonItem.confidence ?? "Insufficient"}</p></div>}{item.summary.growth && <div className="mt-3 flex flex-wrap gap-2"><GrowthPotentialBadge value={item.summary.growth.classification} /><span className="text-xs text-slate-500">Action: {item.summary.nextBestAction?.actionLevel ?? "NONE"}</span></div>}</article>; })}</div>{view.storeSummaries.length === 0 && <AnalyticsEmptyState title="店舗比較データがありません" />}</AnalyticsSection>
      <AnalyticsSection title="Cast比較"><AnalyticsUnavailableState title="Cast単位TrendはAPI未接続" description="Performance APIのCast結果をTrendへ推測転用せず、Cast Trend DTOの接続後に表示します。" />{castRows.length > 0 && <div />}</AnalyticsSection>
    </>}</div>;
}
