import Link from "next/link";
import type { DailyBriefDto, BriefMetric } from "@/lib/analytics/integration/daily-brief";

const formatMetric = (metric: BriefMetric) => {
  if (metric.availability === "MISSING") return "データ不足";
  if (metric.availability === "UNAVAILABLE") return "利用できません";
  if (metric.availability === "UNCOMPUTABLE") return "算出できません";
  if (metric.value === null) return "—";
  if (metric.unit === "yen") return `¥${Math.round(metric.value).toLocaleString("ja-JP")}`;
  if (metric.unit === "hours") return `${metric.value.toLocaleString("ja-JP", { maximumFractionDigits: 1 })}時間`;
  if (metric.unit === "percent") return `${(metric.value * 100).toLocaleString("ja-JP", { maximumFractionDigits: 1 })}%`;
  return metric.value.toLocaleString("ja-JP", { maximumFractionDigits: 1 });
};

const MetricCard = ({ label, metric }: { label: string; metric: BriefMetric }) => <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold text-slate-900">{formatMetric(metric)}</p><p className="mt-1 text-xs text-slate-500">データ状態：{metric.availability === "VALUE" ? "利用可能" : metric.availability === "ZERO" ? "0件" : metric.availability === "MISSING" ? "データ不足" : metric.availability === "UNAVAILABLE" ? "利用できません" : "算出できません"}</p></div>;

export function DailyBrief({ brief }: { brief: DailyBriefDto }) {
  const healthClass = brief.dataHealth.level === "HEALTHY" ? "border-emerald-200 bg-emerald-50 text-emerald-950" : brief.dataHealth.level === "CRITICAL" ? "border-red-200 bg-red-50 text-red-950" : "border-amber-200 bg-amber-50 text-amber-950";
  return <section aria-labelledby="daily-brief-title" className="mb-6 space-y-5">
    <div className={`rounded-2xl border p-4 ${healthClass}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="daily-brief-title" className="font-semibold">Daily Brief：今日の運営確認</h2><p className="mt-1 text-sm">最新確定データ：{brief.meta.latestDataAt ?? "確認できません"} ／ 画面生成：{new Date(brief.meta.generatedAt).toLocaleString("ja-JP", { timeZone: "Asia/Tokyo" })}</p><p className="mt-1 text-sm">{brief.dataHealth.message}</p></div><Link href={brief.dataHealth.detailUrl} className="rounded-lg border border-current px-3 py-2 text-sm font-medium underline">データ状態を確認</Link></div><div className="mt-3 flex flex-wrap gap-3 text-xs"><span>未確定Batch {brief.dataHealth.pendingBatchCount}件</span><span>FAILED {brief.dataHealth.failedBatchCount}件</span><span>OPENエラー {brief.dataHealth.openErrorCount}件</span></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-900">今日の優先アクション</h2><p className="mt-1 text-sm text-slate-500">現在の状況 → 判断根拠 → 推奨確認の順で表示しています。</p></div><span className="text-xs text-slate-500">最大3件</span></div>{brief.priorityActions.length ? <div className="mt-4 grid gap-3 lg:grid-cols-3">{brief.priorityActions.map((action) => <article key={action.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${action.priority === "HIGH" ? "bg-red-100 text-red-800" : action.priority === "MEDIUM" ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-700"}`}>{action.priority === "HIGH" ? "最優先" : action.priority === "MEDIUM" ? "優先" : "確認"}</span><span className="text-xs text-slate-500">{action.category === "DATA_HEALTH" ? "データ状態" : action.category === "SALES" ? "売上" : action.category === "RESERVATION" ? "予約" : "運営"}</span></div><h3 className="mt-3 font-semibold text-slate-900">{action.title}</h3><p className="mt-2 text-sm text-slate-700">{action.situation}</p><p className="mt-3 text-xs font-medium text-slate-500">判断根拠</p><ul className="mt-1 list-disc pl-5 text-xs text-slate-600">{action.evidence.map((evidence) => <li key={evidence}>{evidence}</li>)}</ul><p className="mt-3 text-sm text-slate-700">推奨確認：{action.recommendedCheck}</p><Link href={action.detailUrl} className="mt-3 inline-block text-sm font-medium text-emerald-700 underline">詳細を見る</Link></article>)}</div> : <p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900" role="status">現在、優先度の高い確認事項はありません。</p>}</div>
    <div><h2 className="mb-3 text-lg font-semibold text-slate-900">前日の主要KPI（{brief.previousDay.businessDate}）</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><MetricCard label="売上" metric={brief.previousDay.sales}/><MetricCard label="予約数" metric={brief.previousDay.reservations}/><MetricCard label="成約数" metric={brief.previousDay.contracts}/><MetricCard label="出勤人数" metric={brief.previousDay.attendanceCount}/><MetricCard label="出勤時間" metric={brief.previousDay.workHours}/><MetricCard label="本指名率" metric={brief.previousDay.nominationRate}/></div></div>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-900">今月の目標進捗</h2><Link href="/settings/goals" className="text-sm text-emerald-700 underline">目標を管理</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><MetricCard label="現在売上" metric={brief.monthProgress.currentSales}/><MetricCard label="月目標" metric={brief.monthProgress.goalSales}/><MetricCard label="達成率" metric={brief.monthProgress.achievementRate}/><MetricCard label="着地予測" metric={brief.monthProgress.projectedSales}/></div><p className="mt-3 text-xs text-slate-500">残り日数：{brief.monthProgress.remainingDays ?? "—"}日 ／ 残り差額：{formatMetric(brief.monthProgress.remainingGap)}</p></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold text-slate-900">店舗別要対応</h2><div className="mt-3 space-y-2">{brief.storeIssues.length ? brief.storeIssues.map((issue) => <Link href={issue.detailUrl} key={issue.storeId} className="block rounded-xl border border-slate-200 p-3 hover:border-emerald-300"><div className="flex justify-between gap-2"><strong>{issue.storeName}</strong><span className="text-xs text-amber-700">{issue.priority === "MEDIUM" ? "確認推奨" : "参考"}</span></div><p className="mt-1 text-sm text-slate-700">{issue.situation}</p><p className="mt-1 text-xs text-slate-500">{issue.evidence.join(" ／ ")}</p></Link>) : <p className="text-sm text-slate-500">対象店舗の要対応はありません。</p>}</div></section></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold text-slate-900">要確認キャスト</h2><p className="mt-1 text-sm text-slate-500">人格評価ではなく、データ上の確認候補です。</p><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{brief.castIssues.length ? brief.castIssues.map((issue) => <Link href={issue.detailUrl} key={issue.castId} className="rounded-xl border border-slate-200 p-3 hover:border-emerald-300"><strong>{issue.castName}</strong><span className="ml-2 text-xs text-slate-500">{issue.storeName ?? "所属不明"}</span><p className="mt-1 text-sm text-slate-700">{issue.situation}</p><p className="mt-1 text-xs text-slate-500">{issue.evidence.join(" ／ ")} ／ 信頼度：{issue.confidence === "High" ? "高い" : issue.confidence === "Medium" ? "標準" : issue.confidence === "Low" ? "低い" : "サンプル不足"}</p></Link>) : <p className="text-sm text-slate-500">現在、要確認キャストはありません。</p>}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold text-slate-900">媒体活動の概要</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Town店舗PV" metric={brief.mediaActivity.townShopPv}/><MetricCard label="Town店舗UU" metric={brief.mediaActivity.townShopUu}/><MetricCard label="Heaven女の子ページアクセス" metric={brief.mediaActivity.heavenCastAccess}/><MetricCard label="Heaven写メ日記投稿数" metric={brief.mediaActivity.heavenDiaryPosts}/></div><ul className="mt-3 list-disc pl-5 text-xs text-slate-500">{brief.mediaActivity.notes.map((note) => <li key={note}>{note}</li>)}</ul></section>
    <nav aria-label="詳細分析へのリンク" className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold text-slate-900">詳細分析へ進む</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{brief.quickLinks.map((link) => <Link href={link.href} key={link.href} className="rounded-xl border border-slate-200 p-3 text-sm hover:border-emerald-300"><strong>{link.label}</strong><span className="ml-2 text-xs text-slate-500">{link.description}</span></Link>)}</div></nav>
  </section>;
}
