"use client";

import Link from "next/link";
import { useState } from "react";
import { MetricHelp } from "@/components/metric-help";

type Point = { date: string; sales: number; attendance: number; minutes: number; contracts: number; salesPerAttendance: number | null; salesPerHour: number | null };
type CumulativePoint = Point & { cumulative: number; target: number | null; forecast: number | null; targetGap: number | null };
type StoreRow = { name: string; sales: number; reward: number; contracts: number; days: number; minutes: number; regularRate: number | null; pv: number | null; pvDay: number | null; heaven: number | null; heavenDay: number | null };
type ScatterRow = { id: string; name: string; store: string | null; attendanceDays: number; attendanceMinutes: number; sales: number; reward: number; x: number | null; y: number | null; lowSample: boolean; tags: string[] };
const fmt = (v: number | null, digits = 0) => v === null ? "—" : v.toLocaleString("ja-JP", { maximumFractionDigits: digits });
const yen = (v: number | null) => v === null ? "—" : `¥${fmt(v)}`;
const width = 720; const height = 270; const pad = { left: 56, right: 22, top: 22, bottom: 38 };

export function DashboardChartCard({ title, metric, description, children, note }: { title: string; metric: string; description: string; children: React.ReactNode; note?: string }) {
  return <section className="panel min-w-0 p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-900">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div><MetricHelp metric={metric} compact/></div>{children}{note && <p className="mt-3 text-xs text-slate-500">{note}</p>}<details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer text-emerald-700">グラフの見方</summary><p className="mt-2 leading-5">実績・効率の差を確認し、候補の詳細画面で根拠を深掘りします。指標の分母がない場合は「—」で表示します。</p><Link href="/help/metrics" className="mt-1 inline-block text-emerald-700 underline">指標ガイド</Link></details></section>;
}

export function DashboardCumulativeSalesChart({ points }: { points: CumulativePoint[] }) {
  if (!points.length) return <p className="empty-state mt-4">対象期間の売上実績はありません。</p>;
  const max = Math.max(1, ...points.map((p) => Math.max(p.cumulative, p.target ?? 0, p.forecast ?? 0))); const x = (i: number) => pad.left + i * ((width - pad.left - pad.right) / Math.max(1, points.length - 1)); const y = (v: number) => height - pad.bottom - (v / max) * (height - pad.top - pad.bottom); const line = (values: (number | null)[]) => values.map((v, i) => v === null ? "" : `${i ? "L" : "M"}${x(i).toFixed(1)},${y(v).toFixed(1)}`).filter(Boolean).join(" ");
  const last = points.at(-1); const forecastPath = last?.forecast === null || last?.forecast === undefined ? "" : `M${x(points.length - 1).toFixed(1)},${y(last.cumulative).toFixed(1)} L${(width - pad.right).toFixed(1)},${y(last.forecast).toFixed(1)}`;
  return <div className="mt-4 overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="h-auto min-w-[560px] w-full" role="img" aria-label="累積売上と目標進捗"><path d={line(points.map((p) => p.cumulative))} fill="none" stroke="#047857" strokeWidth="3"/><path d={line(points.map((p) => p.target))} fill="none" stroke="#94a3b8" strokeDasharray="6 5" strokeWidth="2"/><path d={forecastPath} fill="none" stroke="#f59e0b" strokeDasharray="3 5" strokeWidth="2"/><line x1={pad.left} x2={width - pad.right} y1={height - pad.bottom} y2={height - pad.bottom} stroke="#cbd5e1"/>{points.map((p, i) => <g key={p.date}><circle cx={x(i)} cy={y(p.cumulative)} r="3" fill="#047857"><title>{`${p.date}\n日別売上: ${yen(p.sales)}\n累積売上: ${yen(p.cumulative)}\n目標累積: ${yen(p.target)}\n目標との差: ${yen(p.targetGap)}`}</title></circle>{(i === 0 || i === points.length - 1) && <text x={x(i)} y={height - 12} textAnchor={i === 0 ? "start" : "end"} fontSize="11" fill="#64748b">{p.date.slice(5)}</text>}</g>)}</svg><div className="mt-2 flex flex-wrap gap-4 text-xs text-slate-600"><span><i className="mr-1 inline-block h-2 w-5 bg-emerald-700"/>実績累積</span><span><i className="mr-1 inline-block h-0.5 w-5 border-t-2 border-dashed border-slate-400"/>目標ペース</span><span><i className="mr-1 inline-block h-0.5 w-5 border-t-2 border-dashed border-amber-500"/>単純着地予測</span></div></div>;
}

export function DashboardDailySalesAttendanceChart({ points }: { points: Point[] }) {
  if (!points.length) return <p className="empty-state mt-4">対象期間の実績はありません。</p>;
  const max = Math.max(1, ...points.map((p) => p.sales)); const maxA = Math.max(1, ...points.map((p) => p.attendance)); const barW = Math.max(2, (width - pad.left - pad.right) / points.length - 3); const x = (i: number) => pad.left + i * ((width - pad.left - pad.right) / points.length) + 1; const y = (v: number) => height - pad.bottom - (v / max) * (height - pad.top - pad.bottom); const ya = (v: number) => height - pad.bottom - (v / maxA) * (height - pad.top - pad.bottom); const line = points.map((p, i) => `${i ? "L" : "M"}${(x(i) + barW / 2).toFixed(1)},${ya(p.attendance).toFixed(1)}`).join(" ");
  return <div className="mt-4 overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="h-auto min-w-[560px] w-full" role="img" aria-label="日別売上と出勤人数"><path d={line} fill="none" stroke="#2563eb" strokeWidth="2.5"/>{points.map((p, i) => <g key={p.date}><rect x={x(i)} y={y(p.sales)} width={barW} height={height - pad.bottom - y(p.sales)} rx="2" fill="#a7f3d0"><title>{`${p.date}\n売上: ${yen(p.sales)}\n出勤人数: ${fmt(p.attendance)}\n出勤時間: ${fmt(p.minutes / 60, 1)}h\n成約数: ${fmt(p.contracts)}\n売上/出勤人数: ${yen(p.salesPerAttendance)}\n売上/出勤時間: ${yen(p.salesPerHour)}`}</title></rect>{(i === 0 || i === points.length - 1) && <text x={x(i) + barW / 2} y={height - 12} textAnchor="middle" fontSize="11" fill="#64748b">{p.date.slice(5)}</text>}</g>)}</svg><div className="mt-2 flex gap-4 text-xs text-slate-600"><span><i className="mr-1 inline-block size-2 bg-emerald-200"/>日別売上（左軸）</span><span><i className="mr-1 inline-block size-2 rounded-full bg-blue-600"/>出勤人数（右軸）</span></div></div>;
}

const storeMetrics: Record<string, { label: string; unit: string; get: (r: StoreRow) => number | null }> = {
  sales: { label: "売上", unit: "円", get: (r) => r.sales }, reward: { label: "女子報酬", unit: "円", get: (r) => r.reward }, contracts: { label: "成約", unit: "件", get: (r) => r.contracts }, days: { label: "出勤人数", unit: "人", get: (r) => r.days }, minutes: { label: "出勤時間", unit: "分", get: (r) => r.minutes }, salesDay: { label: "売上/出勤日", unit: "円", get: (r) => r.days ? r.sales / r.days : null }, salesHour: { label: "売上/出勤時間", unit: "円", get: (r) => r.minutes ? r.sales / (r.minutes / 60) : null }, contractsDay: { label: "成約/出勤日", unit: "件", get: (r) => r.days ? r.contracts / r.days : null }, regular: { label: "本指名率", unit: "%", get: (r) => r.regularRate === null ? null : r.regularRate * 100 }, pv: { label: "Town PV", unit: "PV", get: (r) => r.pv }, pvDay: { label: "Town PV/出勤日", unit: "PV", get: (r) => r.pvDay }, heaven: { label: "Heaven PAGE_ACCESS", unit: "件", get: (r) => r.heaven }, heavenDay: { label: "Heaven PAGE_ACCESS/出勤日", unit: "件", get: (r) => r.heavenDay },
};
export function DashboardStoreComparisonChart({ rows }: { rows: StoreRow[] }) {
  const [metric, setMetric] = useState("sales"); const definition = storeMetrics[metric]; const values = rows.map(definition.get); const max = Math.max(1, ...values.filter((v): v is number => v !== null));
  return <div className="mt-4"><label className="form-label text-xs">比較指標<select value={metric} onChange={(e) => setMetric(e.target.value)} className="form-input mt-1 w-full"><option value="sales">売上</option>{Object.entries(storeMetrics).filter(([k]) => k !== "sales").map(([k, v]) => <option value={k} key={k}>{v.label}</option>)}</select></label><div className="mt-4 space-y-3">{rows.map((r) => { const v = definition.get(r); return <div key={r.name} className="grid grid-cols-[5rem_1fr_6rem] items-center gap-2 text-xs"><span className="truncate">{r.name}</span><div className="h-5 rounded bg-slate-100">{v !== null && <div className="h-5 rounded bg-emerald-500" style={{ width: `${Math.max(2, (v / max) * 100)}%` }}><span className="sr-only">{fmt(v, 1)}</span></div>}</div><span className="text-right">{v === null ? "—" : definition.unit === "円" ? yen(v) : `${fmt(v, 1)}${definition.unit}`}</span></div>; })}</div><p className="mt-3 text-xs text-slate-500">横棒：{definition.label}（{definition.unit}）。媒体対象外・未存在値は棒を表示しません。</p></div>;
}

export function DashboardCastScatterChart({ rows }: { rows: ScatterRow[] }) {
  const [xKey, setXKey] = useState("attendanceDays"); const [yKey, setYKey] = useState("salesPerDay"); const get = (r: ScatterRow, k: string) => k === "attendanceDays" ? r.attendanceDays : k === "attendanceMinutes" ? r.attendanceMinutes / 60 : k === "salesPerDay" ? r.attendanceDays ? r.sales / r.attendanceDays : null : k === "salesPerHour" ? r.attendanceMinutes ? r.sales / (r.attendanceMinutes / 60) : null : k === "rewardPerHour" ? r.attendanceMinutes ? r.reward / (r.attendanceMinutes / 60) : null : k === "contractsPerDay" ? r.attendanceDays ? null : null : null; const usable = rows.map((r) => ({ r, x: get(r, xKey), y: get(r, yKey) })).filter((p): p is { r: ScatterRow; x: number; y: number } => p.x !== null && p.y !== null); const maxX = Math.max(1, ...usable.map((p) => p.x)); const maxY = Math.max(1, ...usable.map((p) => p.y));
  return <div className="mt-4"><div className="grid gap-2 sm:grid-cols-2"><label className="form-label text-xs">X軸<select value={xKey} onChange={(e) => setXKey(e.target.value)} className="form-input mt-1 w-full"><option value="attendanceDays">出勤日数</option><option value="attendanceMinutes">出勤時間（h）</option></select></label><label className="form-label text-xs">Y軸<select value={yKey} onChange={(e) => setYKey(e.target.value)} className="form-input mt-1 w-full"><option value="salesPerDay">売上/出勤日</option><option value="salesPerHour">売上/出勤時間</option><option value="rewardPerHour">女子報酬/出勤時間</option></select></label></div>{!usable.length ? <p className="empty-state mt-4">CTI分析可能な散布図データがありません。</p> : <svg viewBox={`0 0 ${width} ${height}`} className="mt-4 h-auto w-full" role="img" aria-label="キャスト効率分布"><line x1={pad.left} x2={width - pad.right} y1={height - pad.bottom} y2={height - pad.bottom} stroke="#cbd5e1"/><line x1={pad.left} x2={pad.left} y1={pad.top} y2={height - pad.bottom} stroke="#cbd5e1"/>{usable.map(({ r, x, y }) => { const cx = pad.left + (x / maxX) * (width - pad.left - pad.right); const cy = height - pad.bottom - (y / maxY) * (height - pad.top - pad.bottom); return <a href={`/analytics/casts/discovery?castId=${r.id}`} key={r.id}><circle cx={cx} cy={cy} r={r.lowSample ? 4 : 6} fill={r.lowSample ? "#94a3b8" : "#047857"} opacity={r.lowSample ? .55 : .85}><title>{`${r.name} / ${r.store ?? "—"}\n出勤日数: ${fmt(r.attendanceDays)}\n出勤時間: ${fmt(r.attendanceMinutes / 60, 1)}h\n売上: ${yen(r.sales)}\n売上/出勤日: ${yen(r.attendanceDays ? r.sales / r.attendanceDays : null)}\n判定タグ: ${r.tags.join(" / ") || "—"}`}</title></circle></a>; })}<text x={width / 2} y={height - 5} textAnchor="middle" fontSize="11" fill="#64748b">{xKey === "attendanceDays" ? "出勤日数" : "出勤時間（h）"}</text><text x="12" y={height / 2} transform={`rotate(-90 12 ${height / 2})`} textAnchor="middle" fontSize="11" fill="#64748b">{storeMetrics[yKey === "salesPerDay" ? "salesDay" : yKey === "salesPerHour" ? "salesHour" : "salesHour"].label}</text></svg>}<p className="mt-2 text-xs text-slate-500">緑：標準サンプル、灰：LOW_SAMPLE。点を選ぶとCAST DISCOVERYへ移動します。</p></div>;
}
