import Link from "next/link";
import type { DashboardMetric, ManagementDashboardDto } from "@/lib/analytics/integration/management-dashboard";

const yen = (value: number | null) => value === null ? "—" : `¥${value.toLocaleString("ja-JP", { maximumFractionDigits: 0 })}`;
const number = (value: number | null, digits = 0) => value === null ? "—" : value.toLocaleString("ja-JP", { maximumFractionDigits: digits });
const metricText = (metric: DashboardMetric, unit: "yen" | "count" | "hours" | "percent" = "count") => metric.value === null ? "—" : unit === "yen" ? yen(metric.value) : unit === "hours" ? `${number(metric.value, 1)}時間` : unit === "percent" ? `${number(metric.value * 100, 1)}%` : number(metric.value);
const stateText = (metric: DashboardMetric) => metric.availability === "UNAVAILABLE" ? "対象外" : metric.availability === "MISSING" ? "データ不足" : metric.availability === "UNCOMPUTABLE" ? "算出できません" : metric.availability === "INSUFFICIENT_SAMPLE" ? "サンプル不足" : metric.availability === "ZERO" ? "0件" : "利用可能";
const comparisonText: Record<string, string> = { previousDay: "前日", previousWeekday: "前週同曜日", previousMonthToDate: "前月同期間" };

function MetricCell({ metric, unit = "count" }: { metric: DashboardMetric; unit?: "yen" | "count" | "hours" | "percent" }) {
  return <span className="whitespace-nowrap">{metricText(metric, unit)}<small className="ml-1 text-[10px] text-slate-500">{stateText(metric)} / {metric.confidence}</small></span>;
}

export function ManagementDashboardPage({ data }: { data: ManagementDashboardDto }) {
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <header className="space-y-2"><p className="text-xs font-semibold tracking-[0.16em] text-emerald-700">MANAGEMENT DASHBOARD</p><h1 className="text-2xl font-semibold text-slate-900">全店舗ダッシュボード</h1><p className="text-sm text-slate-600">店舗ごとの母数・効率・実績・データ状態を比較し、優先して確認する店舗を判断します。</p><p className="text-xs text-slate-500">対象期間：{data.meta.from}〜{data.meta.to} / 比較：{comparisonText[data.meta.comparison] ?? data.meta.comparison} / 最終確定：{data.meta.latestConfirmedDate ?? "—"}</p></header>
    <form className="panel grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4" method="get"><label className="form-label">開始日<input className="form-input mt-1" type="date" name="from" max={data.meta.to} defaultValue={data.meta.from} /></label><label className="form-label">終了日<input className="form-input mt-1" type="date" name="to" max={new Date().toISOString().slice(0, 10)} defaultValue={data.meta.to} /></label><label className="form-label">比較<select className="form-input mt-1" name="comparison" defaultValue={data.meta.comparison}><option value="previousWeekday">前週同曜日</option><option value="previousMonthToDate">前月同期間</option><option value="previousDay">前日</option></select></label><label className="form-label">店舗<select className="form-input mt-1" name="stores" defaultValue={data.meta.selectedStoreCodes.length === 3 ? "ALL" : data.meta.selectedStoreCodes[0]}><option value="ALL">全体</option><option value="KASUKABE">春日部</option><option value="KOSHIGAYA">越谷</option><option value="NODA">野田</option></select></label><button className="primary-button sm:col-span-2 lg:col-span-4" type="submit">表示</button></form>
    <section className={`rounded-xl border p-4 text-sm ${data.dataHealth.status === "要対応" ? "border-red-200 bg-red-50 text-red-900" : data.dataHealth.status === "注意" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-emerald-200 bg-emerald-50 text-emerald-900"}`} aria-live="polite"><strong>データ状態：{data.dataHealth.status}</strong><span className="ml-3">未確定 {data.dataHealth.pending}件 / FAILED {data.dataHealth.failed}件 / OPENエラー {data.dataHealth.openErrors}件</span><Link className="ml-3 underline" href={data.dataHealth.detailUrl}>DATA HEALTHを確認</Link></section>
    <section aria-labelledby="management-summary"><h2 id="management-summary" className="mb-3 text-lg font-semibold">全体サマリー</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[["全体売上", <MetricCell key="sales" metric={data.summary.sales} unit="yen" />], ["月目標", <MetricCell key="goal" metric={data.summary.goal} unit="yen" />], ["目標達成率", <MetricCell key="rate" metric={data.summary.achievementRate} unit="percent" />], ["着地予測", <MetricCell key="projected" metric={data.summary.projectedSales} unit="yen" />], ["売上／時間", <MetricCell key="hour" metric={data.summary.salesPerHour} unit="yen" />], ["データ状態", data.summary.dataHealthStatus]].map(([label, value]) => <article className="panel p-4" key={String(label)}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold text-slate-900">{value}</p></article>)}</div></section>
    <section aria-labelledby="priority-title"><h2 id="priority-title" className="mb-3 text-lg font-semibold">店舗別要確認順</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.priorities.map((item) => <article className="panel p-4" key={item.storeId}><div className="flex items-center justify-between gap-2"><h3 className="font-semibold">{item.storeName}</h3><span className="badge">{item.title}</span></div><p className="mt-2 text-sm text-slate-700">現在の状況：{item.situation}</p><p className="mt-2 text-xs text-slate-500">判断根拠：{item.evidence.join(" / ")}</p><Link className="mt-3 inline-block text-sm text-emerald-700 underline" href={item.detailUrl}>{item.recommendedDestination}を確認</Link></article>)}</div></section>
    <section aria-labelledby="store-comparison-title"><h2 id="store-comparison-title" className="mb-3 text-lg font-semibold">店舗サマリー比較</h2><div className="panel overflow-x-auto p-4"><table className="min-w-[980px] w-full"><caption className="sr-only">店舗別の母数・効率・実績比較</caption><thead><tr><th scope="col">店舗</th><th scope="col">Sample</th><th scope="col">売上／時間</th><th scope="col">売上</th><th scope="col">予約</th><th scope="col">出勤時間</th><th scope="col">比較結果</th><th scope="col">詳細</th></tr></thead><tbody>{data.stores.map((store) => <tr key={store.storeId}><th scope="row" className="text-left">{store.storeName}</th><td><MetricCell metric={store.sample.businessDays} unit="count" /><br /><MetricCell metric={store.sample.castCount} unit="count" /></td><td><MetricCell metric={store.efficiency.salesPerHour} unit="yen" /></td><td><MetricCell metric={store.volume.sales} unit="yen" /></td><td><MetricCell metric={store.volume.reservations} /></td><td><MetricCell metric={store.volume.workHours} unit="hours" /></td><td>{store.comparison[0] ? `${comparisonText[store.comparison[0].baselineKind] ?? store.comparison[0].baselineKind} / ${store.comparison[0].differenceRate === null ? "—" : `${number(store.comparison[0].differenceRate * 100, 1)}%`}` : "—"}</td><td><Link className="text-emerald-700 underline" href={store.detailUrls.store}>店舗分析</Link></td></tr>)}</tbody></table></div></section>
    <section aria-labelledby="charts-title" className="grid gap-6 xl:grid-cols-3"><h2 id="charts-title" className="sr-only">店舗比較グラフ</h2><ChartTable title="店舗別売上" unit="yen" rows={data.charts.salesByStore} /><ChartTable title="店舗別売上／時間" unit="yen" rows={data.charts.salesPerHourByStore} /><div className="panel p-5"><h2 className="font-semibold">店舗別売上推移</h2><p className="mt-1 text-xs text-slate-500">日別CTI売上。欠測日は線で補完しません。</p><div className="mt-4 space-y-3">{data.charts.salesTrend.slice(-10).map((day) => <div key={day.date}><p className="text-xs text-slate-500">{day.date}</p><div className="grid grid-cols-3 gap-2 text-xs">{day.stores.map((store) => <span key={store.storeId}>{store.storeName}：{store.value === null ? "—" : yen(store.value)}</span>)}</div></div>)}</div></div></section>
    <section aria-labelledby="media-title"><h2 id="media-title" className="mb-3 text-lg font-semibold">媒体対象範囲</h2><div className="grid gap-4 md:grid-cols-3">{data.media.map((item) => <article className="panel p-4" key={item.storeId}><h3 className="font-semibold">{item.storeName}</h3><p className="mt-3 text-sm">Town店舗PV：<MetricCell metric={item.townPv} /></p><p className="mt-2 text-sm">Town店舗UU：<MetricCell metric={item.townUu} /></p><p className="mt-2 text-sm">Heaven店舗アクセス：<MetricCell metric={item.heavenAccess} /></p><p className="mt-2 text-sm">Heaven日記投稿数：<MetricCell metric={item.heavenDiaryPosts} /></p></article>)}</div></section>
    <section aria-labelledby="next-title"><h2 id="next-title" className="mb-3 text-lg font-semibold">次に見る画面</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.quickLinks.map((link) => <Link className="panel p-4 text-sm hover:border-emerald-300" href={link.href} key={link.href}><span className="font-semibold text-emerald-700">{link.label}</span><span className="mt-1 block text-xs text-slate-500">{link.description}</span></Link>)}</div></section>
    <p className="text-xs text-slate-500">{data.notes.join(" ")}</p>
  </div>;
}

function ChartTable({ title, unit, rows }: { title: string; unit: "yen" | "count"; rows: Array<{ storeId: string; storeName: string; value: number | null; availability: string }> }) {
  return <article className="panel p-5"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-xs text-slate-500">期間内の比較値。利用可能な値のみ表示します。</p><div className="mt-4 space-y-3">{rows.map((row) => <div className="flex items-center justify-between gap-3 text-sm" key={row.storeId}><span>{row.storeName}</span><span>{row.value === null ? row.availability === "MISSING" ? "データ不足" : "対象外" : unit === "yen" ? yen(row.value) : number(row.value)}</span></div>)}</div></article>;
}
