"use client";

import type { DashboardChartDto, DashboardRelationshipChartDto, DashboardStoryCardDto, RelationshipDirection } from "@/lib/analytics/integration/management-dashboard";

const COLORS: Record<string, string> = { sales: "#047857", contracts: "#2563eb", attendance: "#d97706", workHours: "#7c3aed", townPv: "#0891b2", townUu: "#0f766e", pageAccess: "#db2777", diaryPosts: "#9333ea", nominations: "#b45309" };
const directionLabel: Record<RelationshipDirection, string> = { same: "同方向", opposite: "逆方向", unchanged: "変化なし", insufficient_data: "判定不能" };
function linePath(values: Array<number | null>, x: (index: number) => number, y: (value: number) => number) { let path = ""; values.forEach((value, index) => { if (value === null) return; path += `${index > 0 && values[index - 1] !== null ? "L" : "M"}${x(index).toFixed(1)},${y(value).toFixed(1)} `; }); return path.trim(); }
function axisValue(value: number, type: DashboardRelationshipChartDto["leftAxis"]["valueType"]) { return type === "currency" ? `¥${Math.round(value).toLocaleString("ja-JP")}` : type === "hours" ? `${value.toLocaleString("ja-JP", { maximumFractionDigits: 1 })}時間` : value.toLocaleString("ja-JP"); }
function ticks(max: number) { return [0, 0.333, 0.666, 1].map((ratio) => ({ ratio, value: max * ratio })); }
function xTickIndices(length: number) { if (length <= 1) return [0]; const count = Math.min(7, length); return Array.from({ length: count }, (_, index) => Math.round(index * (length - 1) / (count - 1))); }

function RelationshipChart({ chart }: { chart: DashboardRelationshipChartDto }) {
  const width = 820; const height = 300; const padding = { left: 74, right: 74, top: 34, bottom: 44 }; const plotWidth = width - padding.left - padding.right; const plotHeight = height - padding.top - padding.bottom;
  const leftValues = chart.values.map((v) => v.leftValue); const rightValues = chart.values.map((v) => v.rightValue); const leftMax = Math.max(1, ...leftValues.filter((v): v is number => v !== null)); const rightMax = Math.max(1, ...rightValues.filter((v): v is number => v !== null)); const x = (i: number) => padding.left + i * plotWidth / Math.max(1, chart.values.length - 1); const leftY = (v: number) => height - padding.bottom - v / leftMax * plotHeight; const rightY = (v: number) => height - padding.bottom - v / rightMax * plotHeight; const barWidth = Math.max(5, plotWidth / Math.max(1, chart.values.length) * 0.62); const leftColor = COLORS[chart.leftAxis.colorToken] ?? "#047857"; const rightColor = COLORS[chart.rightAxis.colorToken] ?? "#2563eb";
  const leftTicks = ticks(leftMax); const dateIndices = xTickIndices(chart.xAxis.labels.length);
  return <div className="min-w-0 overflow-hidden rounded-lg border border-slate-200 bg-white p-3"><div className="mb-2 flex flex-wrap gap-3 text-xs"><span style={{ color: leftColor }}>■ 左軸：{chart.leftAxis.label}（{chart.leftAxis.unitLabel}・棒）</span><span style={{ color: rightColor }}>━ 右軸：{chart.rightAxis.label}（{chart.rightAxis.unitLabel}・線）</span></div><svg viewBox={`0 0 ${width} ${height}`} className="h-auto w-full" role="img" aria-label={`${chart.title}。左軸${chart.leftAxis.label}、右軸${chart.rightAxis.label}`}>
    {leftTicks.map((tick) => <g key={`grid-${tick.ratio}`}><line x1={padding.left} x2={width - padding.right} y1={height - padding.bottom - tick.ratio * plotHeight} y2={height - padding.bottom - tick.ratio * plotHeight} stroke="#e2e8f0" strokeWidth="1" /><text x={padding.left - 8} y={height - padding.bottom - tick.ratio * plotHeight + 4} textAnchor="end" fontSize="10" fill={leftColor}>{axisValue(tick.value, chart.leftAxis.valueType)}</text><text x={width - padding.right + 8} y={height - padding.bottom - tick.ratio * plotHeight + 4} fontSize="10" fill={rightColor}>{axisValue(rightMax * tick.ratio, chart.rightAxis.valueType)}</text></g>)}
    <path d={linePath(rightValues, x, rightY)} fill="none" stroke={rightColor} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />{chart.values.map((value, i) => value.leftValue === null ? null : <rect key={value.date} x={x(i) - barWidth / 2} y={leftY(value.leftValue)} width={barWidth} height={height - padding.bottom - leftY(value.leftValue)} fill={leftColor} opacity="0.72"><title>{`${value.date}｜${chart.scope.scopeLabel}\n${chart.leftAxis.label}: ${value.leftFormattedValue}\n${chart.rightAxis.label}: ${value.rightFormattedValue}\n前日差: ${value.previousDayLeftDifference ?? "—"} / ${value.previousDayRightDifference ?? "—"}\n方向: ${directionLabel[value.previousDayDirection]}`}</title></rect>)}
    <text x={padding.left} y={padding.top - 12} fontSize="11" fill={leftColor}>{chart.leftAxis.label}（{chart.leftAxis.unitLabel}）</text><text x={width - padding.right} y={padding.top - 12} textAnchor="end" fontSize="11" fill={rightColor}>{chart.rightAxis.label}（{chart.rightAxis.unitLabel}）</text>{dateIndices.map((index) => <text key={`date-${index}`} x={x(index)} y={height - 12} textAnchor="middle" fontSize="10" fill="#64748b">{chart.xAxis.labels[index]?.slice(5).replace("-", "/")}</text>)}
  </svg></div>;
}

function SalesTrendChart({ chart }: { chart: DashboardChartDto }) {
  const values = chart.series[0]?.values ?? []; const max = Math.max(1, ...values.map((value) => value.value ?? 0)); const width = 820; const height = 250; const pad = { left: 70, right: 18, top: 18, bottom: 30 }; const plotWidth = width - pad.left - pad.right; const plotHeight = height - pad.top - pad.bottom; const x = (i: number) => pad.left + i * plotWidth / Math.max(1, values.length - 1); const dateIndices = xTickIndices(values.length); return <div className="rounded-lg border border-slate-200 bg-white p-3"><div className="mb-2 text-xs text-emerald-700">売上（円・棒）</div><svg viewBox={`0 0 ${width} ${height}`} className="h-auto w-full" role="img" aria-label={`${chart.title} ${chart.series[0]?.storeName ?? ""}`}>
    {ticks(max).map((tick) => <g key={tick.ratio}><line x1={pad.left} x2={width - pad.right} y1={height - pad.bottom - tick.ratio * plotHeight} y2={height - pad.bottom - tick.ratio * plotHeight} stroke="#e2e8f0" /><text x={pad.left - 8} y={height - pad.bottom - tick.ratio * plotHeight + 4} textAnchor="end" fontSize="10" fill="#047857">¥{Math.round(tick.value).toLocaleString("ja-JP")}</text></g>)}
    {values.map((value, i) => value.value === null ? null : <rect key={value.date} x={x(i) - Math.max(3, plotWidth / Math.max(1, values.length) * 0.3)} y={height - pad.bottom - value.value / max * plotHeight} width={Math.max(4, plotWidth / Math.max(1, values.length) * 0.6)} height={value.value / max * plotHeight} fill="#047857" opacity=".75"><title>{`${value.date}｜${chart.series[0]?.storeName ?? ""}\n売上: ${value.formattedValue}`}</title></rect>)}{dateIndices.map((index) => <text key={`date-${index}`} x={x(index)} y={height - 8} textAnchor="middle" fontSize="10" fill="#64748b">{values[index]?.date.slice(5).replace("-", "/")}</text>)}
  </svg></div>;
}

function StoryCard({ card }: { card: DashboardStoryCardDto }) {
  const health = card.dataHealth.state === "unavailable" ? "利用できません" : card.dataHealth.state === "partial" ? "一部欠測" : card.dataHealth.state === "not_applicable" ? "対象外" : "利用可能";
  const showHealth = card.dataHealth.state === "partial" || card.dataHealth.state === "unavailable" || card.dataHealth.state === "not_applicable";
  return <article className="panel min-w-0 overflow-hidden p-5" aria-labelledby={`story-card-${card.cardId}`}><header className="flex flex-wrap items-start justify-between gap-3"><div><h3 id={`story-card-${card.cardId}`} className="text-base font-semibold">{card.title}</h3>{card.description && <p className="mt-1 text-xs text-slate-500">{card.description}</p>}</div>{showHealth && <span className={`rounded-full px-2 py-1 text-[11px] ${card.dataHealth.state === "partial" ? "bg-amber-50 text-amber-800" : "bg-slate-100 text-slate-600"}`}>データ状態：{health}</span>}</header><div className="mt-3 grid gap-3 sm:grid-cols-3">{card.headlineMetrics.slice(0, 3).map((metric) => <div key={metric.metricId} className="rounded-md bg-slate-50 px-3 py-2"><p className="text-[11px] text-slate-500">{metric.label}</p><p className="mt-1 text-sm font-semibold">{metric.formattedValue}</p>{metric.comparisonText && <p className="mt-1 text-xs text-slate-600">{metric.comparisonText}</p>}</div>)}</div>{card.trendCharts?.map((chart) => <div className="mt-4" key={chart.chartId}><SalesTrendChart chart={chart} /></div>)}<div className={`mt-4 grid gap-4 ${card.charts.length > 1 ? "md:grid-cols-2" : "grid-cols-1"}`}>{card.charts.map((chart) => <RelationshipChart chart={chart} key={chart.chartId} />)}</div>{card.relationshipSummary && <div className="mt-3 text-xs text-slate-600"><span className="font-medium">{card.relationshipSummary.primaryText}</span>{card.relationshipSummary.secondaryText && <span className="ml-3 font-medium">{card.relationshipSummary.secondaryText}</span>}</div>}<footer className="mt-3 space-y-1 text-xs text-slate-500">{card.notes.map((note) => <p key={note}>{note}</p>)}<p>最新反映日：{card.dataHealth.latestDate ?? "—"}{card.dataHealth.missingDates.length ? ` / ${card.dataHealth.missingDates.length}日未取得` : ""}</p><nav aria-label={`${card.title}の詳細`} className="flex flex-wrap gap-3">{card.navigation.map((link) => <a className="text-emerald-700 underline" href={link.href} key={link.href}>{link.label}</a>)}</nav></footer></article>;
}

export function ManagementDashboardCharts({ storyCards }: { storyCards: DashboardStoryCardDto[] }) {
  const groups: Array<{ id: string; title: string; description: string; cards: DashboardStoryCardDto[]; columns: string }> = [
    { id: "sales_trend", title: "STORY 1｜全体・店舗別売上推移", description: "売上だけの日別推移を店舗ごとに確認します。", cards: storyCards.filter((card) => card.storyId === "sales_trend"), columns: "grid-cols-1 md:grid-cols-2" },
    { id: "sales_outcome", title: "STORY 2｜売上と成約数", description: "売上と成約数の同日変化を観察します。因果関係は断定しません。", cards: storyCards.filter((card) => card.storyId === "sales_outcome"), columns: "grid-cols-1 md:grid-cols-2" },
    { id: "sales_operations", title: "STORY 3｜全体の売上と稼働", description: "全体の売上と出勤人数・時間を確認します。", cards: storyCards.filter((card) => card.storyId === "sales_operations"), columns: "grid-cols-1" },
    { id: "town_performance", title: "STORY 4-5｜Town集客", description: "春日部・越谷のTown集客を店舗別に確認します。", cards: storyCards.filter((card) => card.storyId === "town_performance" && !card.title.includes("Town・Heaven")), columns: "grid-cols-1" },
    { id: "heaven_performance", title: "STORY 6｜春日部Heaven活動・閲覧・成果", description: "Heavenの閲覧・投稿・活動指標を確認します。", cards: storyCards.filter((card) => card.storyId === "heaven_performance"), columns: "grid-cols-1" },
    { id: "media_cross", title: "STORY 7｜春日部Town・Heaven媒体推移", description: "Town PVとHeaven PAGE_ACCESSを絶対値で確認します。定義は同一ではなく、因果関係は断定しません。", cards: storyCards.filter((card) => card.title.includes("Town・Heaven")), columns: "grid-cols-1" },
    { id: "sales_nomination", title: "STORY 8｜売上と本指名", description: "売上と本指名数を確認します。本指名率は補助表示です。", cards: storyCards.filter((card) => card.storyId === "sales_nomination"), columns: "grid-cols-1 md:grid-cols-2" },
  ];
  return <section aria-labelledby="story-title" className="space-y-8"><div><h2 id="story-title" className="text-lg font-semibold">売上構造ストーリー</h2><p className="mt-1 text-sm text-slate-500">関連する指標を同じ営業日軸で読みます。数字の同時変化を示す参考情報であり、因果関係や統計的相関を示しません。</p></div>{groups.map((group) => <section key={group.id} aria-labelledby={`story-${group.id}`}><h3 id={`story-${group.id}`} className="text-lg font-semibold"><span className="mr-2 text-emerald-700">{group.title.split("｜")[0]}</span><span>{group.title.split("｜")[1]}</span></h3><p className="mt-1 text-sm text-slate-500">{group.description}</p><div className={`mt-4 grid gap-5 ${group.columns}`}>{group.cards.map((card) => <StoryCard card={card} key={card.cardId} />)}</div></section>)}</section>;
}
