"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { METRIC_CATEGORIES, type MetricDefinition } from "@/lib/analytics/metric-definitions";

export function MetricGlossaryExplorer({ definitions }: { definitions: MetricDefinition[] }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("ALL");
  const filtered = useMemo(() => definitions.filter((m) => (category === "ALL" || m.category === category) && `${m.label} ${m.key} ${m.meaning}`.toLowerCase().includes(query.toLowerCase())), [definitions, category, query]);
  const common = definitions.filter((m) => ["sales", "contracts", "attendanceDays", "townPv", "page_access", "salesPerDay", "regularRate", "achievementRate"].includes(m.key)); const caution = definitions.filter((m) => ["townUu", "townHeavenReference", "correlation", "LOW_SAMPLE", "landingForecast", "regularRate"].includes(m.key));
  return <div><div className="panel mb-6 grid gap-3 p-4 sm:grid-cols-[1fr_14rem]"><label className="form-label">キーワード検索<input className="form-input mt-1 w-full" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="例：成約、PV、予測"/></label><label className="form-label">カテゴリ<select className="form-input mt-1 w-full" value={category} onChange={(e) => setCategory(e.target.value)}><option value="ALL">すべて</option>{METRIC_CATEGORIES.map((x) => <option key={x} value={x}>{x}</option>)}</select></label></div><div className="mb-6 grid gap-4 md:grid-cols-2"><section className="panel p-5"><h2 className="font-semibold text-slate-900">よく使う指標</h2><div className="mt-3 flex flex-wrap gap-2">{common.map((m) => <Link key={m.key} href={`#${m.key}`} className="rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-800">{m.label}</Link>)}</div></section><section className="panel p-5"><h2 className="font-semibold text-slate-900">判断時に注意が必要な指標</h2><div className="mt-3 flex flex-wrap gap-2">{caution.map((m) => <Link key={m.key} href={`#${m.key}`} className="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-800">{m.label}</Link>)}</div></section></div><p className="mb-3 text-sm text-slate-500">{filtered.length}件表示。内部キーは実装確認用です。</p><div className="grid gap-4 md:grid-cols-2">{filtered.map((m) => <article id={m.key} className="panel scroll-mt-6 p-5" key={m.key}><div className="flex items-start justify-between gap-3"><h2 className="font-semibold text-slate-900">{m.label}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] text-slate-500">{m.category}</span></div><p className="mt-1 font-mono text-[11px] text-slate-400">{m.key}</p><p className="mt-2 text-sm text-slate-700"><strong>意味：</strong>{m.meaning}</p><p className="mt-1 text-sm text-slate-700"><strong>見るポイント：</strong>{m.whatToSee}</p>{m.formula && <p className="mt-1 text-sm text-slate-700"><strong>計算式：</strong><span className="font-mono">{m.formula}</span>{m.unit && `（${m.unit}）`}</p>}<p className="mt-2 text-xs text-amber-700"><strong>注意：</strong>{m.caution}</p><div className="mt-3 flex flex-wrap gap-2">{(m.pages ?? []).slice(0, 4).map((p) => <Link key={p} href={p} className="text-xs text-emerald-700 underline">使用画面</Link>)}{m.related?.map((r) => <Link key={r} href={`#${r}`} className="text-xs text-slate-600 underline">関連指標</Link>)}</div></article>)}{!filtered.length && <p className="empty-state">該当する指標がありません。</p>}</div></div>;
}
