import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { requireUser } from "@/lib/auth";
import { getDataHealth, parseHealthDate, type HealthMedia, type HealthScope } from "@/lib/analytics/data-health";

type Query = { period?: string; from?: string; to?: string; scope?: string; media?: string };
const yen = (value: number | null) => value === null ? "—" : `¥${value.toLocaleString("ja-JP")}`;
const n = (value: number | null) => value === null ? "—" : value.toLocaleString("ja-JP");
const safeScope = (value?: string): HealthScope => value === "KASUKABE" || value === "KOSHIGAYA" || value === "NODA" ? value : "ALL";
const safeMedia = (value?: string): HealthMedia => value === "CTI" || value === "TOWN" || value === "HEAVEN" ? value : "ALL";

function rangeFromQuery(query: Query) {
  const now = new Date(); const currentFrom = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)); const currentTo = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 0));
  if (query.period === "previous") { const from = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1)); const to = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 0)); return { from, to }; }
  if (query.period === "custom") return { from: parseHealthDate(query.from, currentFrom), to: parseHealthDate(query.to, currentTo) };
  return { from: currentFrom, to: currentTo };
}

function statusClass(state: string) { return state === "正常" ? "bg-emerald-50 text-emerald-800" : state === "注意" ? "bg-amber-50 text-amber-800" : "bg-red-50 text-red-800"; }
function batchLink(batch: { media: string; id: string }) { return batch.media === "CTI" ? `/imports/${batch.id}` : batch.media === "TOWN" ? `/imports/town/${batch.id}` : `/imports/heaven/${batch.id}`; }

export default async function DataHealthPage({ searchParams }: { searchParams: Promise<Query> }) {
  await requireUser();
  const query = await searchParams; const range = rangeFromQuery(query); const scope = safeScope(query.scope); const media = safeMedia(query.media); const health = await getDataHealth({ from: range.from, to: range.to, scope, media });
  return <>
    <PageHeader eyebrow="DATA HEALTH" title="データ健全性" description="分析・着地予測・目標達成率を確認する前に、取込状態と未反映影響を読み取り専用で点検します。" />
    <form className="panel mb-5 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5">
      <label className="form-label">期間<select name="period" defaultValue={query.period ?? "current"} className="form-input mt-1"><option value="current">当月</option><option value="previous">前月</option><option value="custom">任意期間</option></select></label>
      <label className="form-label">開始日<input className="form-input mt-1" type="date" name="from" defaultValue={health.range.from}/></label>
      <label className="form-label">終了日<input className="form-input mt-1" type="date" name="to" defaultValue={health.range.to}/></label>
      <label className="form-label">店舗<select name="scope" defaultValue={scope} className="form-input mt-1"><option value="ALL">全体</option><option value="KASUKABE">春日部</option><option value="KOSHIGAYA">越谷</option><option value="NODA">野田</option></select></label>
      <label className="form-label">媒体<select name="media" defaultValue={media} className="form-input mt-1"><option value="ALL">すべて</option><option value="CTI">CTI</option><option value="TOWN">Town</option><option value="HEAVEN">Heaven</option></select></label>
      <button className="primary-button sm:col-span-2 xl:col-span-5">表示</button>
    </form>
    <div className="mb-5 rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-950">媒体対象範囲：CTI（春日部・越谷・野田）／Town（春日部・越谷）／Heaven（春日部のみ）。対象外店舗は欠損扱いしません。</div>
    <section className="mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <div className={`panel p-5 ${statusClass(health.state)}`}><p className="text-sm">データ健全性状態</p><p className="mt-2 text-3xl font-semibold">{health.state}</p><p className="mt-2 text-xs">品質スコア：{health.score}/100（運用確認用）</p></div>
      {[['未確定Batch', health.summary.pendingBatches], ['FAILED', health.summary.failedBatches], ['OPEN未解決・警告', health.summary.unresolved + health.summary.warnings], ['推定売上影響額', yen(health.summary.impactAmount)]].map(([label, value]) => <div className="panel p-5" key={label as string}><p className="text-sm text-slate-500">{label as string}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{typeof value === "number" ? n(value) : value}</p></div>)}
    </section>
    <section className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900"><strong>最優先対応：</strong>{health.summary.priority}。{health.summary.impactAmount > 0 ? ` 未反映売上の影響見込みは${yen(health.summary.impactAmount)}です。HOMEの確定済み売上には加算していません。` : "重大な未反映売上は確認されていません。"}</section>
    <section className="mb-5 grid gap-4 lg:grid-cols-3">{health.mediaCards.map((card) => <div className="panel p-5" key={card.media}><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-900">{card.media}</h2><span className={`rounded-full px-2 py-1 text-xs ${card.failed || card.pending ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-800"}`}>{card.failed || card.pending ? "注意" : "正常"}</span></div><p className="mt-2 text-sm text-slate-500">対象：{card.target}</p><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><dt className="text-slate-500">最新反映日</dt><dd>{card.latest ?? "—"}</dd><dt className="text-slate-500">完了Batch</dt><dd>{card.completed}</dd><dt className="text-slate-500">未確定</dt><dd>{card.pending}</dd><dt className="text-slate-500">WAITING</dt><dd>{card.waiting}</dd><dt className="text-slate-500">FAILED</dt><dd>{card.failed}</dd><dt className="text-slate-500">OPEN WARNING</dt><dd>{card.openWarnings}</dd><dt className="text-slate-500">OPEN ERROR</dt><dd>{card.openErrors}</dd><dt className="text-slate-500">未反映行見込み</dt><dd>{n(card.pendingRows)}</dd>{card.media === "CTI" && <><dt className="text-slate-500">売上影響見込み</dt><dd>{yen(card.impactAmount)}</dd></>}</dl><Link href={card.media === "CTI" ? "/imports" : card.media === "TOWN" ? "/imports/town" : "/imports/heaven"} className="mt-4 inline-block text-sm text-emerald-700 underline">詳細を見る →</Link></div>)}</section>
    <section className="panel mb-5 overflow-hidden p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-900">未確定Batch・異常一覧</h2><span className="text-sm text-slate-500">読み取り専用</span></div><div className="table-wrap mt-4"><table><thead><tr><th>優先度</th><th>媒体</th><th>対象日</th><th>店舗</th><th>ファイル</th><th>status</th><th>Batch ID</th><th>保存見込み</th><th>影響額</th><th>対応</th></tr></thead><tbody>{health.batches.filter((b) => ["PREVIEW_READY", "WAITING_FOR_CAST_LINK", "COMPLETED_WITH_WARNINGS", "FAILED"].includes(b.status)).map((b) => <tr key={b.id}><td><span className={`rounded-full px-2 py-1 text-xs ${b.priority === "最優先" ? "bg-red-50 text-red-800" : "bg-amber-50 text-amber-800"}`}>{b.priority}</span></td><td>{b.media}</td><td>{b.targetFrom === b.targetTo ? b.targetFrom : `${b.targetFrom}〜${b.targetTo}`}</td><td>{b.store}</td><td className="max-w-[14rem] truncate">{b.filename}</td><td>{b.status}</td><td className="font-mono text-xs">{b.id}</td><td>{b.saveRows === null ? "算出不可" : `${n(b.saveRows)}行`}</td><td>{yen(b.impactAmount)}</td><td><Link href={batchLink(b)} className="text-emerald-700 underline">詳細</Link><p className="mt-1 text-xs text-slate-500">{b.recommendation}</p></td></tr>)}</tbody></table>{!health.batches.some((b) => ["PREVIEW_READY", "WAITING_FOR_CAST_LINK", "COMPLETED_WITH_WARNINGS", "FAILED"].includes(b.status)) && <p className="empty-state">未確定・異常Batchはありません。</p>}</div></section>
    <section className="panel mb-5 p-5"><h2 className="text-lg font-semibold text-slate-900">品質スコア内訳</h2><p className="mt-2 text-sm text-slate-500">基礎点100点から、未確定-8/件（最大32）、FAILED-10/件（最大30）、WAITING-3/件（最大15）、OPEN ERROR-2/件（最大20）、OPEN WARNING-0.2/件（最大10）、CTI日付欠損-5/日（最大25）を減点。0点未満にはしません。</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm md:grid-cols-6">{Object.entries(health.scoreBreakdown).map(([label, value]) => <div className="rounded-xl bg-slate-50 p-3" key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div></section>
    <section className="panel mb-5 overflow-hidden p-5"><h2 className="text-lg font-semibold text-slate-900">日付カバレッジ</h2><div className="table-wrap mt-4"><table><thead><tr><th>日付</th><th>CTI</th><th>Town</th><th>Heaven</th></tr></thead><tbody>{health.coverage.map((row) => <tr key={row.date}><td>{row.date}</td><td>{row.cti}</td><td>{row.town}</td><td>{row.heaven}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-slate-500">Heavenは累積CSV運用のため、個別日CSVがないこと自体は欠損と判定しません。</p></section>
    <section className="mb-5 grid gap-5 lg:grid-cols-2"><div className="panel p-5"><h2 className="text-lg font-semibold text-slate-900">Alias・未解決状況</h2><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><dt>OPEN UNMATCHED_CAST</dt><dd>{n(health.aliases.openUnmatched)}</dd><dt>AMBIGUOUS</dt><dd>{n(health.aliases.ambiguous)}</dd><dt>在籍期間外</dt><dd>{n(health.aliases.outside)}</dd><dt>ID_NO_SOURCE_URL</dt><dd>{n(health.aliases.idNoSourceUrl)}</dd><dt>修正版候補</dt><dd>{n(health.aliases.revision)}</dd></dl><p className="mt-3 text-xs text-slate-500">ID不明・判断不能は保留可能、候補ありの未解決は要対応として扱います。</p></div><div className="panel p-5"><h2 className="text-lg font-semibold text-slate-900">最新反映状況</h2><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><dt>CTI</dt><dd>{health.latest.cti ?? "—"}</dd><dt>Town女子</dt><dd>{health.latest.townCast ?? "—"}</dd><dt>Town URL</dt><dd>{health.latest.townUrl ?? "—"}</dd><dt>Town LP</dt><dd>{health.latest.townLanding ?? "—"}</dd><dt>Heaven Shop</dt><dd>{health.latest.heavenShop ?? "—"}</dd><dt>Heaven女子</dt><dd>{health.latest.heavenCast ?? "—"}</dd></dl></div></section>
    <section className="panel mb-5 overflow-hidden p-5"><h2 className="text-lg font-semibold text-slate-900">データ整合性チェック</h2><div className="table-wrap mt-4"><table><thead><tr><th>項目</th><th>状態</th><th>内容</th></tr></thead><tbody>{health.integrity.map((item) => <tr key={item.label}><td>{item.label}</td><td><span className={`rounded-full px-2 py-1 text-xs ${statusClass(item.state)}`}>{item.state}</span></td><td>{item.detail}</td></tr>)}</tbody></table></div></section>
    <p className="text-xs text-slate-500">DATA HEALTHは取込状態を確認する運用指標です。データの正しさを保証するものではなく、確定・再解析・Alias作成などの操作は行いません。</p>
  </>;
}
