import type { AnalyticsSummaryDto } from "@/lib/analytics/integration/dto";
import type { MetricFormat, UiAvailability, UiConfidence } from "./types";

export type PerformanceCastDto = { cast: { id: string; displayName: string; primaryStoreId?: string | null } | null; castId: string; summary: AnalyticsSummaryDto };
export type PerformanceResponseDto = { period: { from: string; to: string }; stores: Array<{ id: string; code: string; name: string; shortName: string }>; storeSummaries?: Array<{ store: { id: string; code: string; name: string; shortName: string }; summary: AnalyticsSummaryDto }>; overall?: AnalyticsSummaryDto; casts: PerformanceCastDto[] };
export type PerformanceMetricViewModel = { key: string; label: string; value: number | null; format: MetricFormat; availability: UiAvailability; description: string };
export type PerformanceCastViewModel = PerformanceCastDto & { name: string; metrics: PerformanceMetricViewModel[]; confidence: UiConfidence; growthLabel: string; actionLevel: "ACTION" | "REFERENCE" | "NONE"; availability: UiAvailability };

const labels: Record<string, { label: string; format: MetricFormat; description: string }> = {
  sales: { label: "売上", format: "currency", description: "対象期間の売上合計" }, castReward: { label: "女子報酬", format: "currency", description: "対象期間の女子報酬合計" }, reservations: { label: "予約", format: "count", description: "対象期間の予約数" }, services: { label: "接客", format: "count", description: "対象期間の接客数" }, regularNominations: { label: "本指名", format: "count", description: "対象期間の本指名数" }, attendancePeople: { label: "出勤人数", format: "people", description: "延べ出勤人数" }, attendanceMinutes: { label: "出勤時間", format: "hours", description: "対象期間の総出勤時間" }, townPv: { label: "Town PV", format: "pv", description: "Townの閲覧数。予約経路とは結び付きません" }, townUu: { label: "Town UU", format: "uu", description: "Townのユニーク閲覧者数" }, heavenAccess: { label: "Heavenアクセス", format: "pv", description: "Heavenアクセス。予約経路とは結び付きません" }, diaryPosts: { label: "写メ日記", format: "count", description: "対象期間の投稿数" }, salesPerHour: { label: "売上／時間", format: "hourly", description: "Engineが算出した売上効率" }, salesPerPerson: { label: "売上／人", format: "currency", description: "Engineが算出した1人あたり売上" }, rewardPerHour: { label: "女子報酬／時間", format: "hourly", description: "Engineが算出した報酬効率" }, rewardPerPerson: { label: "女子報酬／人", format: "currency", description: "Engineが算出した1人あたり報酬" }, reservationsPerHour: { label: "予約／時間", format: "decimal", description: "Engineが算出した予約効率" }, reservationsPerPerson: { label: "予約／人", format: "decimal", description: "Engineが算出した予約効率" }, averageUnitPrice: { label: "平均単価", format: "currency", description: "Engineが算出した平均単価" }, regularNominationRate: { label: "本指名率", format: "percent", description: "Engineが算出した本指名率" }, utilizationRate: { label: "稼働率", format: "percent", description: "未接続の場合はAvailabilityで表示" }, theoreticalMaxAchievementRate: { label: "理論最大時給達成率", format: "percent", description: "ランク未接続の場合はAvailabilityで表示" }, opIncludedHourly: { label: "OP込み実績時給", format: "hourly", description: "入力未接続の場合はAvailabilityで表示" }, currentHourly: { label: "現在時給", format: "hourly", description: "Engineが算出した現在時給" }, theoreticalMaxHourly: { label: "理論最大時給", format: "hourly", description: "ランク未接続の場合はAvailabilityで表示" },
};
const efficiencyKeys = ["salesPerHour", "salesPerPerson", "rewardPerHour", "rewardPerPerson", "reservationsPerHour", "reservationsPerPerson", "averageUnitPrice", "regularNominationRate", "utilizationRate", "theoreticalMaxAchievementRate"];
const volumeKeys = ["sales", "castReward", "reservations", "services", "regularNominations", "attendancePeople", "attendanceMinutes", "diaryPosts", "townPv", "townUu", "heavenAccess"];

const metricValue = (summary: AnalyticsSummaryDto, key: string, category: "volume" | "efficiency") => category === "volume" ? summary.volume.metrics[key as never] : summary.efficiency[key as never];
const availabilityFor = (summary: AnalyticsSummaryDto, key: string, category: "volume" | "efficiency") => (summary[category].metricAvailability?.[key as never] ?? (metricValue(summary, key, category) === null || metricValue(summary, key, category) === undefined ? "MISSING" : metricValue(summary, key, category) === 0 ? "ZERO" : "VALUE")) as UiAvailability;
export function toPerformanceViewModel(response: PerformanceResponseDto) {
  const toMetrics = (summary: AnalyticsSummaryDto, keys: string[], category: "volume" | "efficiency") => keys.map((key) => { const spec = labels[key]; const value = metricValue(summary, key, category) as number | null | undefined; return { key, label: spec.label, value: value ?? null, format: spec.format, availability: availabilityFor(summary, key, category), description: spec.description }; });
  return { period: response.period, stores: response.stores, storeSummaries: response.storeSummaries ?? [], overall: response.overall ? { summary: response.overall, sample: response.overall.sample, efficiency: toMetrics(response.overall, efficiencyKeys, "efficiency"), volume: toMetrics(response.overall, volumeKeys, "volume") } : null, casts: response.casts.filter((item) => item.cast).map((item) => ({ ...item, name: item.cast?.displayName ?? "—", metrics: [...toMetrics(item.summary, efficiencyKeys, "efficiency"), ...toMetrics(item.summary, volumeKeys, "volume")], confidence: item.summary.sample.confidence, growthLabel: item.summary.growth?.classification ?? "Data不足", actionLevel: item.summary.nextBestAction?.actionLevel ?? "NONE", availability: (item.summary.growth?.availability ?? "MISSING") as UiAvailability })) };
}
