import { AnalyticsComparisonCard, AnalyticsEmptyState, AnalyticsErrorState, AnalyticsKpiCard, AnalyticsSection, AnalyticsSkeleton, AnalyticsUnavailableState, AvailabilityBadge, ConfidenceBadge, GrowthPotentialBadge, GrowthPotentialCard, InsightCard, NextBestActionCard, TrendIndicator } from "@/components/analytics";
import type { UiAvailability, UiConfidence } from "@/lib/analytics/ui";

const availability: UiAvailability[] = ["VALUE", "ZERO", "MISSING", "UNCOMPUTABLE", "UNAVAILABLE", "INSUFFICIENT_SAMPLE"];
const confidence: UiConfidence[] = ["High", "Medium", "Low", "Insufficient"];
const growth = ["Data不足", "Capacity上限", "Schedule制約", "Exposure不足", "Activity不足", "Efficiency改善余地", "安定維持"] as const;

export default function AnalyticsDesignSystemPage() {
  return <div className="mx-auto max-w-7xl"><header><p className="text-xs font-bold tracking-[0.2em] text-emerald-700">DEVELOPMENT CATALOG</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Analytics Design System</h1><p className="mt-2 text-sm text-slate-600">本番分析画面へ統合する前に、共通表示ルールと状態を確認する開発用カタログです。</p></header>
    <AnalyticsSection title="KPI / Availability / Confidence" description="Sample、Efficiency、Volumeを同じ文脈で表示します。0と欠測は別状態です。" period="2026-06-01〜2026-06-30"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><AnalyticsKpiCard label="売上" value={1240000} format="currency" confidence="High" sample="14日" period="2026-06-01〜2026-06-30" comparison={{ current: "¥1,240,000", baseline: "¥1,140,000", difference: "+¥100,000", rate: 8.4, label: "前月同期間", period: "2026-05-01〜2026-05-30", confidence: "High" }} trend={{ direction: "INCREASE", rate: 8.4 }} /><AnalyticsKpiCard label="実績0" value={0} format="count" availability="ZERO" /><AnalyticsKpiCard label="Town PV" value={null} format="pv" availability="MISSING" confidence="Insufficient" /></div><div className="mt-4 flex flex-wrap gap-2">{availability.map((item) => <AvailabilityBadge key={item} value={item} />)}{confidence.map((item) => <ConfidenceBadge key={item} value={item} />)}</div></AnalyticsSection>
    <AnalyticsSection title="Trend / Comparison" description="増加が常に良いとは限らないため、positiveIsBetterを明示して表示します。"><div className="grid gap-4 lg:grid-cols-2"><AnalyticsComparisonCard comparison={{ current: "¥1,240,000", baseline: "¥1,140,000", difference: "+¥100,000", rate: 8.4, label: "前月同期間", period: "2026-05-01〜2026-05-30", availability: "VALUE", confidence: "High" }} direction="INCREASE" /><AnalyticsComparisonCard comparison={{ current: "—", baseline: "—", label: "ランク平均", availability: "UNAVAILABLE" }} direction="UNAVAILABLE" /><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="mb-3 text-sm font-semibold">Trend states</p><div className="space-y-3"><TrendIndicator direction="INCREASE" difference="+100,000" rate={8.4} baselineLabel="前月同期間" positiveIsBetter /><TrendIndicator direction="DECREASE" difference="-2件" rate={-10} baselineLabel="前週" positiveIsBetter={false} /><TrendIndicator direction="FLAT" rate={0} baselineLabel="本人平均" /><TrendIndicator direction="UNAVAILABLE" /></div></div></div></AnalyticsSection>
    <AnalyticsSection title="Growth Potential" description="分類や優先順位はAPIの最終結果を表示し、UI側で再判定しません。"><div className="flex flex-wrap gap-2">{growth.map((item) => <GrowthPotentialBadge key={item} value={item} />)}</div><div className="mt-4 grid gap-4 lg:grid-cols-2"><GrowthPotentialCard classification="Exposure不足" reason="露出が店舗基準を下回っています。" evidence={["Town PVが店舗平均より18%低い", "対象14日、Confidence Medium"]} availability="VALUE" confidence="Medium" score={70} actionable /><GrowthPotentialCard classification="Data不足" reason="判定に必要な母数が不足しています。" evidence={["出勤実績が4回未満"]} availability="INSUFFICIENT_SAMPLE" confidence="Insufficient" score={0} actionable={false} /></div></AnalyticsSection>
    <AnalyticsSection title="Cause → Evidence → Action" description="原因を先に示し、根拠と母数を確認してから提案を表示します。"><InsightCard cause="金曜日の出勤時間が少ない" evidence={["金曜日の報酬時給は本人平均より18%高い"]} comparison="本人平均" sample="6回" confidence="Medium" action="金曜日の出勤枠を月2回追加する" /><div className="mt-4 grid gap-4 lg:grid-cols-2"><NextBestActionCard result={{ actionLevel: "ACTION", cause: "活動量が基準を下回る", evidence: ["出勤時間が店舗平均より低い"], action: "出勤時間の確保を検討", confidence: "High", availability: "VALUE", status: "OK" }} /><NextBestActionCard result={{ actionLevel: "REFERENCE", cause: "効率改善余地", evidence: ["母数が少ないため参考"], action: "参考値として確認", confidence: "Low", availability: "VALUE", status: "OK" }} /><NextBestActionCard result={{ actionLevel: "NONE", availability: "INSUFFICIENT_SAMPLE", confidence: "Insufficient", status: "DataInsufficient" }} /></div></AnalyticsSection>
    <AnalyticsSection title="Data states" description="Empty、Unavailable、Insufficient、Error、Loadingを分けて表示します."><div className="grid gap-4 lg:grid-cols-2"><AnalyticsEmptyState /><AnalyticsUnavailableState /><AnalyticsErrorState message="APIの応答を確認してください。" /><AnalyticsSkeleton count={2} /></div></AnalyticsSection>
  </div>;
}
