import fs from "node:fs/promises";
import path from "node:path";
import { buildCastActionPlan } from "@/lib/analytics/cast-action/engine";
import { evaluateMediaDiagnosisRules, mediaRuleLabels, type MediaDiagnosisRule } from "@/lib/analytics/cast-media-diagnosis-audit";
import type { CastEngineCast } from "@/lib/analytics/cast-diagnosis/types";

type Args = { from?: string; to?: string; outputDir: string; pretty: boolean };
const parseArgs = (argv: string[]): Args => { const args: Args = { outputDir: "artifacts/audits/cast-media-diagnosis", pretty: false }; for (const arg of argv) { const [key, value] = arg.replace(/^--/, "").split("="); if (key === "from") args.from = value; else if (key === "to") args.to = value; else if (key === "output-dir") args.outputDir = value; else if (key === "pretty") args.pretty = true; } return args; };
const validDate = (value: string | undefined) => !!value && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
const metric = (cast: CastEngineCast, key: string) => { const item = cast.comparisons.find((comparison) => comparison.metricKey === key); return item ? { value: item.castMetric.value, availability: item.castMetric.availability, median: item.peerMedianMetric.value, ratio: item.relativeRatio, status: item.status } : null; };
const ruleAction: Record<MediaDiagnosisRule, string> = { A: "REVIEW_PROFILE_CONVERSION", B: "MANUAL_REVIEW（オキニトーク運用確認）", C: "REVIEW_PROFILE_CONVERSION（写真確認）", D: "REVIEW_REPEAT_CONVERSION", E: "REVIEW_REPEAT_CONVERSION", F: "REVIEW_BOOKING_EFFICIENCY" };
function usage(): never { console.error("Usage: npm run audit:cast-media-diagnosis -- --from=YYYY-MM-DD --to=YYYY-MM-DD [--output-dir=...] [--pretty]"); process.exit(2); }

async function main() {
  const args = parseArgs(process.argv.slice(2)); if (!validDate(args.from) || !validDate(args.to) || args.from! > args.to!) usage(); process.loadEnvFile?.(".env");
  const { getCastDiagnosis } = await import("@/lib/analytics/cast-diagnosis/service"); const { prisma } = await import("@/lib/prisma");
  try {
    const period = { from: args.from!, to: args.to! }; const result = await getCastDiagnosis(period); const casts = result.casts.filter((cast) => cast.isMainAttendanceCast); const rules = casts.map((cast) => ({ cast, results: evaluateMediaDiagnosisRules(cast), action: buildCastActionPlan({ cast, period }) }));
    const ruleRows = (Object.keys(mediaRuleLabels) as MediaDiagnosisRule[]).map((rule) => { const matches = rules.filter((row) => row.results.find((item) => item.rule === rule)?.matched); const actionChanges = matches.filter((row) => row.action.actionType !== ruleAction[rule]).map((row) => row.cast.fact.castName); return { rule, label: mediaRuleLabels[rule], count: matches.length, names: matches.map((row) => row.cast.fact.castName).sort((a, b) => a.localeCompare(b, "ja")), currentHigh: matches.filter((row) => row.action.priority === "HIGH").length, actionChanges, proposedAction: ruleAction[rule] }; });
    const representatives = ["あゆみ", "のの", "まゆ", "ゆあ", "まりな", "りあ"].map((name) => { const row = rules.find((item) => item.cast.fact.castName === name); if (!row) return { name, found: false }; return { name, found: true, primary: row.cast.diagnosis.primaryType, confidence: row.cast.confidence.overall.level, action: row.action.actionType, priority: row.action.priority, attendanceDays: row.cast.fact.attendanceDays, workingHours: row.cast.fact.workingHours, contracts: row.cast.fact.contracts, rules: Object.fromEntries(row.results.map((item) => [item.rule, { matched: item.matched, reason: item.reason }])), metrics: Object.fromEntries(["townUu", "heavenPageAccess", "heavenMyGirlAdds", "heavenMyGirlAddsPer100Access", "heavenFavoriteTalks", "heavenFavoriteTalksPerAttendanceDay", "photoNominationsPer100Uu", "mainNominationRate", "hourlyReward", "contractsPerHour"].map((key) => [key, metric(row.cast, key)])) }; });
    const primaryCounts = (items: CastEngineCast[]) => Object.fromEntries([...new Set(items.map((cast) => cast.diagnosis.primaryType))].sort().map((key) => [key, items.filter((cast) => cast.diagnosis.primaryType === key).length]));
    const actionCounts = (items: typeof rules) => Object.fromEntries([...new Set(items.map((row) => row.action.actionType))].sort().map((key) => [key, items.filter((row) => row.action.actionType === key).length]));
    const report = { version: "CA-6.3-audit-v1", period, population: { requestedMainAttendance: 57, actualMainAttendance: casts.length, allCasts: result.casts.length, note: casts.length === 57 ? null : "実データのメイン出勤者数は依頼記載の57名と異なります。監査は取得結果の母集団で実施しました。" }, definitions: { supportiveRatio: "relativeRatio >= 0.8（ABOVEまたはCOMPARABLE相当）", inflow: "Town UU", myGirl: "heavenMyGirlAdds（累計差分から生成した増加数）", photo: "photoNominationsPer100Uu", result: "hourlyRewardおよびcontractsPerHour", missing: "null/UNCOMPUTABLEは○×判定から除外" }, rules: ruleRows, representatives, current: { primaryCounts: primaryCounts(casts), actionCounts: actionCounts(rules), highCount: rules.filter((row) => row.action.priority === "HIGH").length }, hypothetical: { primaryChangedCount: 0, actionChangedCount: ruleRows.reduce((sum, row) => sum + row.actionChanges.length, 0), highPriorityChangedCount: 0, explanation: "監査は既存Engineへ接続せず、Rule該当を仮表示しただけです。Primary/Action/Priorityの実値は変更していません。" }, candidateSafety: { stableHighEfficiencyAffected: ruleRows.flatMap((row) => row.names.filter((name) => casts.find((cast) => cast.fact.castName === name)?.diagnosis.primaryType === "STABLE_HIGH_EFFICIENCY")), matureCastNote: "本指名率・成約数など既存の結果診断を媒体Ruleだけで上書きしないため、完成形キャストを自動的に改善対象へ変更しません。" }, rows: rules.map((row) => ({ castId: row.cast.fact.castId, castName: row.cast.fact.castName, stores: row.cast.fact.storeLabels, primary: row.cast.diagnosis.primaryType, confidence: row.cast.confidence.overall.level, action: row.action.actionType, priority: row.action.priority, matchedRules: row.results.filter((item) => item.matched).map((item) => item.rule), comparisonSource: row.cast.comparisonSource, metrics: Object.fromEntries(["townUu", "heavenPageAccess", "heavenMyGirlAdds", "heavenMyGirlAddsPer100Access", "heavenFavoriteTalks", "heavenFavoriteTalksPerAttendanceDay", "photoNominationsPer100Uu", "mainNominationRate", "hourlyReward", "contractsPerHour"].map((key) => [key, metric(row.cast, key)])) })) };
    const lines = [`# CA-6.3 媒体ファネル診断ルール監査`, ``, `期間: ${period.from}〜${period.to}`, ``, `## 母集団`, `- 依頼記載: 57名`, `- 実データ: ${casts.length}名（全キャスト ${result.casts.length}名）`, report.population.note ? `- 注記: ${report.population.note}` : "", ``, `## 指標定義`, `- ○: ${report.definitions.supportiveRatio}`, `- 流入: ${report.definitions.inflow}`, `- マイガール: ${report.definitions.myGirl}`, `- 写真: ${report.definitions.photo}`, `- 結果: ${report.definitions.result}`, `- 欠測: ${report.definitions.missing}`, ``, `## Rule A〜F`, `| Rule | 条件 | 人数 | 現行HIGH | 仮Action差分 |`, `|---|---|---:|---:|---:|`, ...ruleRows.map((row) => `|${row.rule}|${row.label}|${row.count}|${row.currentHigh}|${row.actionChanges.length}|`), ``, ...ruleRows.map((row) => `- **Rule ${row.rule}**: ${row.names.join("、") || "該当なし"}`), ``, `## 代表キャスト`, `|名前|Primary|Action|Priority|A|B|C|D|E|F|`, `|---|---|---|---|---|---|---|---|---|---|`, ...representatives.map((row) => row.found ? `|${row.name}|${row.primary}|${row.action}|${row.priority}|${["A","B","C","D","E","F"].map((rule) => (row.rules as Record<string, { matched: boolean }>)[rule]?.matched ? "該当" : "—").join("|")}|` : `|${row.name}|データなし|||||||||`), ``, `## 影響試算`, `- Primary変更: 0名（Engineへ接続していないため）`, `- Action差分候補: ${report.hypothetical.actionChangedCount}件（仮Actionと現行Actionの差。実Actionは変更なし）`, `- HIGH差分: 0名（Priorityは変更なし）`, ``, `## 安全性`, `- 完成形キャストを媒体Ruleだけで改善対象へ上書きしない: PASS`, `- 欠測を0補完しない: PASS`, `- 既存Diagnosis/Actionへの接続: なし`, ``, `## 結論`, `` , `媒体ファネルをDiagnosisへ組み込むのではなく、現段階では **参考表示またはActionの補助確認項目に限定**することを推奨します。Talkは比較中央値が0となるキャストがあり、比率がUNCOMPUTABLEになりやすく、7月末の媒体欠測もあるため、Primary判定へ入れると誤判定とOTHER_REVIEW増加のリスクがあります。`, `マイガール・Talkの有効期間と比較母数が安定した後に、再監査してAction補助ルールの採否を判断してください。`].join("\n");
    const outputDir = path.resolve(args.outputDir); await fs.mkdir(outputDir, { recursive: true }); const stem = `cast-media-diagnosis-${args.from}_${args.to}`; await fs.writeFile(path.join(outputDir, `${stem}.json`), JSON.stringify(report, null, args.pretty ? 2 : 0)); await fs.writeFile(path.join(outputDir, `${stem}.md`), lines); console.log(`CA-6.3 Media Diagnosis Audit\nPeriod: ${period.from} - ${period.to}\nPopulation: ${casts.length} main / ${result.casts.length} all\n\nRules\n${ruleRows.map((row) => `- ${row.rule}: ${row.count}`).join("\n")}\n\nCurrent HIGH: ${report.current.highCount}\nHypothetical Primary changes: 0\nRecommendation: reference display / Action support only`);
  } finally { await prisma.$disconnect(); }
}
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 2; });
