import fs from "node:fs/promises";
import path from "node:path";
import { buildCastDiagnosisAuditReport } from "@/lib/analytics/cast-diagnosis/audit";

type Args = { from?: string; to?: string; outputDir: string; pretty: boolean; failOnDiffCount: number };
function parseArgs(argv: string[]): Args { const args: Args = { outputDir: "artifacts/audits/cast-diagnosis", pretty: false, failOnDiffCount: 15 }; for (const arg of argv) { const [key, value] = arg.replace(/^--/, "").split("="); if (key === "from") args.from = value; else if (key === "to") args.to = value; else if (key === "output-dir") args.outputDir = value; else if (key === "pretty") args.pretty = true; else if (key === "fail-on-diff-count") args.failOnDiffCount = Number(value); } return args; }
const validDate = (value: string | undefined) => !!value && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
function usage(): never { console.error("Usage: npm run audit:cast-diagnosis -- --from=YYYY-MM-DD --to=YYYY-MM-DD [--output-dir=...] [--pretty]"); process.exit(2); }
function markdown(report: ReturnType<typeof buildCastDiagnosisAuditReport>) { const s = report.summary; return [`# Cast Diagnosis Audit`, ``, `期間: ${report.metadata.period.from}〜${report.metadata.period.to}`, ``, `## データ母数`, `- 全キャスト: ${report.dataset.totalFactCastCount}`, `- メイン出勤者: ${report.dataset.mainAttendanceCastCount}`, `- 結果上位群: ${report.dataset.topGroupCount}`, ``, `## 診断分布`, ``, `|診断|Baseline|Current|`, `|---|---:|---:|`, ...Object.keys(s.currentDiagnosisCounts).map((key) => `|${key}|${s.baselineDiagnosisCounts[key] ?? 0}|${s.currentDiagnosisCounts[key] ?? 0}|`), ``, `## 差分`, `- Primary変更: ${s.primaryChangedCount}`, `- 軸不一致: ${s.axisMismatchCount}`, `- Facts不一致: ${s.factsMismatchCount}`, `- Validation違反: ${s.validationViolationCount}`, ``, `## Safety`, s.stoppedBySafetyCondition ? `FAIL: ${s.safetyReasons.join("、")}` : `PASS`, ``, `## Step 3-B`, s.stoppedBySafetyCondition ? `進行不可` : `進行可能`].join("\n"); }
async function main() { const args = parseArgs(process.argv.slice(2)); if (!validDate(args.from) || !validDate(args.to) || args.from! > args.to!) usage(); process.loadEnvFile?.(".env"); const { getCastDiagnosis } = await import("@/lib/analytics/cast-diagnosis/service"); const { prisma } = await import("@/lib/prisma"); try { const baseline = await getCastDiagnosis({ from: args.from!, to: args.to!, comparisonMode: "LEGACY_RESULT_TOP_ONLY" }); const current = await getCastDiagnosis({ from: args.from!, to: args.to!, comparisonMode: "AXIS_SPECIFIC" }); const report = buildCastDiagnosisAuditReport(baseline, current, { from: args.from!, to: args.to! }); const outputDir = path.resolve(args.outputDir); await fs.mkdir(outputDir, { recursive: true }); const stem = `cast-diagnosis-${args.from}_${args.to}`; await fs.writeFile(path.join(outputDir, `${stem}.json`), JSON.stringify(report, null, args.pretty ? 2 : 0)); await fs.writeFile(path.join(outputDir, `${stem}.md`), markdown(report)); console.log(`Cast Diagnosis Audit\nPeriod: ${args.from} - ${args.to}\n\nDataset\n- All casts: ${report.dataset.totalFactCastCount}\n- Main attendance: ${report.dataset.mainAttendanceCastCount}\n- Top group: ${report.dataset.topGroupCount}\n\nDiagnosis changes\n- Primary changed: ${report.summary.primaryChangedCount}\n- Validation violations: ${report.summary.validationViolationCount}\n- Axis mismatches: ${report.summary.axisMismatchCount}\n- Facts mismatches: ${report.summary.factsMismatchCount}\n\nSafety\n- ${report.summary.stoppedBySafetyCondition ? "FAIL" : "PASS"}\n- Step 3-B: ${report.summary.stoppedBySafetyCondition ? "BLOCKED" : "ALLOWED"}`); if (report.summary.primaryChangedCount >= args.failOnDiffCount || report.summary.stoppedBySafetyCondition) process.exitCode = 1; } finally { await prisma.$disconnect(); } }
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 2; });
