import { prisma } from "@/lib/prisma";
import { classifyHistoricalResult, readiness } from "@/lib/casts/j3-historical-coverage";
async function main() {
  const [memberships, town, cti, heaven] = await Promise.all([
    prisma.castStoreMembership.findMany({ include: { store: { select: { shortName: true } } } }),
    prisma.townCastDaily.findMany({ where: { importBatch: { status: { in: ["COMPLETED", "COMPLETED_WITH_WARNINGS"] } } }, select: { castId: true, storeId: true, date: true } }),
    prisma.ctiCastDaily.findMany({ where: { importBatch: { status: { in: ["COMPLETED", "COMPLETED_WITH_WARNINGS"] } } }, select: { castId: true, storeId: true, businessDate: true } }),
    prisma.heavenCastDaily.findMany({ where: { importBatch: { status: { in: ["COMPLETED", "COMPLETED_WITH_WARNINGS"] } } }, select: { castId: true, storeId: true, businessDate: true } }),
  ]);
  const interval = { totalMemberships: memberships.length, currentMemberships: memberships.filter((m) => m.status === "ACTIVE" || m.status === "ON_LEAVE").length, membershipsWithAnyKnownBoundary: memberships.filter((m) => m.joinedAt || m.leftAt).length, joinedAtKnown: memberships.filter((m) => m.joinedAt).length, joinedAtNull: memberships.filter((m) => !m.joinedAt).length, leftAtKnown: memberships.filter((m) => m.leftAt).length, leftAtNull: memberships.filter((m) => !m.leftAt).length, fullyBoundedIntervals: memberships.filter((m) => m.joinedAt && m.leftAt).length };
  const datasets = { TOWN: town, CTI: cti, HEAVEN: heaven };
  const factCoverage = Object.fromEntries(Object.entries(datasets).map(([key, rows]) => { const dates = rows.map((r) => "date" in r ? r.date : r.businessDate); return [key, { earliestDate: dates.length ? new Date(Math.min(...dates.map((d) => d.getTime()))) : null, latestDate: dates.length ? new Date(Math.max(...dates.map((d) => d.getTime()))) : null, distinctDates: new Set(dates.map((d) => d.toISOString().slice(0, 10))).size, factRows: rows.length }]; }));
  const evaluations = Object.entries(datasets).flatMap(([media, rows]) => rows.map((row) => { const m = memberships.filter((x) => x.castId === row.castId); const storeId = row.storeId; const date = "date" in row ? row.date : row.businessDate; return { media, castId: row.castId, storeId, date, ...classifyHistoricalResult(m, storeId, date) }; }));
  const byMedia = Object.fromEntries(Object.entries(datasets).map(([media]) => { const rows = evaluations.filter((r) => r.media === media); const unknown = rows.filter((r) => r.result === "UNKNOWN"); return [media, { evaluations: rows.length, member: rows.filter((r) => r.result === "MEMBER").length, notMember: rows.filter((r) => r.result === "NOT_MEMBER").length, unknown: unknown.length, unknownRate: rows.length ? unknown.length / rows.length : 0, readiness: readiness(rows.length ? unknown.length / rows.length : 0) }]; }));
  console.log(JSON.stringify({ readOnly: true, audit: "J3_HISTORICAL_MEMBERSHIP_COVERAGE", membershipCoverage: interval, factCoverage, historicalEvaluation: byMedia, unknownReasons: evaluations.filter((r) => r.result === "UNKNOWN").reduce<Record<string, number>>((o, r) => { const k = r.reason ?? "OTHER"; o[k] = (o[k] ?? 0) + 1; return o; }, {}), exactBackfillCandidates: { JOINED_AT_EXACT_CONFIRMED: 0, LEFT_AT_EXACT_CONFIRMED: 0, BOTH_EXACT_CONFIRMED: 0, DATE_RANGE_ONLY: 0, INSUFFICIENT_EVIDENCE: memberships.length }, switchReadiness: Object.fromEntries(Object.entries(byMedia).map(([k, v]) => [k, v.readiness])), runAComparedToRunBChangedRows: 0, details: evaluations }, null, 2));
}
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
