import { CAST_DIAGNOSIS_THRESHOLDS as T, thresholdsDto } from "./thresholds";
import type { Availability } from "@/lib/analytics/engine/types";
import type { CastDiagnosisInput, CastMonthlyFact, CastMetric, CastMetricComparison, CastEngineCast, CastDiagnosisType, CastDiagnosisFact, CastPeerSelection, DiagnosisStep, DiagnosisConfidencePart, MetricPeerCoverage, CastReviewTarget, CastReviewPriority, InsufficientReason, OtherReviewReason } from "./types";
import { buildCastComparisonAudit } from "@/lib/analytics/cast-comparison/service";
import type { CastMetricPeerComparison } from "@/lib/analytics/cast-comparison/types";

const metric = (value: number | null, availability?: Availability): CastMetric => ({ value, availability: availability ?? (value === null ? "MISSING" : value === 0 ? "ZERO" : "VALUE") });
const ratio = (a: CastMetric, b: CastMetric): CastMetric => a.value === null || b.value === null ? metric(null, a.availability === "UNAVAILABLE" || b.availability === "UNAVAILABLE" ? "UNAVAILABLE" : "UNCOMPUTABLE") : b.value === 0 ? metric(null, "UNCOMPUTABLE") : metric(a.value / b.value);
const sumMetric = (values: number[], missing = false): CastMetric => values.length ? metric(values.reduce((a, b) => a + b, 0)) : metric(null, missing ? "MISSING" : "UNAVAILABLE");
const median = (values: number[]) => { const a = [...values].sort((x, y) => x - y); if (!a.length) return null; const i = Math.floor(a.length / 2); return a.length % 2 ? a[i] : (a[i - 1] + a[i]) / 2; };
const n = (x: CastMetric) => x.value;

export type CastRawInput = {
  castId: string; castName: string; storeId: string; storeLabel: string; date: string;
  attendanceCount: number; attendanceMinutes: number | null; reservations: number | null; contracts: number | null; mainNominations: number | null; photoNominations: number | null; freeCount: number | null; newCount: number | null; repeatCount: number | null; cancelCount: number | null; femaleReward: number | null; chargeAmount: number | null; profit: number | null; paidOptionCount: number | null;
  townPv?: number | null; townUu?: number | null; townAvailability?: Availability; heavenPageAccess?: number | null; heavenDiaryPosts?: number | null; heavenAvailability?: Availability;
};

export function buildMonthlyFacts(rows: CastRawInput[]): CastMonthlyFact[] {
  const grouped = new Map<string, CastRawInput[]>();
  for (const row of rows) { const list = grouped.get(row.castId) ?? []; list.push(row); grouped.set(row.castId, list); }
  const sumField = (items: CastRawInput[], key: keyof CastRawInput) => { const values = items.map((r) => r[key]).filter((v): v is number => typeof v === "number" && Number.isFinite(v)); return sumMetric(values, !values.length); };
  return [...grouped.values()].map((items) => {
    const dates = new Set(items.filter((r) => r.attendanceCount > 0).map((r) => r.date));
    const storeIds = [...new Set(items.map((r) => r.storeId))]; const storeLabels = [...new Set(items.map((r) => r.storeLabel))];
    const attendanceDays = metric(dates.size); const attendanceMinutes = sumField(items, "attendanceMinutes"); const workingHours = attendanceMinutes.value === null ? metric(null, attendanceMinutes.availability) : metric(attendanceMinutes.value / 60);
    const fact: CastMonthlyFact = {
      castId: items[0].castId, castName: items[0].castName, storeIds, storeLabels, attendanceDays, workingHours,
      reservations: sumField(items, "reservations"), contracts: sumField(items, "contracts"), mainNominations: sumField(items, "mainNominations"), photoNominations: sumField(items, "photoNominations"), freeCount: sumField(items, "freeCount"), newCount: sumField(items, "newCount"), repeatCount: sumField(items, "repeatCount"), cancelCount: sumField(items, "cancelCount"), femaleReward: sumField(items, "femaleReward"), chargeAmount: sumField(items, "chargeAmount"), profit: sumField(items, "profit"), paidOptionCount: sumField(items, "paidOptionCount"),
      townPv: sumField(items.filter((r) => r.townPv !== undefined), "townPv"), townUu: sumField(items.filter((r) => r.townUu !== undefined), "townUu"), heavenPageAccess: sumField(items.filter((r) => r.heavenPageAccess !== undefined), "heavenPageAccess"), heavenDiaryPosts: sumField(items.filter((r) => r.heavenDiaryPosts !== undefined), "heavenDiaryPosts"),
      heavenMyGirlAdds: metric(null, "UNAVAILABLE"), heavenFavoriteTalks: metric(null, "UNAVAILABLE"), heavenMyGirlAddsPer100Access: metric(null, "UNAVAILABLE"), heavenMyGirlAddsPer100TownUu: metric(null, "UNAVAILABLE"), heavenFavoriteTalksPerAttendanceDay: metric(null, "UNAVAILABLE"), heavenFavoriteTalksPer100Access: metric(null, "UNAVAILABLE"),
      hourlyReward: ratio(sumField(items, "femaleReward"), workingHours), contractsPerDay: ratio(sumField(items, "contracts"), attendanceDays), contractsPerHour: ratio(sumField(items, "contracts"), workingHours), photoNominationsPerDay: ratio(sumField(items, "photoNominations"), attendanceDays), photoNominationsPerHour: ratio(sumField(items, "photoNominations"), workingHours), photoNominationsPer100Uu: (() => { const p = sumField(items, "photoNominations"); const u = sumField(items.filter((r) => r.townUu !== undefined), "townUu"); return p.value === null || u.value === null || u.value === 0 ? metric(null, u.availability === "UNAVAILABLE" ? "UNAVAILABLE" : "UNCOMPUTABLE") : metric(p.value / u.value * 100); })(),
      mainNominationRate: ratio(sumField(items, "mainNominations"), sumField(items, "contracts")), photoNominationShare: ratio(sumField(items, "photoNominations"), sumField(items, "contracts")), repeatShare: ratio(sumField(items, "repeatCount"), sumField(items, "contracts")),
    };
    if (items.every((r) => r.townPv === undefined && r.townUu === undefined)) { fact.townPv = metric(null, "UNAVAILABLE"); fact.townUu = metric(null, "UNAVAILABLE"); }
    if (items.every((r) => r.heavenPageAccess === undefined && r.heavenDiaryPosts === undefined)) { fact.heavenPageAccess = metric(null, "UNAVAILABLE"); fact.heavenDiaryPosts = metric(null, "UNAVAILABLE"); }
    return fact;
  });
}

function coverage(key: keyof CastMonthlyFact, peers: CastMonthlyFact[]): MetricPeerCoverage {
  const values = peers.map((p) => p[key] as CastMetric); const valid = values.filter((m) => m.value !== null); return { metricKey: String(key), eligiblePeerCount: peers.length, validPeerCount: valid.length, unavailablePeerCount: values.filter((m) => m.availability === "UNAVAILABLE").length, missingPeerCount: values.filter((m) => m.availability === "MISSING").length, medianAvailability: valid.length ? valid.some((m) => m.value !== 0) ? "VALUE" : "ZERO" : values.some((m) => m.availability === "UNAVAILABLE") ? "UNAVAILABLE" : "MISSING" };
}
function peerMetric(key: keyof CastMonthlyFact, peers: CastMonthlyFact[]): { metric: CastMetric; coverage: MetricPeerCoverage } { const c = coverage(key, peers); const values = peers.map((p) => p[key] as CastMetric).map((m) => m.value).filter((v): v is number => v !== null); return { metric: values.length ? metric(median(values)) : metric(null, c.medianAvailability), coverage: c }; }
function comparison(fact: CastMonthlyFact, peers: CastMonthlyFact[], key: keyof CastMonthlyFact, label: string, unit: string): CastMetricComparison {
  const castMetric = fact[key] as CastMetric; const comparablePeers = peers.filter((peer) => peer.castId !== fact.castId); const { metric: peerMedianMetric, coverage: peerCoverage } = peerMetric(key, comparablePeers); const a = castMetric.value; const b = peerMedianMetric.value; const relativeRatio = a === null || b === null || b === 0 ? null : a / b; const status = a === null || b === null || (b === 0 && a !== 0) ? "UNCOMPUTABLE" : a === 0 && b === 0 ? "COMPARABLE" : relativeRatio! >= 1 ? "ABOVE" : relativeRatio! >= T.comparableRatio ? "COMPARABLE" : relativeRatio! >= T.lowRatio ? "INTERMEDIATE" : "BELOW"; return { metricKey: String(key), label, unit, castMetric, peerMedianMetric, absoluteDifference: a === null || b === null ? null : a - b, relativeRatio, relativeDifference: relativeRatio === null ? null : relativeRatio - 1, status, peerCoverage, thresholdsUsed: { comparableRatio: T.comparableRatio, lowRatio: T.lowRatio } };
}
function comparisonFromAxis(c: CastMetricPeerComparison, label: string, unit: string): CastMetricComparison {
  const a = c.subject.value, b = c.median.value;
  const relativeRatio = c.ratio.value;
  const status: CastMetricComparison["status"] = a === null || b === null || c.availability === "INSUFFICIENT_SAMPLE" ? "UNCOMPUTABLE" : a === 0 && b === 0 ? "COMPARABLE" : relativeRatio !== null && relativeRatio >= 1 ? "ABOVE" : relativeRatio !== null && relativeRatio >= T.comparableRatio ? "COMPARABLE" : relativeRatio !== null && relativeRatio >= T.lowRatio ? "INTERMEDIATE" : relativeRatio !== null ? "BELOW" : "UNCOMPUTABLE";
  const peerCoverage: MetricPeerCoverage = { metricKey: c.metricKey, eligiblePeerCount: c.selection.validPeerCount, validPeerCount: c.selection.validPeerCount, unavailablePeerCount: c.peers.filter((p) => p.metric.availability === "UNAVAILABLE").length, missingPeerCount: c.peers.filter((p) => p.metric.availability === "MISSING").length, medianAvailability: c.median.availability };
  return { metricKey: c.metricKey, label, unit, castMetric: c.subject, peerMedianMetric: c.median, absoluteDifference: a === null || b === null ? null : a - b, relativeRatio, relativeDifference: relativeRatio === null ? null : relativeRatio - 1, status, peerCoverage, thresholdsUsed: { comparableRatio: T.comparableRatio, lowRatio: T.lowRatio }, comparisonAxis: c.axis, comparisonAxisLabel: c.axisLabel, peerSelectionMethod: c.selection.method, validPeerCount: c.selection.validPeerCount, candidateCount: c.selection.candidateCount, workingHoursRange: c.selection.workingHoursRange, fallbackReason: c.selection.fallbackReason, diagnosticUsage: c.diagnosticUsage, medianEvidence: c.medianEvidence, peerEvidence: c.peers };
}
function part(level: DiagnosisConfidencePart["level"], reasons: string[]): DiagnosisConfidencePart { return { level, label: level, reasons }; }
function confidence(f: CastMonthlyFact, peerCount: number): import("./types").CastDiagnosisConfidence {
  const days = n(f.attendanceDays) ?? 0, hours = n(f.workingHours) ?? 0, contracts = n(f.contracts) ?? 0; const reasons: string[] = []; let level: DiagnosisConfidencePart["level"] = "HIGH";
  if (days < 2 || hours < T.minimumDiagnosisHours || f.hourlyReward.value === null || peerCount < T.minimumPeerCount) { level = "INSUFFICIENT"; reasons.push("主要母数または比較群が不足しています。"); } else if (days <= 3 || hours < 20 || contracts < 5) { level = "LOW"; reasons.push("出勤日数・稼働時間・成約数の一部が少ないため参考値です。"); } else if (days <= 7 || contracts < 10) { level = "MEDIUM"; reasons.push(contracts < T.nominationMinimumContracts ? `成約${contracts}本のため本指名率は参考値です。` : "標準母数ですが、高信頼の閾値には未達です。"); } else reasons.push("主要母数と比較群が確保されています。");
  const photoLevel = (n(f.townUu) ?? 0) >= T.conversionMinimumUu ? level : "LOW"; const repeatLevel = contracts >= T.nominationMinimumContracts ? level : "LOW"; const p = part(photoLevel, photoLevel === "LOW" ? ["Town UU 100未満のため写真指名転換は参考値です。"] : []); const r = part(repeatLevel, repeatLevel === "LOW" ? ["成約10本未満のため本指名率は参考値です。"] : []); return { overall: part(level, reasons), steps: { result: part(level, []), pageTraffic: part(n(f.townUu) === null ? "INSUFFICIENT" : level, []), photoConversion: p, repeatConversion: r }, attendanceDays: days, workingHours: hours, contractCount: contracts, townUu: f.townUu.value, peerCount };
}
function factFromComparison(c: CastMetricComparison): CastDiagnosisFact { return { metricKey: c.metricKey, label: c.label, castValue: c.castMetric.value, peerMedianValue: c.peerMedianMetric.value, absoluteDifference: c.absoluteDifference, relativeRatio: c.relativeRatio, statement: c.relativeRatio === null ? `${c.label}は比較不能です。` : `${c.label}は${c.comparisonAxisLabel ?? "比較群"}中央値の${(c.relativeRatio * 100).toFixed(1)}%です。`, availability: c.castMetric.availability, comparisonAxis: c.comparisonAxis, comparisonAxisLabel: c.comparisonAxisLabel, diagnosticUsage: c.diagnosticUsage, medianEvidence: c.medianEvidence }; }
function sampleFact(f: CastMonthlyFact): CastDiagnosisFact { return { metricKey: "contracts", label: "成約母数", castValue: f.contracts.value, peerMedianValue: null, absoluteDifference: null, relativeRatio: null, statement: `本指名率は${f.mainNominationRate.value === null ? "算出不能" : `${(f.mainNominationRate.value * 100).toFixed(1)}%`}ですが、成約${f.contracts.value ?? 0}本を母数とする参考値です。正式判定基準は成約${T.nominationMinimumContracts}本以上です。`, availability: f.contracts.availability }; }
function insufficientReasons(f: CastMonthlyFact, peerCount: number): InsufficientReason[] {
  const days = f.attendanceDays.value ?? 0, hours = f.workingHours.value ?? 0;
  const reasons: InsufficientReason[] = [];
  if (days === 0) reasons.push("ATTENDANCE_0_DAYS"); else if (days === 1) reasons.push("ATTENDANCE_1_DAY");
  if (hours < T.minimumDiagnosisHours) reasons.push("HOURS_BELOW_MINIMUM");
  if (f.hourlyReward.value === null) reasons.push("HOURLY_REWARD_UNCOMPUTABLE");
  if (peerCount < T.minimumPeerCount) reasons.push("INSUFFICIENT_COMPARISON_GROUP");
  const major = [f.femaleReward, f.contracts, f.mainNominations].some((m) => m.value === null);
  if (major) reasons.push("CTI_MAJOR_DATA_MISSING");
  return reasons.length ? reasons : ["OTHER"];
}
function step(stepName: DiagnosisStep["step"], metrics: CastMetricComparison[], conf: DiagnosisConfidencePart, explanation: string): DiagnosisStep { const low = metrics.some((m) => m.status === "BELOW"), unavailable = metrics.some((m) => m.status === "UNCOMPUTABLE"); return { step: stepName, status: unavailable ? "UNAVAILABLE" : low ? "LOW" : metrics.some((m) => m.status === "INTERMEDIATE") ? "INTERMEDIATE" : metrics.length ? "GOOD" : "INSUFFICIENT", metrics, facts: metrics.map(factFromComparison), confidence: conf, thresholdExplanation: explanation }; }
function diagnose(f: CastMonthlyFact, cs: CastMetricComparison[], conf: import("./types").CastDiagnosisConfidence): CastEngineCast["diagnosis"] {
  const get = (key: string) => cs.find((c) => c.metricKey === key); const hourly = get("hourlyReward"), reward = get("femaleReward"), hours = get("workingHours"), uu = get("townUu"), photoHour = get("photoNominationsPerHour"), photo100 = get("photoNominationsPer100Uu"), diary = get("heavenDiaryPosts"); const ratioOf = (c?: CastMetricComparison) => c?.relativeRatio;
  const insufficient = conf.overall.level === "INSUFFICIENT"; const stable = !insufficient && (f.hourlyReward.value ?? 0) >= T.goodHourlyReward && (ratioOf(hourly) ?? 0) >= T.comparableRatio && (f.mainNominationRate.value ?? 0) >= T.goodNominationRate; const limited = stable && (ratioOf(reward) ?? 1) < T.lowRatio && (ratioOf(hours) ?? 1) < T.lowRatio; const lowTraffic = !insufficient && (ratioOf(hourly) ?? 1) < T.comparableRatio && (ratioOf(photoHour) ?? 1) < T.lowRatio && (ratioOf(uu) ?? 1) < T.lowTrafficRatio && uu?.castMetric.value !== null; const profile = !insufficient && (ratioOf(hourly) ?? 1) < T.comparableRatio && (ratioOf(uu) ?? 0) >= T.comparableRatio && (ratioOf(photo100) ?? 1) < T.lowRatio && (f.townUu.value ?? 0) >= T.conversionMinimumUu; const repeat = !insufficient && (ratioOf(photoHour) ?? 0) >= T.comparableRatio && (f.mainNominationRate.value ?? 1) < T.lowNominationRate && (f.contracts.value ?? 0) >= T.nominationMinimumContracts; const other = !insufficient && (ratioOf(photoHour) ?? 0) >= T.comparableRatio && (f.mainNominationRate.value ?? 1) >= T.lowNominationRate && (ratioOf(hourly) ?? 1) < T.lowRatio;
  const primary: CastDiagnosisType = insufficient ? "INSUFFICIENT_DATA" : limited ? "LIMITED_BY_AVAILABILITY" : stable ? "STABLE_HIGH_EFFICIENCY" : lowTraffic ? "LOW_PAGE_TRAFFIC" : profile ? "LOW_PROFILE_CONVERSION" : repeat ? "LOW_REPEAT_CONVERSION" : other ? "OTHER_REVIEW" : "OTHER_REVIEW";
  const secondary: CastDiagnosisType[] = []; if (!insufficient && (ratioOf(uu) ?? 1) < T.lowTrafficRatio && (ratioOf(photoHour) ?? 1) < T.lowRatio && (ratioOf(diary) ?? 1) < T.lowRatio && diary?.peerMedianMetric.value !== null) secondary.push("LOW_NEW_CUSTOMER_ACQUISITION");
  const targets: Record<CastDiagnosisType, CastReviewTarget[]> = { INSUFFICIENT_DATA: ["DATA_INTEGRITY"], STABLE_HIGH_EFFICIENCY: ["NONE"], LIMITED_BY_AVAILABILITY: ["NONE"], LOW_PAGE_TRAFFIC: ["LISTING_PHOTO", "LISTING_COPY", "MEDIA_EXPOSURE", "DIARY_POSTING"], LOW_PROFILE_CONVERSION: ["PROFILE_PHOTOS", "PROFILE_COPY", "PROFILE_TEXT", "DIARY_CONTENT"], LOW_REPEAT_CONVERSION: ["REPEAT_STATUS", "STAFF_REVIEW"], LOW_NEW_CUSTOMER_ACQUISITION: ["MEDIA_EXPOSURE", "DIARY_POSTING"], OTHER_REVIEW: ["CANCELLATIONS", "DATA_INTEGRITY"] }; const summary: Record<CastDiagnosisType, string> = { INSUFFICIENT_DATA: "必要な母数または比較群が不足しています。", STABLE_HIGH_EFFICIENCY: "稼働効率と本指名率は結果上位群と比べて良好です。", LIMITED_BY_AVAILABILITY: "効率は良好ですが、稼働量に差があります。", LOW_PAGE_TRAFFIC: "ページ流入・写真指名効率に差があります。", LOW_PROFILE_CONVERSION: "ページ流入に対して写真指名転換に差があります。", LOW_REPEAT_CONVERSION: "写真指名効率に対して本指名率に差があります。", LOW_NEW_CUSTOMER_ACQUISITION: "流入・写真指名・媒体活動の複数指標に差があります。", OTHER_REVIEW: "結果指標に差があるため、追加確認が必要です。" };
  const resultMetrics = cs.filter((c) => ["hourlyReward", "contractsPerHour", "femaleReward"].includes(c.metricKey)); const pageMetrics = cs.filter((c) => ["townPv", "townUu", "heavenPageAccess"].includes(c.metricKey)); const photoMetrics = cs.filter((c) => ["photoNominationsPerHour", "photoNominationsPer100Uu", "photoNominations"].includes(c.metricKey)); const repeatMetrics = cs.filter((c) => ["mainNominationRate", "repeatCount", "repeatShare"].includes(c.metricKey));
  const candidateFacts = [...resultMetrics, ...pageMetrics, ...photoMetrics, ...repeatMetrics].filter((c) => c.status === "BELOW" || c.status === "INTERMEDIATE").slice(0, 6).map(factFromComparison);
  const facts = [...(candidateFacts.length ? candidateFacts : (hourly ? [factFromComparison(hourly)] : [])), ...(primary === "STABLE_HIGH_EFFICIENCY" && (f.contracts.value ?? 0) < T.nominationMinimumContracts ? [sampleFact(f)] : [])];
  const otherReviewReason: OtherReviewReason | null = primary !== "OTHER_REVIEW" ? null : (f.hourlyReward.value !== null && (ratioOf(hourly) ?? 0) >= T.comparableRatio && (f.contracts.value ?? 0) < T.nominationMinimumContracts ? "HIGH_EFFICIENCY_LOW_SAMPLE" : (ratioOf(photoHour) ?? 0) >= T.comparableRatio && (f.mainNominationRate.value ?? 1) < T.lowNominationRate ? "PHOTO_EFFICIENCY_GOOD_REPEAT_SAMPLE_LOW" : [ratioOf(hourly), ratioOf(photoHour), ratioOf(uu)].some((x) => x !== null && x !== undefined && x >= T.lowRatio && x < T.comparableRatio) ? "INTERMEDIATE_THRESHOLDS" : (f.hourlyReward.value ?? 0) < T.goodHourlyReward ? "LOW_HOURLY_REWARD_WITHOUT_CLEAR_BOTTLENECK" : "NO_EXPLICIT_DIAGNOSIS_MATCH");
  return { primaryType: primary, secondaryTypes: secondary, otherReviewReason, label: primary, summary: summary[primary], facts, reviewTargets: targets[primary], steps: { result: step("RESULT", resultMetrics, conf.steps.result, "結果指標は上位群中央値と比較します。"), pageTraffic: step("PAGE_TRAFFIC", pageMetrics, conf.steps.pageTraffic, "Town/Heavenの正式取得値のみを比較します。"), photoConversion: step("PHOTO_CONVERSION", photoMetrics, conf.steps.photoConversion, "写真指名効率は分母のAvailabilityを保持します。"), repeatConversion: step("REPEAT_CONVERSION", repeatMetrics, conf.steps.repeatConversion, "成約10本以上の場合に本指名率を正式判定します。") } };
}

export function validateDiagnosisAssignment(cast: CastEngineCast): { valid: boolean; violations: string[] } {
  const violations: string[] = [];
  const f = cast.fact;
  const get = (key: string) => cast.comparisons.find((c) => c.metricKey === key)?.relativeRatio;
  const insufficient = cast.diagnosis.primaryType === "INSUFFICIENT_DATA";
  const reasons = cast.insufficientReasons;
  if (insufficient && reasons.length === 0) violations.push("INSUFFICIENT_DATAに理由がありません。");
  if (!insufficient && reasons.some((r) => r !== "OTHER")) violations.push("母数不足理由があるのに確定診断です。");
  if (cast.diagnosis.facts.length === 0) violations.push("Primary診断のFactがありません。");
  const type = cast.diagnosis.primaryType;
  if (type === "STABLE_HIGH_EFFICIENCY" && !((f.hourlyReward.value ?? 0) >= T.goodHourlyReward && (get("hourlyReward") ?? 0) >= T.comparableRatio && (f.mainNominationRate.value ?? 0) >= T.goodNominationRate)) violations.push("STABLE_HIGH_EFFICIENCY条件不一致。");
  if (type === "LIMITED_BY_AVAILABILITY" && !((f.hourlyReward.value ?? 0) >= T.goodHourlyReward && (get("hourlyReward") ?? 0) >= T.comparableRatio && (f.mainNominationRate.value ?? 0) >= T.goodNominationRate && (get("femaleReward") ?? 1) < T.lowRatio && (get("workingHours") ?? 1) < T.lowRatio)) violations.push("LIMITED_BY_AVAILABILITY条件不一致。");
  if (type === "LOW_PAGE_TRAFFIC" && !((get("hourlyReward") ?? 1) < T.comparableRatio && (get("photoNominationsPerHour") ?? 1) < T.lowRatio && (get("townUu") ?? 1) < T.lowTrafficRatio && cast.comparisons.find((c) => c.metricKey === "townUu")?.castMetric.value !== null)) violations.push("LOW_PAGE_TRAFFIC条件不一致。");
  if (type === "LOW_PROFILE_CONVERSION" && !((get("hourlyReward") ?? 1) < T.comparableRatio && (get("townUu") ?? 0) >= T.comparableRatio && (get("photoNominationsPer100Uu") ?? 1) < T.lowRatio && (f.townUu.value ?? 0) >= T.conversionMinimumUu)) violations.push("LOW_PROFILE_CONVERSION条件不一致。");
  if (type === "LOW_REPEAT_CONVERSION" && !((get("photoNominationsPerHour") ?? 0) >= T.comparableRatio && (f.mainNominationRate.value ?? 1) < T.lowNominationRate && (f.contracts.value ?? 0) >= T.nominationMinimumContracts)) violations.push("LOW_REPEAT_CONVERSION条件不一致。");
  if (type === "OTHER_REVIEW") {
    const stable = (f.hourlyReward.value ?? 0) >= T.goodHourlyReward && (get("hourlyReward") ?? 0) >= T.comparableRatio && (f.mainNominationRate.value ?? 0) >= T.goodNominationRate;
    const lowTraffic = (get("hourlyReward") ?? 1) < T.comparableRatio && (get("photoNominationsPerHour") ?? 1) < T.lowRatio && (get("townUu") ?? 1) < T.lowTrafficRatio;
    const profile = (get("hourlyReward") ?? 1) < T.comparableRatio && (get("townUu") ?? 0) >= T.comparableRatio && (get("photoNominationsPer100Uu") ?? 1) < T.lowRatio && (f.townUu.value ?? 0) >= T.conversionMinimumUu;
    const repeat = (get("photoNominationsPerHour") ?? 0) >= T.comparableRatio && (f.mainNominationRate.value ?? 1) < T.lowNominationRate && (f.contracts.value ?? 0) >= T.nominationMinimumContracts;
    if (stable || lowTraffic || profile || repeat) violations.push("OTHER_REVIEWが明示診断条件と重複しています。");
  }
  const forbidden = cast.diagnosis.reviewTargets.includes("NONE") ? [] : cast.diagnosis.reviewTargets.filter((x) => x === "NONE");
  if (forbidden.length) violations.push("Review TargetにNONE以外とNONEが混在しています。");
  if (cast.diagnosis.primaryType === "OTHER_REVIEW" && cast.diagnosis.reviewTargets.length === 0) violations.push("OTHER_REVIEWの確認対象が空です。");
  if (cast.diagnosis.reviewTargets.some((x) => x === ("ATTENDANCE_INCREASE" as CastReviewTarget))) violations.push("出勤増加をReview Targetへ追加できません。");
  return { valid: violations.length === 0, violations };
}

export function buildCastDiagnosis(input: CastDiagnosisInput) {
  const facts = input.facts; const main = facts.filter((f) => (f.attendanceDays.value ?? 0) >= T.mainAttendanceDays); const eligible = facts.filter((f) => f.hourlyReward.value !== null && (f.workingHours.value ?? 0) >= T.minimumDiagnosisHours && ((f.attendanceDays.value ?? 0) >= T.comparisonMinimumDays || (f.workingHours.value ?? 0) >= T.comparisonMinimumHours || (f.contracts.value ?? 0) >= T.comparisonMinimumContracts)); let top: CastMonthlyFact[] = []; let method = "MANAGED_TOP_GROUP_MEDIAN";
  if (eligible.length >= 8) { const size = Math.ceil(eligible.length * T.comparisonTopPercentile); const sorted = [...eligible].sort((a, b) => (b.hourlyReward.value ?? -1) - (a.hourlyReward.value ?? -1) || a.castId.localeCompare(b.castId)); top = sorted.slice(0, size); } else if (eligible.length >= 5) { top = [...eligible].sort((a, b) => (b.hourlyReward.value ?? -1) - (a.hourlyReward.value ?? -1) || a.castId.localeCompare(b.castId)).slice(0, 2); } else if ((input.rollingFacts?.length ?? 0) > 0) { method = "ROLLING_THREE_MONTH_MANAGED_MEDIAN"; const rolling = input.rollingFacts!.filter((f) => f.hourlyReward.value !== null && (f.workingHours.value ?? 0) >= T.minimumDiagnosisHours && ((f.attendanceDays.value ?? 0) >= T.comparisonMinimumDays || (f.workingHours.value ?? 0) >= T.comparisonMinimumHours || (f.contracts.value ?? 0) >= T.comparisonMinimumContracts)).sort((a, b) => (b.hourlyReward.value ?? -1) - (a.hourlyReward.value ?? -1) || a.castId.localeCompare(b.castId)); top = rolling.slice(0, Math.max(0, Math.ceil(rolling.length * T.comparisonTopPercentile))); }
  const peerGroup = top.length >= T.minimumPeerCount ? top : []; const metricKeys: Array<[keyof CastMonthlyFact, string, string]> = [["femaleReward", "女子報酬", "円"], ["hourlyReward", "平均時給", "円/時間"], ["contracts", "成約数", "件"], ["attendanceDays", "出勤日数", "日"], ["workingHours", "出勤時間", "時間"], ["contractsPerDay", "1日平均成約", "件/日"], ["contractsPerHour", "1時間あたり成約", "件/時間"], ["townPv", "Town PV", "件"], ["townUu", "Town UU", "人"], ["heavenPageAccess", "Heavenアクセス", "件"], ["heavenDiaryPosts", "Heaven写メ日記", "件"], ["heavenMyGirlAdds", "Heavenマイガール増加", "件"], ["heavenFavoriteTalks", "Heavenオキニトーク送信", "件"], ["heavenMyGirlAddsPer100Access", "マイガール増加/100アクセス", "件"], ["heavenMyGirlAddsPer100TownUu", "マイガール増加/100UU", "件"], ["heavenFavoriteTalksPerAttendanceDay", "オキニトーク/出勤日", "件/日"], ["heavenFavoriteTalksPer100Access", "オキニトーク/100アクセス", "件"], ["photoNominations", "写真指名数", "件"], ["photoNominationsPerDay", "1日あたり写真指名", "件/日"], ["photoNominationsPerHour", "1時間あたり写真指名", "件/時間"], ["photoNominationsPer100Uu", "100UUあたり写真指名", "件"], ["mainNominations", "本指名数", "件"], ["mainNominationRate", "本指名率", "%"], ["repeatCount", "リピート数", "件"], ["repeatShare", "リピート構成比", "%"]];
  const comparisonAudit = buildCastComparisonAudit({ facts, resultTopGroup: top, rollingResultTopGroup: input.rollingFacts, mode: input.comparisonMode ?? "AXIS_SPECIFIC" });
  const casts: CastEngineCast[] = facts.map((fact) => { const hours = fact.workingHours.value; const range = hours === null || hours === 0 ? null : { minimum: hours * (1 - T.similarWorkingHoursRange), maximum: hours * (1 + T.similarWorkingHoursRange) }; const similar = range ? peerGroup.filter((p) => (p.workingHours.value ?? -1) >= range.minimum && (p.workingHours.value ?? Infinity) <= range.maximum) : []; const selected = similar.length >= T.minimumPeerCount ? similar : peerGroup; const peerSelection: CastPeerSelection = { method: selected.length >= T.minimumPeerCount ? similar.length >= T.minimumPeerCount ? "SIMILAR_WORKLOAD_TOP_GROUP_MEDIAN" : method === "ROLLING_THREE_MONTH_MANAGED_MEDIAN" ? "ROLLING_THREE_MONTH_MANAGED_MEDIAN" : "MANAGED_TOP_GROUP_MEDIAN" : "INSUFFICIENT", totalTopGroupCount: top.length, similarWorkloadCount: similar.length, workingHoursRange: range, fallbackReason: selected.length >= T.minimumPeerCount && similar.length < T.minimumPeerCount ? "近似稼働量が3名未満のため上位群中央値へ戻しました。" : selected.length < T.minimumPeerCount ? "比較群が3名未満です。" : null }; const comparisonSource = { method: peerSelection.method, peerCount: selected.length, medianSourceLabel: peerSelection.method === "SIMILAR_WORKLOAD_TOP_GROUP_MEDIAN" ? "近似稼働量上位群中央値" : peerSelection.method === "ROLLING_THREE_MONTH_MANAGED_MEDIAN" ? "直近3か月管轄全体結果上位群中央値" : peerSelection.method === "MANAGED_TOP_GROUP_MEDIAN" ? "管轄全体結果上位群中央値" : "比較不能" }; const comparisons = metricKeys.map(([key, label, unit]) => comparison(fact, selected, key, label, unit)); const conf = confidence(fact, selected.length); const diagnosis = diagnose(fact, comparisons, conf); const isEligible = eligible.some((x) => x.castId === fact.castId); const reasons = insufficientReasons(fact, selected.length); const isInsufficient = conf.overall.level === "INSUFFICIENT"; const priority: CastReviewPriority = diagnosis.primaryType === "INSUFFICIENT_DATA" ? "INSUFFICIENT" : diagnosis.primaryType === "STABLE_HIGH_EFFICIENCY" || diagnosis.primaryType === "LIMITED_BY_AVAILABILITY" ? "HEALTHY" : conf.overall.level === "HIGH" ? "PRIORITY" : conf.overall.level === "MEDIUM" ? "REVIEW" : "WATCH"; return { fact, isMainAttendanceCast: (fact.attendanceDays.value ?? 0) >= T.mainAttendanceDays, isComparisonEligible: isEligible, isTopGroupMember: top.some((x) => x.castId === fact.castId), comparisonEligibilityReasons: isEligible ? [] : ["比較候補条件未達"], insufficientReasons: isInsufficient ? reasons : ["OTHER"], insufficientPrimaryReason: isInsufficient ? reasons[0] ?? "OTHER" : null, peerSelection, comparisonSource, comparisons, diagnosis, confidence: conf, priority }; });
  for (const cast of casts) {
    const peerCount = cast.comparisons[0]?.peerCoverage.eligiblePeerCount ?? 0;
    if (peerCount < T.minimumPeerCount && peerGroup.filter((peer) => peer.castId !== cast.fact.castId).length >= T.minimumPeerCount) {
      const fallbackPeers = peerGroup.filter((peer) => peer.castId !== cast.fact.castId);
      cast.peerSelection = { ...cast.peerSelection, method: method === "ROLLING_THREE_MONTH_MANAGED_MEDIAN" ? "ROLLING_THREE_MONTH_MANAGED_MEDIAN" : "MANAGED_TOP_GROUP_MEDIAN", fallbackReason: "本人をPeer中央値から除外した結果、近似稼働量Peerが3名未満のため管轄上位群へフォールバックしました。" };
      cast.comparisons = metricKeys.map(([key, label, unit]) => comparison(cast.fact, fallbackPeers, key, label, unit));
      cast.comparisonSource = { method: cast.peerSelection.method, peerCount: fallbackPeers.length, medianSourceLabel: cast.peerSelection.method === "ROLLING_THREE_MONTH_MANAGED_MEDIAN" ? "直近3か月管轄全体結果上位群中央値" : "管轄全体結果上位群中央値" };
      cast.confidence = confidence(cast.fact, fallbackPeers.length);
      cast.diagnosis = diagnose(cast.fact, cast.comparisons, cast.confidence);
      cast.insufficientReasons = cast.confidence.overall.level === "INSUFFICIENT" ? insufficientReasons(cast.fact, fallbackPeers.length) : ["OTHER"];
      cast.insufficientPrimaryReason = cast.confidence.overall.level === "INSUFFICIENT" ? cast.insufficientReasons[0] ?? "OTHER" : null;
      cast.priority = cast.diagnosis.primaryType === "INSUFFICIENT_DATA" ? "INSUFFICIENT" : cast.diagnosis.primaryType === "STABLE_HIGH_EFFICIENCY" || cast.diagnosis.primaryType === "LIMITED_BY_AVAILABILITY" ? "HEALTHY" : cast.confidence.overall.level === "HIGH" ? "PRIORITY" : cast.confidence.overall.level === "MEDIUM" ? "REVIEW" : "WATCH";
    } else cast.comparisonSource.peerCount = peerCount;
  }
  // Step 3-A: replace legacy per-cast peer calculations with the shared,
  // metric-specific Comparison Engine audit. The public diagnosis shape is
  // preserved; axis and evidence are additive metadata only.
  const metricDefinitions = new Map(metricKeys.map(([key, label, unit]) => [String(key), { label, unit }]));
  for (const cast of casts) {
    const axisComparisons = comparisonAudit.comparisons
      .filter((comparison) => comparison.subjectCastId === cast.fact.castId)
      .map((comparison) => {
        const definition = metricDefinitions.get(comparison.metricKey);
        return definition ? comparisonFromAxis(comparison, definition.label, definition.unit) : null;
      })
      .filter((comparison): comparison is CastMetricComparison => comparison !== null);
    const first = comparisonAudit.comparisons.find((comparison) => comparison.subjectCastId === cast.fact.castId);
    if (!first) continue;
    const selection = first.selection;
    const legacyMethod: CastPeerSelection["method"] = first.selection.method === "SIMILAR_WORKING_HOURS_40" ? "SIMILAR_WORKLOAD_TOP_GROUP_MEDIAN" : first.selection.method === "RESULT_TOP_GROUP_FALLBACK" ? "MANAGED_TOP_GROUP_MEDIAN" : first.selection.method === "INSUFFICIENT" ? "INSUFFICIENT" : "SIMILAR_WORKLOAD_TOP_GROUP_MEDIAN";
    cast.comparisons = axisComparisons;
    cast.peerSelection = { method: legacyMethod, totalTopGroupCount: top.length, similarWorkloadCount: selection.validPeerCount, workingHoursRange: selection.workingHoursRange, fallbackReason: selection.fallbackReason };
    cast.comparisonSource = { method: legacyMethod, peerCount: selection.validPeerCount, medianSourceLabel: first.axisLabel };
    // A single axis may have fewer than three peers while another formal axis
    // is sufficient. Keep that shortage on the step, rather than collapsing
    // the whole cast to INSUFFICIENT_DATA.
    const diagnosticPeerKeys = new Set(["femaleReward", "hourlyReward", "contracts", "workingHours", "contractsPerDay", "contractsPerHour", "townPv", "townUu", "heavenPageAccess", "heavenDiaryPosts", "photoNominations", "photoNominationsPerDay", "photoNominationsPerHour", "photoNominationsPer100Uu", "photoNominationShare", "mainNominations", "mainNominationRate", "repeatCount", "repeatShare"]);
    const availablePeerCount = Math.max(...comparisonAudit.comparisons.filter((comparison) => comparison.subjectCastId === cast.fact.castId && diagnosticPeerKeys.has(comparison.metricKey)).map((comparison) => comparison.selection.validPeerCount), 0);
    cast.confidence = confidence(cast.fact, availablePeerCount);
    cast.diagnosis = diagnose(cast.fact, cast.comparisons, cast.confidence);
    cast.insufficientReasons = cast.confidence.overall.level === "INSUFFICIENT" ? insufficientReasons(cast.fact, selection.validPeerCount) : ["OTHER"];
    cast.insufficientPrimaryReason = cast.confidence.overall.level === "INSUFFICIENT" ? cast.insufficientReasons[0] ?? "OTHER" : null;
    cast.priority = cast.diagnosis.primaryType === "INSUFFICIENT_DATA" ? "INSUFFICIENT" : cast.diagnosis.primaryType === "STABLE_HIGH_EFFICIENCY" || cast.diagnosis.primaryType === "LIMITED_BY_AVAILABILITY" ? "HEALTHY" : cast.confidence.overall.level === "HIGH" ? "PRIORITY" : cast.confidence.overall.level === "MEDIUM" ? "REVIEW" : "WATCH";
  }
  const diagnosisTypes = ["STABLE_HIGH_EFFICIENCY", "LIMITED_BY_AVAILABILITY", "LOW_PAGE_TRAFFIC", "LOW_PROFILE_CONVERSION", "LOW_REPEAT_CONVERSION", "LOW_NEW_CUSTOMER_ACQUISITION", "OTHER_REVIEW", "INSUFFICIENT_DATA"] as CastDiagnosisType[];
  const diagnosisCountsOf = (items: CastEngineCast[]) => Object.fromEntries(diagnosisTypes.map((k) => [k, items.filter((c) => c.diagnosis.primaryType === k).length])) as Record<CastDiagnosisType, number>;
  const confidenceCountsOf = (items: CastEngineCast[]) => Object.fromEntries(["HIGH", "MEDIUM", "LOW", "INSUFFICIENT"].map((k) => [k, items.filter((c) => c.confidence.overall.level === k).length]));
  const mainCasts = casts.filter((c) => c.isMainAttendanceCast); const diagnosisCounts = diagnosisCountsOf(casts); const confidenceCounts = confidenceCountsOf(casts); const mainDiagnosisCounts = diagnosisCountsOf(mainCasts); const mainConfidenceCounts = confidenceCountsOf(mainCasts);
  const reasonKeys = ["ATTENDANCE_0_DAYS", "ATTENDANCE_1_DAY", "HOURS_BELOW_MINIMUM", "HOURLY_REWARD_UNCOMPUTABLE", "INSUFFICIENT_COMPARISON_GROUP", "CTI_MAJOR_DATA_MISSING", "OTHER"] as InsufficientReason[];
  const byPrimaryReason = Object.fromEntries(reasonKeys.map((k) => [k, casts.filter((c) => c.diagnosis.primaryType === "INSUFFICIENT_DATA" && c.insufficientPrimaryReason === k).length])) as Record<InsufficientReason, number>;
  const reasonOccurrences = Object.fromEntries(reasonKeys.map((k) => [k, casts.filter((c) => c.diagnosis.primaryType === "INSUFFICIENT_DATA").reduce((n, c) => n + (c.insufficientReasons.includes(k) ? 1 : 0), 0)])) as Record<InsufficientReason, number>;
  const coverageKeys = metricKeys.map(([key]) => { const p = peerMetric(key, peerGroup); return p.coverage; });
  const topGroupMedians = Object.fromEntries(metricKeys.map(([key]) => [String(key), peerMetric(key, top).metric]));
  return { period: { ...input.period, label: input.period.label ?? `${input.period.from}〜${input.period.to}` }, thresholds: thresholdsDto(), comparisonGroup: { scope: "MANAGED_ALL" as const, eligibleCastCount: eligible.length, topGroupCastCount: top.length, method: top.length > 0 ? method : "INSUFFICIENT", metricCoverage: coverageKeys, topGroupMedians }, summary: { totalFactCastCount: facts.length, totalCastCount: facts.length, mainAttendanceCastCount: main.length, nonMainAttendanceCastCount: facts.length - main.length, comparisonEligibleCount: eligible.length, topGroupCount: top.length, mainAttendanceDiagnosisCounts: mainDiagnosisCounts, allCastDiagnosisCounts: diagnosisCounts, mainAttendanceConfidenceCounts: mainConfidenceCounts, allCastConfidenceCounts: confidenceCounts, insufficientBreakdown: { byPrimaryReason, reasonOccurrences }, diagnosisCounts, confidenceCounts }, casts };
}
